rm -rf device/hisilicon/bigfish/build/device_common.mk
rm -rf device/hisilicon/bigfish/development/apps/HiDebugKit/project.properties
rm -rf device/hisilicon/bigfish/development/apps/HiErrorReport/ic_launcher-web.png
rm -rf device/hisilicon/bigfish/development/apps/HiErrorReport/proguard-project.txt
rm -rf device/hisilicon/bigfish/development/apps/HiErrorReport/project.properties
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/.classpath
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/.project
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/Android.mk
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/AndroidManifest.xml
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/ic_launcher-web.png
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/libs/android-support-v4.jar
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/libs/javalib.jar
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/proguard-project.txt
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/project.properties
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/drawable-hdpi/ic_launcher.jpg
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/drawable-hdpi/input_disable_wide.png
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/drawable-hdpi/input_focus_wide.png
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/drawable-hdpi/input_normal.png
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/drawable-hdpi/input_normal_wide.png
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/drawable-hdpi/left_focused.png
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/drawable-hdpi/left_normal.png
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/drawable-hdpi/line.png
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/drawable-hdpi/right_focused.png
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/drawable-hdpi/right_normal.png
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/drawable-mdpi/ic_launcher.jpg
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/drawable-xhdpi/ic_launcher.jpg
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/drawable-xxhdpi/ic_launcher.jpg
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/drawable/input_wide_selector.xml
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/layout/karaoke_set.xml
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/menu/main.xml
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/values-sw600dp/dimens.xml
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/values-sw720dp-land/dimens.xml
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/values-v11/styles.xml
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/values-v14/styles.xml
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/values-zh-rCN/arrays.xml
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/values-zh-rCN/strings.xml
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/values/arrays.xml
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/values/color.xml
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/values/dimens.xml
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/values/strings.xml
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/res/values/styles.xml
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/src/com/hisilicon/android/karaokesetting/Common.java
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/src/com/hisilicon/android/karaokesetting/EngineDialog.java
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/src/com/hisilicon/android/karaokesetting/HiKaraokeReceiver.java
rm -rf device/hisilicon/bigfish/development/apps/HiKaraokeSetting/src/com/hisilicon/android/karaokesetting/MainService.java
rm -rf device/hisilicon/bigfish/hardware/gpu/prebuilts/mali450/libEGL_mali.so
rm -rf device/hisilicon/bigfish/hardware/gpu/prebuilts/mali450/libGLESv1_CM_mali.so
rm -rf device/hisilicon/bigfish/hardware/gpu/prebuilts/mali450/libGLESv2_mali.so
rm -rf device/hisilicon/bigfish/hidolphin/component/player/utils/Android.mk
rm -rf device/hisilicon/bigfish/hidolphin/component/player/utils/Makefile
rm -rf device/hisilicon/bigfish/hidolphin/component/player/utils/svr_log.c
rm -rf device/hisilicon/bigfish/hidolphin/component/player/utils/svr_log.h
rm -rf device/hisilicon/bigfish/hidolphin/component/player/utils/svr_log_android.c
rm -rf device/hisilicon/bigfish/hidolphin/component/player/utils/svr_log_linux.c
rm -rf device/hisilicon/bigfish/hidolphin/component/player/utils/svr_sys.c
rm -rf device/hisilicon/bigfish/hidolphin/component/player/utils/svr_sys.h
rm -rf device/hisilicon/bigfish/hidolphin/component/player/utils/svr_sys_android.c
rm -rf device/hisilicon/bigfish/hidolphin/component/player/utils/svr_sys_linux.c
rm -rf device/hisilicon/bigfish/hidolphin/component/player/utils/test/Android.mk
rm -rf device/hisilicon/bigfish/hidolphin/component/player/utils/test/LogTest.cpp
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/Android.mk
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/data/Android.mk
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/data/aichangtv_20150210.apk
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/Android.mk
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/Launcher_Rainbow_0711.apk.bak
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/VST2.5.6.apk
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/VideoPhone.apk
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/XCgamecenter.apk
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/com.moretv.android-2.apk
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/com.shafa.market_2.6.7.apk
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/XCGame/libEventJNI4.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/moretv/libluajava_moretv.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/moretv/libutp.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/moretv/libvitvbasicphrasegrm.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/moretv/libvitvlsopen.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/moretv/libvitvlsopencfg.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/moretv/libvitvmsc.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/moretv/libvitvmspk.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/moretv/libvitvmspkcfg.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/moretv/libvitvphonecost.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/moretv/libvitvpinyin.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/moretv/libvitvsystemcommongrm.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/shafa/libEventInjector.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/shafa/libbspatch.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/vst/libasrfix_v5.3.0_net.myvst.v2.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/vst/libbdpush_V2_1.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/vst/libforcetv.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/vst/libiomx-gingerbread.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/vst/libiomx-hc.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/vst/libiomx-ics.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/vst/liblocSDK3.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/vst/libmyvst2.0.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/vst/libmyvstPush.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/vst/libp2pcore.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/vst/libsvttsjni.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/vst/liburlKey.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/vst/libvjplayer_jni.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/lib/vst/libyzs_usc.so
rm -rf device/hisilicon/bigfish/prebuilts/ThirdPartyApplications/system/xmxwangluocesu_1.1_2.apk
rm -rf device/hisilicon/bigfish/sdk/configs/hi3798mv100/hi3798mdmo1a_hi3798mv100_android_cfg.mak
rm -rf device/hisilicon/bigfish/sdk/configs/hi3798mv100/hi3798mdmo1a_hi3798mv100_android_recovery_cfg.mak
rm -rf device/hisilicon/bigfish/sdk/configs/hi3798mv100/hi3798mdmo1a_hi3798mv100_android_security_cfg.mak
rm -rf device/hisilicon/bigfish/sdk/configs/hi3798mv100/hi3798mdmo1b_hi3798mv100_android_cfg.mak
rm -rf device/hisilicon/bigfish/sdk/configs/hi3798mv100/hi3798mdmo1b_hi3798mv100_android_recovery_cfg.mak
rm -rf device/hisilicon/bigfish/sdk/configs/hi3798mv100/hi3798mdmo1b_hi3798mv100_android_security_cfg.mak
rm -rf device/hisilicon/bigfish/sdk/configs/hi3798mv100/hi3798mdmo1c_hi3798mv100_android_cfg.mak
rm -rf device/hisilicon/bigfish/sdk/configs/hi3798mv100/hi3798mdmo1c_hi3798mv100_android_recovery_cfg.mak
rm -rf device/hisilicon/bigfish/sdk/configs/hi3798mv100/hi3798mdmo1c_hi3798mv100_android_security_cfg.mak
rm -rf device/hisilicon/bigfish/sdk/configs/hi3798mv100/hi3798mdmo1d_hi3798mv100_android_cfg.mak
rm -rf device/hisilicon/bigfish/sdk/configs/hi3798mv100/hi3798mdmo1d_hi3798mv100_android_recovery_cfg.mak
rm -rf device/hisilicon/bigfish/sdk/configs/hi3798mv100/hi3798mdmo1d_hi3798mv100_android_security_cfg.mak
rm -rf device/hisilicon/bigfish/sdk/prebuilts/libhi_3g.so
rm -rf device/hisilicon/bigfish/sdk/prebuilts/libhi_cc.so
rm -rf device/hisilicon/bigfish/sdk/prebuilts/libhi_ttx.so
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/common/egl/inc/egl_native.h
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/common/egl/inc/hi_egl.h
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/common/egl/src/egl_native.c
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/common/egl/src/hi_egl.c
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/common/inc/hi_3d_config.h
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/common/key/inc/hi_engine_key.h
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/common/key/inc/hi_input_dfb.h
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/common/key/inc/hi_ir_remote.h
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/common/key/src/hi_engine_key.c
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/common/key/src/hi_input_dfb.c
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/common/key/src/hi_ir_remote.c
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/common/oesUtil.c
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/common/oesUtil.h
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/common/texture/inc/hi_texture.h
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/common/texture/src/hi_texture.c
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es11/texture/Makefile
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es11/texture/texture.c
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es11/texture/texture.h
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es11/tutorial/Makefile
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es11/tutorial/tutorial.c
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es11/tutorial/tutorial.h
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es20/Hello_Triangle/Hello_Triangle.c
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es20/Hello_Triangle/Makefile
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es20/sphere/Makefile
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es20/sphere/common.cpp
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es20/sphere/common.h
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es20/sphere/commonMath.cpp
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es20/sphere/commonMath.h
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es20/sphere/readme.txt
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es20/sphere/sphere_res/ps_es20t4_bgrnd.frag
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es20/sphere/sphere_res/ps_es20t4_glass.frag
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es20/sphere/sphere_res/stpeters_cross_mipmap_256.dds
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es20/sphere/sphere_res/vs_es20t4.vert
rm -rf device/hisilicon/bigfish/sdk/sample/gpu/mali700/es20/sphere/tutorial.cpp
rm -rf device/hisilicon/bigfish/sdk/sample/tuner/tuner_demo.c
rm -rf device/hisilicon/bigfish/sdk/sample/voip/Android.mk
rm -rf device/hisilicon/bigfish/sdk/sample/voip/Makefile
rm -rf device/hisilicon/bigfish/sdk/sample/voip/load_aci31
rm -rf device/hisilicon/bigfish/sdk/sample/voip/load_slic
rm -rf device/hisilicon/bigfish/sdk/sample/voip/load_voip
rm -rf device/hisilicon/bigfish/sdk/sample/voip/love1999.wav
rm -rf 'device/hisilicon/bigfish/sdk/sample/voip/readme(chs).txt'
rm -rf device/hisilicon/bigfish/sdk/sample/voip/readme.txt
rm -rf device/hisilicon/bigfish/sdk/sample/voip/serial.c
rm -rf device/hisilicon/bigfish/sdk/sample/voip/standard_G711A.wav
rm -rf device/hisilicon/bigfish/sdk/sample/voip/voip.c
rm -rf device/hisilicon/bigfish/sdk/sample/voip/voip_noalsa.c
rm -rf device/hisilicon/bigfish/sdk/sample/wifi/readme
rm -rf device/hisilicon/bigfish/sdk/source/boot/fastboot/arch/arm/cpu/hi3798mx/ddr_dataeye_training.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/fastboot/arch/arm/cpu/hi3798mx/ddr_dataeye_training.h
rm -rf device/hisilicon/bigfish/sdk/source/boot/fastboot/arch/arm/cpu/hi3798mx/ddr_training/Makefile
rm -rf device/hisilicon/bigfish/sdk/source/boot/fastboot/arch/arm/cpu/hi3798mx/ddr_training/boot.lds
rm -rf device/hisilicon/bigfish/sdk/source/boot/fastboot/arch/arm/cpu/hi3798mx/ddr_training/ddr_training.mk
rm -rf device/hisilicon/bigfish/sdk/source/boot/fastboot/arch/arm/cpu/hi3798mx/ddr_training/hi3798mx/Makefile
rm -rf device/hisilicon/bigfish/sdk/source/boot/fastboot/arch/arm/cpu/hi3798mx/ddr_training/hi3798mx/ddr_training.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/fastboot/arch/arm/cpu/hi3798mx/ddr_training/hi3798mx/ddr_training.h
rm -rf device/hisilicon/bigfish/sdk/source/boot/fastboot/arch/arm/cpu/hi3798mx/ddr_training/hi3798mx/ddr_training_printf.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/fastboot/arch/arm/cpu/hi3798mx/ddr_training/libc.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/fastboot/arch/arm/cpu/hi3798mx/ddr_training/libc.h
rm -rf device/hisilicon/bigfish/sdk/source/boot/fastboot/arch/arm/cpu/hi3798mx/ddr_training/start.S
rm -rf device/hisilicon/bigfish/sdk/source/boot/fastboot/arch/arm/cpu/hi3798mx/ddr_training/uart.S
rm -rf device/hisilicon/bigfish/sdk/source/boot/fastboot/arch/arm/cpu/hi3798mx/ddrphy_training.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/fastboot/arch/arm/cpu/hi3798mx/ddrphy_training_func.S
rm -rf device/hisilicon/bigfish/sdk/source/boot/fastboot/arch/arm/cpu/hi3798mx/ddrphy_training_print.S
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/godbox/boot/Makefile
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/godbox/boot/chip.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/godbox/boot/cpu.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/godbox/boot/ddrphy_train_route.S
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/godbox/boot/early_uart.S
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/godbox/boot/emmc_boot.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/godbox/boot/hinfc504_boot_nandr.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/godbox/boot/irq.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/godbox/boot/lowlevel_init.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/godbox/boot/platform.lds
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/godbox/boot/start.S
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/godbox/include/asm/io.h
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/godbox/include/platform.h
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/boot/Makefile
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/boot/chip.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/boot/cpu.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/boot/ddr_dataeye_training.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/boot/ddr_dataeye_training.h
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/boot/ddrphy_training.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/boot/ddrphy_training_func.S
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/boot/ddrphy_training_print.S
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/boot/early_timer.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/boot/early_uart.S
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/boot/emmc_boot.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/boot/himci_boot.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/boot/himci_boot_s40.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/boot/irq.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/boot/lowlevel_init.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/boot/platform.lds
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/boot/start.S
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/include/asm/io.h
rm -rf device/hisilicon/bigfish/sdk/source/boot/miniboot/arm/s40/include/platform.h
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/ALPS_TDAE/ALPS_TDAE_QAM128_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/ALPS_TDAE/ALPS_TDAE_QAM16_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/ALPS_TDAE/ALPS_TDAE_QAM256_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/ALPS_TDAE/ALPS_TDAE_QAM32_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/ALPS_TDAE/ALPS_TDAE_QAM64_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/CD1616/CD1616_QAM128_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/CD1616/CD1616_QAM16_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/CD1616/CD1616_QAM256_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/CD1616/CD1616_QAM32_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/CD1616/CD1616_QAM64_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/CD1616_DOUBLE/CD1616_DOUBLE_QAM128_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/CD1616_DOUBLE/CD1616_DOUBLE_QAM16_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/CD1616_DOUBLE/CD1616_DOUBLE_QAM256_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/CD1616_DOUBLE/CD1616_DOUBLE_QAM32_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/CD1616_DOUBLE/CD1616_DOUBLE_QAM64_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/MT2081/MT2081_QAM128_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/MT2081/MT2081_QAM16_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/MT2081/MT2081_QAM256_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/MT2081/MT2081_QAM32_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/MT2081/MT2081_QAM64_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/MXL203/MXL203_QAM128_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/MXL203/MXL203_QAM16_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/MXL203/MXL203_QAM256_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/MXL203/MXL203_QAM32_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/MXL203/MXL203_QAM64_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/MXL603/MXL603_QAM128_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/MXL603/MXL603_QAM16_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/MXL603/MXL603_QAM256_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/MXL603/MXL603_QAM32_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/MXL603/MXL603_QAM64_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/QAMPRINT_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/R820C/R820C_QAM128_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/R820C/R820C_QAM16_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/R820C/R820C_QAM256_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/R820C/R820C_QAM32_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/R820C/R820C_QAM64_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/TDA18250/TDA18250_QAM128_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/TDA18250/TDA18250_QAM16_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/TDA18250/TDA18250_QAM256_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/TDA18250/TDA18250_QAM32_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/TDA18250/TDA18250_QAM64_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/TDCC/TDCC_QAM128_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/TDCC/TDCC_QAM16_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/TDCC/TDCC_QAM256_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/TDCC/TDCC_QAM32_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/TDCC/TDCC_QAM64_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/TMX70707/TMX70707_QAM128_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/TMX70707/TMX70707_QAM16_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/TMX70707/TMX70707_QAM256_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/TMX70707/TMX70707_QAM32_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/TMX70707/TMX70707_QAM64_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/XG_3BL/XG_3BL_QAM128_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/XG_3BL/XG_3BL_QAM16_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/XG_3BL/XG_3BL_QAM256_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/XG_3BL/XG_3BL_QAM32_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/qamdata/XG_3BL/XG_3BL_QAM64_V200.txt
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/frontend/demod/x5hdqamv200/x5hdqamv200.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/higo/higo/adp_png.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/higo/higo/adp_png.h
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/higo/higo/hi_debug.h
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/higo/higo/higo_bmp.h
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/higo/higo/higo_common.h
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/higo/higo/higo_decbmp.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/higo/higo/higo_decgif.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/higo/higo/higo_gif.h
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/higo/higo/higo_io.c
rm -rf device/hisilicon/bigfish/sdk/source/boot/product/driver/higo/higo/higo_io.h
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/bin/write_flash
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/bin/write_otp
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/include/hi_unf_authupdate.h
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/include/hi_unf_ctit.h
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/lib/libhi_ctit_debug.a
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/lib/libhi_ctit_release.a
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/sample/burn_scsdata.c
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/sample/readme.txt
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/sample/readme_cn.txt
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/sample/write_otp.c
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/src/update/alg/bignum.c
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/src/update/alg/bignum.h
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/src/update/alg/bn_mul.h
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/src/update/alg/config.h
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/src/update/alg/crc32.c
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/src/update/alg/crc32.h
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/src/update/alg/rsa.c
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/src/update/alg/rsa.h
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/src/update/alg/sha2.c
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/src/update/alg/sha2.h
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/src/update/auth/auth.c
rm -rf device/hisilicon/bigfish/sdk/source/component/advca/ctit/src/update/auth/authdefine.h
rm -rf device/hisilicon/bigfish/sdk/source/component/ha_codec/src/dtsm6/2customer/Android.mk
rm -rf device/hisilicon/bigfish/sdk/source/component/ha_codec/src/dtsm6/2customer/include/.dirholder
rm -rf device/hisilicon/bigfish/sdk/source/component/ha_codec/src/dtsm6/2customer/lib/.dirholder
rm -rf device/hisilicon/bigfish/sdk/source/component/ha_codec/src/dtsm6/2customer/libdtshd_wrap.c
rm -rf device/hisilicon/bigfish/sdk/source/component/ha_codec/src/dtsm6/2customer/libdtshd_wrap.h
rm -rf device/hisilicon/bigfish/sdk/source/component/ha_effect/Android.mk
rm -rf device/hisilicon/bigfish/sdk/source/component/ha_effect/Makefile
rm -rf device/hisilicon/bigfish/sdk/source/component/ntfs/linux-3.10.y/tntfs_hi3798cv200_defconfig.ko
rm -rf device/hisilicon/bigfish/sdk/source/component/ntfs/linux-3.10.y/tntfs_hi3798cv200_loader_defconfig.ko
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/Android.mk
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/Makefile
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/api/Android.mk
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/api/Makefile
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/api/aud_adp/mpi_aud_adp.c
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/api/aud_adp/mpi_aud_adp_no_alsa.c
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/api/hme/mpi_voip_hme.c
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/api/hme/msg_trace.c
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/api/include/mpi_aud_adp.h
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/api/include/mpi_voip_hme.h
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/api/include/msg_trace.h
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/api/unf/hi_unf_voip.c
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/drv/Android.mk
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/drv/Makefile
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/drv/hme/inc/HME_Common_Audio.h
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/drv/hme/inc/HME_Common_Defines.h
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/drv/hme/inc/HME_commontype.h
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/drv/include/priv_audadp.h
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/drv/include/priv_hme.h
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/include/hi_error_voip.h
rm -rf device/hisilicon/bigfish/sdk/source/component/voip/include/hi_unf_voip.h
rm -rf device/hisilicon/bigfish/sdk/source/component/wifi/drv/usb_rtl8188eu/rtl8188EUS_linux_v4.3.0.6_12167.20140828.tar.gz
rm -rf device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/arch/arm/mach-hi3798mx/hiuapi.c
rm -rf device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/arch/arm/mach-hifone/hiuapi.c
rm -rf device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/include/uapi/linux/hiuapi.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/api/gpu/include/EGL/fbdev_window.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/aflt/src/aflt_func.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/aflt/src/aflt_main.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/aoe/src/aip/aoe_aip.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/aoe/src/aoe_main.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/aoe/src/aoe_reg.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/aoe/src/aop/aoe_aop.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/aoe/src/aop/aoe_cast.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/aoe/src/engine/aoe_engine.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/aoe/src/pp/.dirholder
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/common/basicop/basicop.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/common/linear/linear.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/common/mem/dsp_mem.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/common/resampler/resample.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/common/resampler/resample_rom.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/common/ringbuf/dsp_ringbuf.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/common/timer/system_timer.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/common/util/dsp_util.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/component/codec/iapcm_dec/iapcm_dec.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/component/codec/iapcm_dec/iapcm_dec_comp.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/component/effect/base_effect/base_effect_comp.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/component/effect/base_effect/base_effect_volume.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/sw_main.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/adsp/adsp_v1_1/hifi/system/map_region.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/avplay/Makefile
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/avplay/drv_avplay_intf.c
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/hifb/adp/include/hifb_config.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/hifb/adp/include/hifb_drv.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/hifb/adp/include/hifb_drv_common.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/hifb/adp/platform/alg/arm-hisiv200-linux/optm_alg_zme_coef.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/hifb/adp/platform/include/optm_define.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/hifb/adp/platform/include/optm_hifb.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/hifb/adp/platform/include/optm_reg_define.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/hifb/adp/platform/src/.dirholder
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/hifb/src/hifb_comm.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/hifb/src/hifb_dmabuf.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/hifb/src/hifb_fence.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/hifb/src/hifb_p.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/hifb/src/hifb_scrolltext.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/include/drv_avplay_ext.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/include/drv_avplay_ioctl.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/include/hi_drv_avplay.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/hal/hi3798mv100/pq_hal_acm.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/hal/hi3798mv100/pq_hal_acm_convert.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/hal/hi3798mv100/pq_hal_acm_convert.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/hal/hi3798mv100/pq_hal_dbdr.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/hal/hi3798mv100/pq_hal_dci.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/hal/hi3798mv100/pq_hal_dei.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/hal/hi3798mv100/pq_hal_fmd.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/hal/hi3798mv100/pq_hal_hsharpen.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/hal/hi3798mv100/pq_hal_nr.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/hal/hi3798mv100/pq_hal_sharpen.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/hal/hi3798mv100/pq_hal_sr.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/hal/hi3798mv100/pq_hal_zme.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_acm.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_acm_default.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_cccl.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_csc.c
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_dbdr_98m.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_dbdr_98m.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_dci.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_dci_default.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_dei.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_dim_divlut.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_es.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_ifmd.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_nr.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_pfmd.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_pq_table.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_scaler.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_scaler.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_sharpen.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_sr.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_ua.c
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_ua.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_zme.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/pq/pq_v3_0/mng/pq_mng_zme_default.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/bitstream.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/fsp.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/mem_manage.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/postprocess.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/public.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/syntax/avs.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/syntax/divx3.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/syntax/h264.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/syntax/hevc.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/syntax/hir8.c
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/syntax/hir9.c
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/syntax/mpeg2.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/syntax/mpeg4.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/syntax/mvc.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/syntax/syntax.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/syntax/vc1.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/syntax/vp6.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/syntax/vp8.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/vdm_drv.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/common/vfmw_ctrl.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiSCDV200/scd_drv.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiVDHV300R001/bitplane.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiVDHV300R001/hi_hal_r8.c
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiVDHV300R001/hi_hal_r9.c
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiVDHV300R001/vdm_hal.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiVDHV300R001/vdm_hal_avs.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiVDHV300R001/vdm_hal_divx3.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiVDHV300R001/vdm_hal_h264.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiVDHV300R001/vdm_hal_hevc.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiVDHV300R001/vdm_hal_mpeg2.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiVDHV300R001/vdm_hal_mpeg4.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiVDHV300R001/vdm_hal_real8.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiVDHV300R001/vdm_hal_real9.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiVDHV300R001/vdm_hal_vc1.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiVDHV300R001/vdm_hal_vp6.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiVDHV300R001/vdm_hal_vp8.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiVDHV400R002/hi_hal_r8.c
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/driver/HiVDHV400R002/hi_hal_r9.c
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/vfmw.S
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/vfmw_config.cfg
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100/HD_FULL_arm-hisiv200-linux/vfmw_make.cfg
rm -rf device/hisilicon/bigfish/sdk/source/rootfs/busybox/busybox-1.22.1.config/glibc.config
rm -rf device/hisilicon/bigfish/sdk/source/rootfs/busybox/busybox-1.22.1.config/glibc_ca_loader_debug.config
rm -rf device/hisilicon/bigfish/sdk/source/rootfs/busybox/busybox-1.22.1.config/glibc_ca_loader_release.config
rm -rf device/hisilicon/bigfish/sdk/source/rootfs/busybox/busybox-1.22.1.config/glibc_ca_net_root_debug.config
rm -rf device/hisilicon/bigfish/sdk/source/rootfs/busybox/busybox-1.22.1.config/glibc_ca_net_root_release.config
rm -rf device/hisilicon/bigfish/sdk/source/rootfs/busybox/busybox-1.22.1.config/glibc_ca_net_user.config
rm -rf device/hisilicon/bigfish/sdk/source/rootfs/busybox/busybox-1.22.1.config/glibc_ca_root_debug.config
rm -rf device/hisilicon/bigfish/sdk/source/rootfs/busybox/busybox-1.22.1.config/glibc_ca_root_final.config
rm -rf device/hisilicon/bigfish/sdk/source/rootfs/busybox/busybox-1.22.1.config/glibc_ca_root_release.config
rm -rf device/hisilicon/bigfish/sdk/source/rootfs/busybox/busybox-1.22.1.config/glibc_ca_user.config
rm -rf device/hisilicon/bigfish/sdk/source/rootfs/busybox/busybox-1.22.1.config/glibc_fpga.config
rm -rf device/hisilicon/bigfish/sdk/source/rootfs/busybox/busybox-1.22.1.config/glibc_lxc_user.config
rm -rf device/hisilicon/bigfish/sdk/source/rootfs/busybox/busybox-1.22.1.tar.bz2
rm -rf device/hisilicon/bigfish/sdk/source/rootfs/gdb/gdb-7.8.1.tar.bz2
rm -rf device/hisilicon/bigfish/sdk/source/rootfs/iptables/iptables-1.4.21.tar.bz2
rm -rf device/hisilicon/bigfish/sdk/source/rootfs/pppd/ppp-2.4.7.tar.bz2
rm -rf device/hisilicon/bigfish/sdk/source/rootfs/udev/udev-167.tar.bz2
rm -rf device/hisilicon/bigfish/sdk/tools/linux/toolchains/arm-histbv300-linux/arm-histbv300-linux.tar.bz2
rm -rf device/hisilicon/bigfish/sdk/tools/linux/toolchains/arm-histbv300-linux/cross.install
rm -rf device/hisilicon/bigfish/sdk/tools/windows/HiTool/HiTool-STB-3.0.30.zip
rm -rf device/hisilicon/bigfish/sdk/tools/windows/HiUpdateEdit/HiUpdateEdit-v1.0.0.6.zip
rm -rf device/hisilicon/bigfish/sdk/tools/windows/HiWorkbench/Hiworkbench_v3_0_3.zip
rm -rf device/hisilicon/bigfish/hardware/gpu/driver/include/EGL/mali_gbm.h
rm -rf device/hisilicon/bigfish/hardware/gpu/driver/include/EGL/platform_drm/EGL/eglplatform.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/gpu/mali4xx/linux/mali_memory_external.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/gpu/mali4xx/linux/mali_memory_ump.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/gpu/mali4xx/linux/mali_memory_util.c
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/gpu/mali4xx/linux/mali_memory_util.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/gpu/mali4xx/linux/mali_memory_virtual.c
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/gpu/mali4xx/linux/mali_memory_virtual.h
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/gpu/mali4xx/linux/mali_memory_manager.c
rm -rf device/hisilicon/bigfish/sdk/source/msp/drv/gpu/mali4xx/linux/mali_memory_manager.h
rm -rf device/hisilicon/bigfish/sdk/tools/windows/HiTool/HiTool-STB-3.1.11.zip
rm -rf device/hisilicon/bigfish/sdk/source/component/wifi/drv/usb_mt7601u/DPA_MT7601U_ANDROID_JB_3.0.0.6_20130830_SOFTAP.tar.gz
rm -rf device/hisilicon/bigfish/sdk/source/component/wifi/drv/usb_mt7601u/DPO_GPL_MT7601UAP_JB_SDK42_20130329.tar.gz
rm -rf device/hisilicon/bigfish/sdk/tools/windows/HiTool/HiTool-STB-3.1.11.zip
rm -rf device/hisilicon/bigfish/sdk/tools/windows/HiUpdateEdit/HiUpdateEdit-v1.0.0.8.zip

  
