	.arch armv7-a
	.fpu softvfp
	.eabi_attribute 20, 1
	.eabi_attribute 21, 1
	.eabi_attribute 23, 3
	.eabi_attribute 24, 1
	.eabi_attribute 25, 1
	.eabi_attribute 26, 2
	.eabi_attribute 30, 2
	.eabi_attribute 18, 4
	.file	"aoe_main.c"
@ GNU C (Hisilicon_v200(gcc4.4-290+glibc-2.11+eabi+nptl)) version 4.4.1 (arm-hisiv200-linux-gnueabi)
@	compiled by GNU C version 4.1.1 20061011 (Red Hat 4.1.1-30), GMP version 4.3.1, MPFR version 2.4.2.
@ GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
@ options passed:  -nostdinc
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/arch/arm/include
@ -Iarch/arm/include/generated
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/include
@ -Iinclude
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/arch/arm/include/uapi
@ -Iarch/arm/include/generated/uapi
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/include/uapi
@ -Iinclude/generated/uapi
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/adsp/adsp_v1_1
@ -Idrivers/msp/adsp/adsp_v1_1
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/arch/arm/mach-hi3798mx/include
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/common/include
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/common/api/include
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/common/drv/include
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/include
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/api/include
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/include
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/include
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/include/comp
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/./hifi/common/include
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/./hifi/aoe/include
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/./hifi/aflt/include
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/./hifi/aoe/src/include
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/./hifi/component/codec/iapcm_dec
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/./hifi/component/codec/iamp3_dec
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1/./hifi/component/effect/base_effect
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/adsp/adsp_v1_1
@ -imultilib armv7a_soft -iprefix
@ /opt/hisi-linux/x86-arm/arm-hisiv200-linux/bin/../lib/gcc/arm-hisiv200-linux-gnueabi/4.4.1/
@ -isysroot /opt/hisi-linux/x86-arm/arm-hisiv200-linux/bin/../target
@ -D__KERNEL__ -D__LINUX_ARM_ARCH__=7 -Uarm -DCHIP_TYPE_hi3796mv100
@ -DSDK_VERSION=HiSTBAndroidV600R001C00SPC064_v2016061301 -DHI_MCE_SUPPORT
@ -DHI_GPIOI2C_SUPPORT -DHI_LOG_SUPPORT=1 -DHI_LOG_LEVEL=4
@ -DHI_PROC_SUPPORT=1 -DHI_HDMI_SUPPORT_1_4 -DHI_KEYLED_SUPPORT
@ -DHI_HDCP_SUPPORT -DHI_SCI_SUPPORT -DHI_PVR_SUPPORT -DHI_VI_SUPPORT
@ -DHI_VENC_SUPPORT -DHI_AENC_SUPPORT -DHI_PQ_V3_0
@ -DHI_SND_AOE_SWSIMULATE_SUPPORT -DINTERLEAVED_OUTPUT
@ -DPCM_DECODER_SUPPORT -DHI_SND_TIMER_CAST -DKBUILD_STR(s)=#s
@ -DKBUILD_BASENAME=KBUILD_STR(aoe_main)
@ -DKBUILD_MODNAME=KBUILD_STR(hi_adsp) -isystem
@ /opt/hisi-linux/x86-arm/arm-hisiv200-linux/bin/../lib/gcc/arm-hisiv200-linux-gnueabi/4.4.1/include
@ -include
@ /home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/include/linux/kconfig.h
@ -MD drivers/msp/adsp/adsp_v1_1/./hifi/aoe/src/.aoe_main.o.d
@ /home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/adsp/adsp_v1_1/./hifi/aoe/src/aoe_main.c
@ -mlittle-endian -mapcs -mno-sched-prolog -mabi=aapcs-linux
@ -mno-thumb-interwork -marm -march=armv7-a -msoft-float -auxbase-strip
@ drivers/msp/adsp/adsp_v1_1/./hifi/aoe/src/aoe_main.o -O2 -Wall -Wundef
@ -Wstrict-prototypes -Wno-trigraphs -Werror-implicit-function-declaration
@ -Wno-format-security -Wframe-larger-than=1024
@ -Wdeclaration-after-statement -Wno-pointer-sign -p -fno-strict-aliasing
@ -fno-common -fno-delete-null-pointer-checks -fno-dwarf2-cfi-asm
@ -funwind-tables -fno-stack-protector -fno-omit-frame-pointer
@ -fno-optimize-sibling-calls -fno-strict-overflow -fconserve-stack
@ -fverbose-asm
@ options enabled:  -falign-loops -fargument-alias -fauto-inc-dec
@ -fbranch-count-reg -fcaller-saves -fcprop-registers -fcrossjumping
@ -fcse-follow-jumps -fdefer-pop -fearly-inlining
@ -feliminate-unused-debug-types -fexpensive-optimizations
@ -fforward-propagate -ffunction-cse -fgcse -fgcse-lm
@ -fguess-branch-probability -fident -fif-conversion -fif-conversion2
@ -findirect-inlining -finline -finline-functions-called-once
@ -finline-small-functions -fipa-cp -fipa-pure-const -fipa-reference
@ -fira-share-save-slots -fira-share-spill-slots -fivopts
@ -fkeep-static-consts -fleading-underscore -fmath-errno -fmerge-constants
@ -fmerge-debug-strings -fmove-loop-invariants -foptimize-register-move
@ -fpeephole -fpeephole2 -fprofile -fpromote-loop-indices
@ -freg-struct-return -fregmove -frename-registers -freorder-blocks
@ -freorder-functions -frerun-cse-after-loop -fsched-interblock
@ -fsched-spec -fsched-stalled-insns-dep -fschedule-insns -fschedule-insns2
@ -fsection-anchors -fsigned-zeros -fsplit-ivs-in-unroller
@ -fsplit-wide-types -fthread-jumps -ftoplevel-reorder -ftrapping-math
@ -ftree-builtin-call-dce -ftree-ccp -ftree-ch -ftree-copy-prop
@ -ftree-copyrename -ftree-cselim -ftree-dce -ftree-dominator-opts
@ -ftree-dse -ftree-fre -ftree-loop-im -ftree-loop-ivcanon
@ -ftree-loop-optimize -ftree-parallelize-loops= -ftree-pre -ftree-reassoc
@ -ftree-scev-cprop -ftree-sink -ftree-sra -ftree-switch-conversion
@ -ftree-ter -ftree-vect-loop-version -ftree-vrp -funit-at-a-time
@ -funroll-loops -funwind-tables -fverbose-asm -fweb
@ -fzero-initialized-in-bss -mapcs-frame -mglibc -mlittle-endian

@ Compiler executable checksum: fa59e0bd179ef45b3a3c3e6f3383fdac

	.text
	.align	2
	.global	AOE_Reset
	.type	AOE_Reset, %function
AOE_Reset:
	.fnstart
.LFB865:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {fp, ip, lr, pc}	@,
	.pad #4
	.save {fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r3, #:lower16:.LANCHOR0	@ tmp133,
	movt	r3, #:upper16:.LANCHOR0	@ tmp133,
	mov	r2, #0	@ tmp134,
	str	r2, [r3, #0]	@ tmp134, g_stAoeInitFlag
	ldmfd	sp, {fp, sp, pc}	@
	.fnend
	.size	AOE_Reset, .-AOE_Reset
	.align	2
	.global	AOE_FlushWKBuf
	.type	AOE_FlushWKBuf, %function
AOE_FlushWKBuf:
	.fnstart
.LFB870:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {fp, ip, lr, pc}	@,
	.pad #4
	.save {fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r3, #:lower16:.LANCHOR0	@ tmp133,
	movt	r3, #:upper16:.LANCHOR0	@ tmp133,
	mov	r2, #0	@ tmp134,
	str	r2, [r3, #4]	@ tmp134, g_stWkbuf.uWkBufIdx
	ldmfd	sp, {fp, sp, pc}	@
	.fnend
	.size	AOE_FlushWKBuf, .-AOE_FlushWKBuf
	.align	2
	.global	AOE_GetWKBuf
	.type	AOE_GetWKBuf, %function
AOE_GetWKBuf:
	.fnstart
.LFB871:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {fp, ip, lr, pc}	@,
	.pad #4
	.save {fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r3, #:lower16:.LANCHOR0	@ tmp149,
	movt	r3, #:upper16:.LANCHOR0	@ tmp149,
	ldr	r2, [r3, #4]	@ D.14998, g_stWkbuf.uWkBufIdx
	ldr	r1, [r3, #12]	@ g_stWkbuf.uWkBufBlockNumber, g_stWkbuf.uWkBufBlockNumber
	cmp	r2, r1	@ D.14998, g_stWkbuf.uWkBufBlockNumber
	ldr	r1, [r3, #16]	@ g_stWkbuf.uWkBufBase, g_stWkbuf.uWkBufBase
	addlt	ip, r2, #1	@ prephitmp.319, D.14998,
	ldrlt	r0, [r3, #8]	@ g_stWkbuf.uWkBufBlockSize, g_stWkbuf.uWkBufBlockSize
	movge	ip, #1	@ prephitmp.319,
	movge	r0, #0	@ prephitmp.317,
	str	ip, [r3, #4]	@ prephitmp.319, g_stWkbuf.uWkBufIdx
	mullt	r0, r0, r2	@ prephitmp.317, g_stWkbuf.uWkBufBlockSize, D.14998
	add	r0, r0, r1	@, prephitmp.317, g_stWkbuf.uWkBufBase
	ldmfd	sp, {fp, sp, pc}	@
	.fnend
	.size	AOE_GetWKBuf, .-AOE_GetWKBuf
	.align	2
	.global	AOE_ReleaseWKBuf
	.type	AOE_ReleaseWKBuf, %function
AOE_ReleaseWKBuf:
	.fnstart
.LFB872:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {fp, ip, lr, pc}	@,
	.pad #4
	.save {fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r3, #:lower16:.LANCHOR0	@ tmp134,
	movt	r3, #:upper16:.LANCHOR0	@ tmp134,
	ldr	r0, [r3, #4]	@ D.15010, g_stWkbuf.uWkBufIdx
	cmp	r0, #0	@ D.15010,
	ldreq	r0, [r3, #12]	@ g_stWkbuf.uWkBufBlockNumber, g_stWkbuf.uWkBufBlockNumber
	sub	r2, r0, #1	@ tmp140, g_stWkbuf.uWkBufBlockNumber,
	str	r2, [r3, #4]	@ tmp140, g_stWkbuf.uWkBufIdx
	ldmfd	sp, {fp, sp, pc}	@
	.fnend
	.size	AOE_ReleaseWKBuf, .-AOE_ReleaseWKBuf
	.align	2
	.global	AOE_GetWKBufSize
	.type	AOE_GetWKBufSize, %function
AOE_GetWKBufSize:
	.fnstart
.LFB873:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {fp, ip, lr, pc}	@,
	.pad #4
	.save {fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r3, #:lower16:.LANCHOR0	@ tmp135,
	movt	r3, #:upper16:.LANCHOR0	@ tmp135,
	ldr	r0, [r3, #8]	@, g_stWkbuf.uWkBufBlockSize
	ldmfd	sp, {fp, sp, pc}	@
	.fnend
	.size	AOE_GetWKBufSize, .-AOE_GetWKBufSize
	.align	2
	.global	AOE_GetBakBuf
	.type	AOE_GetBakBuf, %function
AOE_GetBakBuf:
	.fnstart
.LFB876:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {fp, ip, lr, pc}	@,
	.pad #4
	.save {fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r3, #:lower16:.LANCHOR0	@ tmp135,
	movt	r3, #:upper16:.LANCHOR0	@ tmp135,
	ldr	r0, [r3, #20]	@, g_pBakBuf
	ldmfd	sp, {fp, sp, pc}	@
	.fnend
	.size	AOE_GetBakBuf, .-AOE_GetBakBuf
	.align	2
	.global	AOE_SchedStatisticsInit
	.type	AOE_SchedStatisticsInit, %function
AOE_SchedStatisticsInit:
	.fnstart
.LFB877:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {fp, ip, lr, pc}	@,
	.pad #4
	.save {fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r3, #:lower16:.LANCHOR0	@ tmp134,
	movt	r3, #:upper16:.LANCHOR0	@ tmp134,
	ldr	r2, [r3, #0]	@ g_stAoeInitFlag, g_stAoeInitFlag
	cmp	r2, #0	@ g_stAoeInitFlag,
	ldrne	r3, [r3, #24]	@ g_pstAOEComReg.248, g_pstAOEComReg
	movne	r2, #0	@ tmp137,
	strne	r2, [r3, #12]	@ tmp137, <variable>.AOE_STATUS1.u32
	ldmfd	sp, {fp, sp, pc}	@
	.fnend
	.size	AOE_SchedStatisticsInit, .-AOE_SchedStatisticsInit
	.align	2
	.global	AOE_SchedStatisticsShow
	.type	AOE_SchedStatisticsShow, %function
AOE_SchedStatisticsShow:
	.fnstart
.LFB878:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {fp, ip, lr, pc}	@,
	.pad #4
	.save {fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r3, #:lower16:.LANCHOR0	@ tmp137,
	movt	r3, #:upper16:.LANCHOR0	@ tmp137,
	ldr	r2, [r3, #0]	@ g_stAoeInitFlag, g_stAoeInitFlag
	cmp	r2, #0	@ g_stAoeInitFlag,
	ldmeqfd	sp, {fp, sp, pc}	@
	cmp	r0, #0	@ enStatistics,
	beq	.L26	@,
	cmp	r0, #1	@ enStatistics,
	ldreq	r3, [r3, #24]	@ g_pstAOEComReg.445, g_pstAOEComReg
	streqh	r1, [r3, #14]	@ movhi	@ u16TimeOutCnt, <variable>.AOE_STATUS1.bits.schedule_timeout_cnt
	ldmfd	sp, {fp, sp, pc}	@
.L26:
	ldr	r3, [r3, #24]	@ g_pstAOEComReg.250, g_pstAOEComReg
	strh	r1, [r3, #12]	@ movhi	@ u16TimeOutCnt, <variable>.AOE_STATUS1.bits.excute_timeout_cnt
	ldmfd	sp, {fp, sp, pc}	@
	.fnend
	.size	AOE_SchedStatisticsShow, .-AOE_SchedStatisticsShow
	.align	2
	.global	AOE_GetThreadStatus
	.type	AOE_GetThreadStatus, %function
AOE_GetThreadStatus:
	.fnstart
.LFB881:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {fp, ip, lr, pc}	@,
	.pad #4
	.save {fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r3, #:lower16:.LANCHOR0	@ tmp135,
	movt	r3, #:upper16:.LANCHOR0	@ tmp135,
	ldr	r0, [r3, #28]	@, g_enAoeTaskStatus
	ldmfd	sp, {fp, sp, pc}	@
	.fnend
	.size	AOE_GetThreadStatus, .-AOE_GetThreadStatus
	.align	2
	.global	AOE_ProcThread
	.type	AOE_ProcThread, %function
AOE_ProcThread:
	.fnstart
.LFB880:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r3, r4, fp, ip, lr, pc}	@,
	.pad #4
	.save {r3, r4, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r4, #:lower16:.LANCHOR0	@ tmp134,
	movt	r4, #:upper16:.LANCHOR0	@ tmp134,
	mov	r2, #0	@ tmp135,
	ldr	r3, [r4, #0]	@ g_stAoeInitFlag, g_stAoeInitFlag
	str	r2, [r4, #28]	@ tmp135, g_enAoeTaskStatus
	cmp	r3, r2	@ g_stAoeInitFlag,
	ldmeqfd	sp, {r3, r4, fp, sp, pc}	@
	bl	AIP_Process	@
	bl	AOP_Process	@
	bl	ENGINE_Process	@
	ldr	r2, [r4, #32]	@ g_u32AoeTaskTicks, g_u32AoeTaskTicks
	mov	ip, #1	@ tmp139,
	str	ip, [r4, #28]	@ tmp139, g_enAoeTaskStatus
	add	r1, r2, ip	@ g_u32AoeTaskTicks.258, g_u32AoeTaskTicks,
	str	r1, [r4, #32]	@ g_u32AoeTaskTicks.258, g_u32AoeTaskTicks
	ands	r0, r1, ip	@ tmp143, g_u32AoeTaskTicks.258,
	streq	r0, [r4, #28]	@ tmp143, g_enAoeTaskStatus
	ldmfd	sp, {r3, r4, fp, sp, pc}	@
	.fnend
	.size	AOE_ProcThread, .-AOE_ProcThread
	.align	2
	.global	AOE_ProcThread_Sw
	.type	AOE_ProcThread_Sw, %function
AOE_ProcThread_Sw:
	.fnstart
.LFB879:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r3, r4, fp, ip, lr, pc}	@,
	.pad #4
	.save {r3, r4, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r4, #:lower16:.LANCHOR0	@ tmp134,
	movt	r4, #:upper16:.LANCHOR0	@ tmp134,
	mov	r2, #0	@ tmp135,
	ldr	r3, [r4, #0]	@ g_stAoeInitFlag, g_stAoeInitFlag
	str	r2, [r4, #28]	@ tmp135, g_enAoeTaskStatus
	cmp	r3, r2	@ g_stAoeInitFlag,
	ldmeqfd	sp, {r3, r4, fp, sp, pc}	@
	bl	AIP_Process	@
	bl	AOP_Process	@
	bl	ENGINE_Process	@
	ldr	ip, [r4, #32]	@ g_u32AoeTaskTicks, g_u32AoeTaskTicks
	mov	r2, #1	@ tmp139,
	str	r2, [r4, #28]	@ tmp139, g_enAoeTaskStatus
	add	r1, ip, r2	@ g_u32AoeTaskTicks.254, g_u32AoeTaskTicks,
	str	r1, [r4, #32]	@ g_u32AoeTaskTicks.254, g_u32AoeTaskTicks
	ands	r0, r1, #3	@ tmp143, g_u32AoeTaskTicks.254,
	streq	r0, [r4, #28]	@ tmp143, g_enAoeTaskStatus
	ldmfd	sp, {r3, r4, fp, sp, pc}	@
	.fnend
	.size	AOE_ProcThread_Sw, .-AOE_ProcThread_Sw
	.align	2
	.global	AOE_DeInitBakBuf
	.type	AOE_DeInitBakBuf, %function
AOE_DeInitBakBuf:
	.fnstart
.LFB875:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r3, r4, fp, ip, lr, pc}	@,
	.pad #4
	.save {r3, r4, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r4, #:lower16:.LANCHOR0	@ tmp133,
	movt	r4, #:upper16:.LANCHOR0	@ tmp133,
	mov	r0, #17	@,
	ldr	r1, [r4, #20]	@, g_pBakBuf
	bl	HI_ADSP_FREE_Aligned	@
	mov	r3, #0	@ tmp136,
	str	r3, [r4, #20]	@ tmp136, g_pBakBuf
	ldmfd	sp, {r3, r4, fp, sp, pc}	@
	.fnend
	.size	AOE_DeInitBakBuf, .-AOE_DeInitBakBuf
	.align	2
	.global	AOE_InitBakBuf
	.type	AOE_InitBakBuf, %function
AOE_InitBakBuf:
	.fnstart
.LFB874:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {fp, ip, lr, pc}	@,
	.pad #4
	.save {fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	mov	r2, r1	@ u32AlignToBytes, u32AlignToBytes
	mov	r1, r0	@, u32BakBufSize
	mov	r0, #17	@,
	bl	HI_ADSP_MALLOC_Aligned	@
	cmp	r0, #0	@ ptr
	movwne	r3, #:lower16:.LANCHOR0	@ tmp136,
	movtne	r3, #:upper16:.LANCHOR0	@ tmp136,
	strne	r0, [r3, #20]	@ ptr, g_pBakBuf
	ldmfd	sp, {fp, sp, pc}	@
	.fnend
	.size	AOE_InitBakBuf, .-AOE_InitBakBuf
	.align	2
	.global	AOE_DeInitWKBuf
	.type	AOE_DeInitWKBuf, %function
AOE_DeInitWKBuf:
	.fnstart
.LFB869:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r3, r4, fp, ip, lr, pc}	@,
	.pad #4
	.save {r3, r4, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r4, #:lower16:.LANCHOR0	@ tmp133,
	movt	r4, #:upper16:.LANCHOR0	@ tmp133,
	mov	r0, #17	@,
	ldr	r1, [r4, #16]	@, g_stWkbuf.uWkBufBase
	bl	HI_ADSP_FREE_Aligned	@
	add	r0, r4, #4	@, tmp133,
	mov	r1, #16	@,
	bl	__memzero	@
	ldmfd	sp, {r3, r4, fp, sp, pc}	@
	.fnend
	.size	AOE_DeInitWKBuf, .-AOE_DeInitWKBuf
	.align	2
	.global	AOE_InitWKBuf
	.type	AOE_InitWKBuf, %function
AOE_InitWKBuf:
	.fnstart
.LFB868:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, r6, r7, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, r6, r7, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r4, #:lower16:.LANCHOR0	@ tmp137,
	movt	r4, #:upper16:.LANCHOR0	@ tmp137,
	mov	r5, r1	@ u32WKBufNum, u32WKBufNum
	mov	r6, r0	@ u32WKBufSize, u32WKBufSize
	mov	r1, #16	@,
	add	r0, r4, #4	@, tmp137,
	mov	r7, r2	@ u32AlignToBytes, u32AlignToBytes
	bl	__memzero	@
	sub	r3, r5, #1	@ tmp139, u32WKBufNum,
	cmp	r3, #1	@ tmp139,
	ldmhifd	sp, {r4, r5, r6, r7, fp, sp, pc}	@
	mov	r2, r7	@, u32AlignToBytes
	mov	r0, #17	@,
	mul	r1, r6, r5	@, u32WKBufSize, u32WKBufNum
	bl	HI_ADSP_MALLOC_Aligned	@
	cmp	r0, #0	@ ptr
	strne	r6, [r4, #8]	@ u32WKBufSize, g_stWkbuf.uWkBufBlockSize
	strne	r0, [r4, #16]	@ ptr, g_stWkbuf.uWkBufBase
	strne	r5, [r4, #12]	@ u32WKBufNum, g_stWkbuf.uWkBufBlockNumber
	ldmfd	sp, {r4, r5, r6, r7, fp, sp, pc}	@
	.fnend
	.size	AOE_InitWKBuf, .-AOE_InitWKBuf
	.align	2
	.global	AOE_DeInit
	.type	AOE_DeInit, %function
AOE_DeInit:
	.fnstart
.LFB867:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r3, r4, fp, ip, lr, pc}	@,
	.pad #4
	.save {r3, r4, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r4, #:lower16:.LANCHOR0	@ tmp134,
	movt	r4, #:upper16:.LANCHOR0	@ tmp134,
	ldr	r3, [r4, #0]	@ g_stAoeInitFlag, g_stAoeInitFlag
	cmp	r3, #0	@ g_stAoeInitFlag,
	ldmeqfd	sp, {r3, r4, fp, sp, pc}	@
	bl	AIP_DeInit	@
	bl	AOP_DeInit	@
	bl	ENGINE_DeInit	@
	bl	AOE_DeInitWKBuf	@
	bl	AOE_DeInitBakBuf	@
	ldr	r0, [r4, #36]	@ g_u32RegMapAddr.240, g_u32RegMapAddr
	mov	r1, #0	@ tmp137,
	str	r1, [r4, #0]	@ tmp137, g_stAoeInitFlag
	cmp	r0, r1	@ g_u32RegMapAddr.240,
	str	r1, [r4, #24]	@ tmp137, g_pstAOEComReg
	ldmeqfd	sp, {r3, r4, fp, sp, pc}	@
	bl	__arm_iounmap	@
	ldmfd	sp, {r3, r4, fp, sp, pc}	@
	.fnend
	.size	AOE_DeInit, .-AOE_DeInit
	.align	2
	.global	AOE_Init
	.type	AOE_Init, %function
AOE_Init:
	.fnstart
.LFB866:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r3, r4, fp, ip, lr, pc}	@,
	.pad #4
	.save {r3, r4, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r4, #:lower16:.LANCHOR0	@ tmp135,
	movt	r4, #:upper16:.LANCHOR0	@ tmp135,
	ldr	r2, [r4, #0]	@ g_stAoeInitFlag, g_stAoeInitFlag
	cmp	r2, #0	@ g_stAoeInitFlag,
	ldmnefd	sp, {r3, r4, fp, sp, pc}	@
	mov	r1, #2048	@,
	movw	r0, #:lower16:-45056	@,
	movt	r0, #:upper16:-45056	@,
	bl	__arm_ioremap	@
	mov	r1, #2048	@,
	str	r0, [r4, #36]	@, g_u32RegMapAddr
	bl	__memzero	@
	ldr	r2, [r4, #36]	@ g_u32RegMapAddr.237, g_u32RegMapAddr
	add	r0, r2, #256	@, g_u32RegMapAddr.237,
	str	r2, [r4, #24]	@ g_u32RegMapAddr.237, g_pstAOEComReg
	bl	AIP_Init	@
	ldr	r1, [r4, #36]	@ g_u32RegMapAddr, g_u32RegMapAddr
	add	r0, r1, #768	@, g_u32RegMapAddr,
	bl	AOP_Init	@
	ldr	r0, [r4, #36]	@ g_u32RegMapAddr, g_u32RegMapAddr
	add	r0, r0, #64	@, g_u32RegMapAddr,
	bl	ENGINE_Init	@
	mov	r0, #61440	@,
	mov	r1, #2	@,
	mov	r2, #32	@,
	bl	AOE_InitWKBuf	@
	mov	r0, #15360	@,
	mov	r1, #8	@,
	bl	AOE_InitBakBuf	@
	mov	r3, #1	@ tmp149,
	str	r3, [r4, #0]	@ tmp149, g_stAoeInitFlag
	ldmfd	sp, {r3, r4, fp, sp, pc}	@
	.fnend
	.size	AOE_Init, .-AOE_Init
	.bss
	.align	2
.LANCHOR0 = . + 0
	.type	g_stAoeInitFlag, %object
	.size	g_stAoeInitFlag, 4
g_stAoeInitFlag:
	.space	4
	.type	g_stWkbuf, %object
	.size	g_stWkbuf, 16
g_stWkbuf:
	.space	16
	.type	g_pBakBuf, %object
	.size	g_pBakBuf, 4
g_pBakBuf:
	.space	4
	.type	g_pstAOEComReg, %object
	.size	g_pstAOEComReg, 4
g_pstAOEComReg:
	.space	4
	.type	g_enAoeTaskStatus, %object
	.size	g_enAoeTaskStatus, 4
g_enAoeTaskStatus:
	.space	4
	.type	g_u32AoeTaskTicks, %object
	.size	g_u32AoeTaskTicks, 4
g_u32AoeTaskTicks:
	.space	4
	.type	g_u32RegMapAddr, %object
	.size	g_u32RegMapAddr, 4
g_u32RegMapAddr:
	.space	4
	.ident	"GCC: (Hisilicon_v200(gcc4.4-290+glibc-2.11+eabi+nptl)) 4.4.1"
	.section	.note.GNU-stack,"",%progbits
