	.arch armv7-a
	.fpu softvfp
	.eabi_attribute 20, 1
	.eabi_attribute 21, 1
	.eabi_attribute 23, 3
	.eabi_attribute 24, 1
	.eabi_attribute 25, 1
	.eabi_attribute 26, 2
	.eabi_attribute 30, 2
	.eabi_attribute 18, 4
	.file	"postprocess.c"
@ GNU C (Hisilicon_v200(gcc4.4-290+glibc-2.11+eabi+nptl)) version 4.4.1 (arm-hisiv200-linux-gnueabi)
@	compiled by GNU C version 4.1.1 20061011 (Red Hat 4.1.1-30), GMP version 4.3.1, MPFR version 2.4.2.
@ GGC heuristics: --param ggc-min-expand=100 --param ggc-min-heapsize=131072
@ options passed:  -nostdinc
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/arch/arm/include
@ -Iarch/arm/include/generated
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/include
@ -Iinclude
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/arch/arm/include/uapi
@ -Iarch/arm/include/generated/uapi
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/include/uapi
@ -Iinclude/generated/uapi
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/vfmw/vfmw_v4.0
@ -Idrivers/msp/vfmw/vfmw_v4.0
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/arch/arm/mach-hi3798mx/include
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/common/include
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/common/drv/include
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/vfmw/vfmw_v4.0
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/vfmw/vfmw_v4.0/scene/stb
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/vfmw/vfmw_v4.0/firmware/common
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/vfmw/vfmw_v4.0/firmware/osal/linux_kernel
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/vfmw/vfmw_v4.0/firmware/common/softlib
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/vfmw/vfmw_v4.0/firmware/common/syntax
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/vfmw/vfmw_v4.0/firmware/driver/HiSCDV200
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/vfmw/vfmw_v4.0/firmware/driver/HiVDHV300R001
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/vfmw/vfmw_v4.0/firmware/product/Hi3798MV100
@ -I/home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/../../../source/msp/drv/vfmw/vfmw_v4.0/firmware/common_test/vdecko
@ -imultilib armv7a_soft -iprefix
@ /opt/hisi-linux/x86-arm/arm-hisiv200-linux/bin/../lib/gcc/arm-hisiv200-linux-gnueabi/4.4.1/
@ -isysroot /opt/hisi-linux/x86-arm/arm-hisiv200-linux/bin/../target
@ -D__KERNEL__ -D__LINUX_ARM_ARCH__=7 -Uarm -DCHIP_TYPE_hi3796mv100
@ -DSDK_VERSION=HiSTBAndroidV600R001C00SPC064_v2016061301 -DHI_MCE_SUPPORT
@ -DHI_GPIOI2C_SUPPORT -DHI_LOG_SUPPORT=1 -DHI_LOG_LEVEL=4
@ -DHI_PROC_SUPPORT=1 -DHI_HDMI_SUPPORT_1_4 -DHI_KEYLED_SUPPORT
@ -DHI_HDCP_SUPPORT -DHI_SCI_SUPPORT -DHI_PVR_SUPPORT -DHI_VI_SUPPORT
@ -DHI_VENC_SUPPORT -DHI_AENC_SUPPORT -DHI_PQ_V3_0 -DENV_ARMLINUX_KERNEL
@ -DDNR_DISABLE -DSCD_MP4_SLICE_ENABLE -DSUPPORT_JPEG_444
@ -DVFMW_EXTRA_TYPE_DEFINE -DPRODUCT_STB -D__VFMW_REGISTER_ISR__
@ -DQ_MATRIX_FIXED -DVFMW_VDH_V300R001_SUPPORT -DCFG_SCD_TIME_OUT=2000
@ -DCFG_VDH_TIME_OUT=500 -DVFMW_H264_SUPPORT -DVFMW_HEVC_SUPPORT
@ -DVFMW_MVC_SUPPORT -DVFMW_MPEG2_SUPPORT -DVFMW_MPEG4_SUPPORT
@ -DVFMW_AVS_SUPPORT -DVFMW_VC1_SUPPORT -DVFMW_BPD_H_SUPPORT
@ -DVFMW_REAL8_SUPPORT -DVFMW_REAL9_SUPPORT -DVFMW_VP6_SUPPORT
@ -DVFMW_VP8_SUPPORT -DVFMW_DIVX3_SUPPORT -DVFMW_H263_SUPPORT
@ -DVFMW_JPEG_SUPPORT -DVFMW_RAW_SUPPORT -DVFMW_USER_SUPPORT
@ -DCFG_MAX_CHAN_NUM=16 -DVFMW_DPRINT_SUPPORT -DVFMW_SCD_LOWDLY_SUPPORT
@ -DVFMW_AVSPLUS_SUPPORT -DVFMW_MODULE_LOWDLY_SUPPORT
@ -DVFMW_SYSTEM_REG_DISABLE -DHI_VDEC_SVDEC_BUILTIN -DKBUILD_STR(s)=#s
@ -DKBUILD_BASENAME=KBUILD_STR(postprocess)
@ -DKBUILD_MODNAME=KBUILD_STR(hi_vfmw) -isystem
@ /opt/hisi-linux/x86-arm/arm-hisiv200-linux/bin/../lib/gcc/arm-hisiv200-linux-gnueabi/4.4.1/include
@ -include
@ /home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/include/linux/kconfig.h
@ -MD drivers/msp/vfmw/vfmw_v4.0/firmware/common/.postprocess.o.d
@ /home/tangxiaodi/HiSTBAndroidV5/images_and_tools/release/hi3798mv100/verify/maintain_spc062/HiSTBAndroidV5_release/HiSTBAndroidV600R001C00SPC064/device/hisilicon/bigfish/sdk/source/kernel/linux-3.10.y/drivers/msp/vfmw/vfmw_v4.0/firmware/common/postprocess.c
@ -mlittle-endian -mapcs -mno-sched-prolog -mabi=aapcs-linux
@ -mno-thumb-interwork -marm -march=armv7-a -msoft-float -auxbase-strip
@ drivers/msp/vfmw/vfmw_v4.0/firmware/common/postprocess.o -O2 -Wall
@ -Wundef -Wstrict-prototypes -Wno-trigraphs
@ -Werror-implicit-function-declaration -Wno-format-security
@ -Wframe-larger-than=1024 -Wdeclaration-after-statement -Wno-pointer-sign
@ -p -fno-strict-aliasing -fno-common -fno-delete-null-pointer-checks
@ -fno-dwarf2-cfi-asm -funwind-tables -fno-stack-protector
@ -fno-omit-frame-pointer -fno-optimize-sibling-calls -fno-strict-overflow
@ -fconserve-stack -fno-pic -fverbose-asm
@ options enabled:  -falign-loops -fargument-alias -fauto-inc-dec
@ -fbranch-count-reg -fcaller-saves -fcprop-registers -fcrossjumping
@ -fcse-follow-jumps -fdefer-pop -fearly-inlining
@ -feliminate-unused-debug-types -fexpensive-optimizations
@ -fforward-propagate -ffunction-cse -fgcse -fgcse-lm
@ -fguess-branch-probability -fident -fif-conversion -fif-conversion2
@ -findirect-inlining -finline -finline-functions-called-once
@ -finline-small-functions -fipa-cp -fipa-pure-const -fipa-reference
@ -fira-share-save-slots -fira-share-spill-slots -fivopts
@ -fkeep-static-consts -fleading-underscore -fmath-errno -fmerge-constants
@ -fmerge-debug-strings -fmove-loop-invariants -foptimize-register-move
@ -fpeephole -fpeephole2 -fprofile -fpromote-loop-indices
@ -freg-struct-return -fregmove -frename-registers -freorder-blocks
@ -freorder-functions -frerun-cse-after-loop -fsched-interblock
@ -fsched-spec -fsched-stalled-insns-dep -fschedule-insns -fschedule-insns2
@ -fsection-anchors -fsigned-zeros -fsplit-ivs-in-unroller
@ -fsplit-wide-types -fthread-jumps -ftoplevel-reorder -ftrapping-math
@ -ftree-builtin-call-dce -ftree-ccp -ftree-ch -ftree-copy-prop
@ -ftree-copyrename -ftree-cselim -ftree-dce -ftree-dominator-opts
@ -ftree-dse -ftree-fre -ftree-loop-im -ftree-loop-ivcanon
@ -ftree-loop-optimize -ftree-parallelize-loops= -ftree-pre -ftree-reassoc
@ -ftree-scev-cprop -ftree-sink -ftree-sra -ftree-switch-conversion
@ -ftree-ter -ftree-vect-loop-version -ftree-vrp -funit-at-a-time
@ -funroll-loops -funwind-tables -fverbose-asm -fweb
@ -fzero-initialized-in-bss -mapcs-frame -mglibc -mlittle-endian

@ Compiler executable checksum: fa59e0bd179ef45b3a3c3e6f3383fdac

	.text
	.align	2
	.global	PostPro_GetRepairStratage
	.type	PostPro_GetRepairStratage, %function
PostPro_GetRepairStratage:
	.fnstart
.LFB1525:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {fp, ip, lr, pc}	@,
	.pad #4
	.save {fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	cmp	r0, #0	@ VidStd
	bne	.L2	@,
	ldrb	r0, [r1, #3]	@ zero_extendqisi2	@ <variable>.frame_mbs_only_flag, <variable>.frame_mbs_only_flag
	rsbs	r0, r0, #1	@ D.32252, <variable>.frame_mbs_only_flag
	movcc	r0, #0	@ D.32252
	ldmfd	sp, {fp, sp, pc}	@
.L2:
	cmp	r0, #15	@ VidStd,
	movne	r0, #0	@ D.32252,
	ldmnefd	sp, {fp, sp, pc}	@
	ldrb	r2, [r1, #3]	@ zero_extendqisi2	@ <variable>.frame_mbs_only_flag, <variable>.frame_mbs_only_flag
	rsbs	r0, r2, #1	@ D.32252, <variable>.frame_mbs_only_flag
	movcc	r0, #0	@ D.32252
	ldmfd	sp, {fp, sp, pc}	@
	.fnend
	.size	PostPro_GetRepairStratage, .-PostPro_GetRepairStratage
	.align	2
	.global	PostPro_CopyYuv
	.type	PostPro_CopyYuv, %function
PostPro_CopyYuv:
	.fnstart
.LFB1526:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r3, r4, r5, r6, fp, ip, lr, pc}	@,
	.pad #4
	.save {r3, r4, r5, r6, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r5, #:lower16:g_RepairParam	@ tmp144,
	movt	r5, #:upper16:g_RepairParam	@ tmp144,
	mov	r4, #1744	@ tmp143,
	movw	r2, #14604	@ tmp145,
	movw	ip, #:lower16:g_vdm_hal_fun_ptr	@ tmp165,
	mla	r4, r4, r1, r5	@ pRepairParam, tmp143, VdhId, tmp144
	ldr	r6, [r0, r2]	@ <variable>.VahbStride, <variable>.VahbStride
	mov	r5, #14592	@ tmp147,
	movt	ip, #:upper16:g_vdm_hal_fun_ptr	@ tmp165,
	mov	r2, #0	@ tmp154,
	mov	r3, r1	@ VdhId, VdhId
	mov	r1, #1	@ tmp153,
	str	r6, [r4, #12]	@ <variable>.VahbStride, <variable>.VahbStride
	ldr	r6, [r0, r5]	@ <variable>.DispFramePhyAddr, <variable>.DispFramePhyAddr
	ldr	ip, [ip, #104]	@ D.32289, g_vdm_hal_fun_ptr.pfun_VDMHAL_PrepareRepair
	str	r6, [r4, #4]	@ <variable>.DispFramePhyAddr, <variable>.ImageAddr
	cmp	ip, r2	@ D.32289,
	ldr	r5, [r0, r5]	@ <variable>.DispFramePhyAddr, <variable>.DispFramePhyAddr
	str	r5, [r4, #8]	@ <variable>.DispFramePhyAddr, <variable>.Image2DAddr
	ldr	r6, [r0, #220]	@ <variable>.FwdRefPicPhyAddr, <variable>.FwdRefPicPhyAddr
	str	r6, [r4, #16]	@ <variable>.FwdRefPicPhyAddr, <variable>.RefImageAddr
	ldr	r5, [r0, #228]	@ <variable>.CurPmvPhyAddr, <variable>.CurPmvPhyAddr
	str	r5, [r4, #20]	@ <variable>.CurPmvPhyAddr, <variable>.CurrPmvAddr
	ldrh	r6, [r0, #164]	@ D.32275, <variable>.PicWidthInMb
	str	r6, [r4, #24]	@ D.32275, <variable>.ImageWidth
	ldrh	r5, [r0, #166]	@ D.32277, <variable>.PicHeightInMb
	str	r1, [r4, #32]	@ tmp153, <variable>.IsFrame
	str	r2, [r4, #36]	@ tmp154, <variable>.ImageCSP
	mul	r6, r6, r5	@ tmp158, D.32275, D.32277
	str	r5, [r4, #28]	@ D.32277, <variable>.ImageHeight
	movw	r5, #14660	@ tmp161,
	str	r1, [r4, #840]	@ tmp153, <variable>.ValidGroupNum
	strh	r2, [r4, #40]	@ movhi	@ tmp154, <variable>.StartMbn
	sub	r6, r6, #1	@ tmp160, tmp158,
	strh	r6, [r4, #42]	@ movhi	@ tmp160, <variable>.EndMbn
	ldr	r5, [r0, r5]	@ <variable>.Compress_en, <variable>.Compress_en
	moveq	r0, r1	@ D.32292, tmp153
	str	r1, [r4, #856]	@ tmp153, <variable>.FullRepair
	str	r2, [r4, #852]	@ tmp154, <variable>.Pic_type
	str	r5, [r4, #848]	@ <variable>.Compress_en, <variable>.Compress_en
	ldmeqfd	sp, {r3, r4, r5, r6, fp, sp, pc}	@
	mov	r1, r0	@, pMp4DecParam
	mov	r0, #2	@,
	blx	ip	@ D.32289
	subs	r0, r0, #0	@ D.32292,,
	movne	r0, #1	@ D.32292
	ldmfd	sp, {r3, r4, r5, r6, fp, sp, pc}	@
	.fnend
	.size	PostPro_CopyYuv, .-PostPro_CopyYuv
	.align	2
	.global	PostPro_BubbleSort
	.type	PostPro_BubbleSort, %function
PostPro_BubbleSort:
	.fnstart
.LFB1538:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, r6, r7, r8, sl, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, r6, r7, r8, sl, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	ldr	r7, [r0, #8]	@ n, <variable>.DecSliceNum
	mov	r5, r0	@ pDecReport, pDecReport
	cmp	r7, #1	@ n,
	movhi	r6, #1	@ i,
	ldmlsfd	sp, {r4, r5, r6, r7, r8, sl, fp, sp, pc}	@
.L13:
	rsb	r0, r6, r7	@ pretmp.536, i, n
	mov	r4, #0	@ flag,
	tst	r0, #1	@ pretmp.536,
	mov	r3, r5	@ ivtmp.551, pDecReport
	mov	r1, r4	@ j, flag
	beq	.L16	@,
	cmp	r0, #0	@ pretmp.536,
	ldmlsfd	sp, {r4, r5, r6, r7, r8, sl, fp, sp, pc}	@
	ldrh	r3, [r5, #12]	@ D.33531, <variable>.SliceMbRange
	mov	r1, #1	@ j,
	ldrh	r2, [r5, #16]	@ D.33533, <variable>.SliceMbRange
	cmp	r3, r2	@ D.33531, D.33533
	bls	.L19	@,
	ldrh	ip, [r5, #14]	@ D.33536, <variable>.SliceMbRange
	mov	r4, r1	@ flag, j
	strh	r2, [r5, #12]	@ movhi	@ D.33533, <variable>.SliceMbRange
	ldrh	r2, [r5, #18]	@, <variable>.SliceMbRange
	strh	r3, [r5, #16]	@ movhi	@ D.33531, <variable>.SliceMbRange
	strh	ip, [r5, #18]	@ movhi	@ D.33536, <variable>.SliceMbRange
	strh	r2, [r5, #14]	@ movhi	@, <variable>.SliceMbRange
.L19:
	add	r3, r5, #4	@ ivtmp.551, pDecReport,
.L16:
	cmp	r0, r1	@ pretmp.536, j
	add	r2, r3, #4	@ tmp194, ivtmp.551,
	add	r1, r1, #1	@ tmp195, j,
	bls	.L25	@,
.L15:
	ldrh	ip, [r3, #12]	@ D.33531, <variable>.SliceMbRange
	add	r1, r1, #1	@ j, tmp195,
	ldrh	r8, [r3, #16]	@ D.33533, <variable>.SliceMbRange
	cmp	ip, r8	@ D.33531, D.33533
	bls	.L14	@,
	ldrh	sl, [r3, #14]	@ D.33536, <variable>.SliceMbRange
	mov	r4, #1	@ flag,
	strh	r8, [r3, #12]	@ movhi	@ D.33533, <variable>.SliceMbRange
	ldrh	r8, [r3, #18]	@, <variable>.SliceMbRange
	strh	ip, [r3, #16]	@ movhi	@ D.33531, <variable>.SliceMbRange
	strh	sl, [r3, #18]	@ movhi	@ D.33536, <variable>.SliceMbRange
	strh	r8, [r3, #14]	@ movhi	@, <variable>.SliceMbRange
.L14:
	ldrh	r3, [r2, #12]	@ D.33531, <variable>.SliceMbRange
	ldrh	ip, [r2, #16]	@ D.33533, <variable>.SliceMbRange
	cmp	r3, ip	@ D.33531, D.33533
	bls	.L22	@,
	ldrh	r8, [r2, #18]	@, <variable>.SliceMbRange
	mov	r4, #1	@ flag,
	strh	ip, [r2, #12]	@ movhi	@ D.33533, <variable>.SliceMbRange
	ldrh	ip, [r2, #14]	@ D.33536, <variable>.SliceMbRange
	strh	r3, [r2, #16]	@ movhi	@ D.33531, <variable>.SliceMbRange
	strh	r8, [r2, #14]	@ movhi	@, <variable>.SliceMbRange
	strh	ip, [r2, #18]	@ movhi	@ D.33536, <variable>.SliceMbRange
.L22:
	cmp	r0, r1	@ pretmp.536, j
	add	r3, r2, #4	@ ivtmp.551, tmp194,
	add	r2, r3, #4	@ tmp194, ivtmp.551,
	add	r1, r1, #1	@ tmp195, j,
	bhi	.L15	@,
.L25:
	cmp	r4, #0	@ flag,
	ldmeqfd	sp, {r4, r5, r6, r7, r8, sl, fp, sp, pc}	@
	add	r6, r6, #1	@ i, i,
	cmp	r7, r6	@ n, i
	bhi	.L13	@,
	ldmfd	sp, {r4, r5, r6, r7, r8, sl, fp, sp, pc}	@
	.fnend
	.size	PostPro_BubbleSort, .-PostPro_BubbleSort
	.align	2
	.global	PostPro_SetDecReport
	.type	PostPro_SetDecReport, %function
PostPro_SetDecReport:
	.fnstart
.LFB1540:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r3, r4, r5, r6, fp, ip, lr, pc}	@,
	.pad #4
	.save {r3, r4, r5, r6, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	mov	r5, r0	@ VidStd, VidStd
	mov	r6, r1	@ pDecParam, pDecParam
	mov	r0, r2	@, pDecReport
	mov	r1, #816	@,
	mov	r4, r2	@ pDecReport, pDecReport
	bl	__memzero	@
	cmp	r5, #16	@ VidStd,
	ldrls	pc, [pc, r5, asl #2]	@ VidStd
	b	.L27	@
.L40:
	.word	.L37
	.word	.L37
	.word	.L37
	.word	.L37
	.word	.L27
	.word	.L37
	.word	.L33
	.word	.L27
	.word	.L37
	.word	.L37
	.word	.L37
	.word	.L37
	.word	.L37
	.word	.L37
	.word	.L27
	.word	.L37
	.word	.L37
.L33:
	ldrb	r3, [r6, #8]	@ zero_extendqisi2	@ <variable>.PicStruct, <variable>.PicStruct
	cmp	r3, #1	@ <variable>.PicStruct,
	beq	.L44	@,
.L37:
	mov	r1, #0	@ movhi	@,
	mov	r0, #1	@ tmp213,
	strh	r1, [r4, #14]	@ movhi	@, <variable>.SliceMbRange
	strh	r1, [r4, #12]	@ movhi	@, <variable>.SliceMbRange
	str	r0, [r4, #8]	@ tmp213, <variable>.DecSliceNum
.L41:
	mov	r0, #0	@,
	ldmfd	sp, {r3, r4, r5, r6, fp, sp, pc}	@
.L27:
	movw	r1, #:lower16:.LC0	@,
	movw	r2, #:lower16:.LANCHOR0	@,
	movt	r1, #:upper16:.LC0	@,
	movt	r2, #:upper16:.LANCHOR0	@,
	movw	r3, #1860	@,
	mov	r0, #0	@,
	bl	dprint_vfmw	@
	b	.L41	@
.L44:
	mov	r3, #0	@ movhi	@,
	mov	r2, #2	@ tmp164,
	strh	r3, [r4, #12]	@ movhi	@, <variable>.SliceMbRange
	strh	r3, [r4, #14]	@ movhi	@, <variable>.SliceMbRange
	str	r2, [r4, #8]	@ tmp164, <variable>.DecSliceNum
	ldrh	ip, [r6, #50]	@ <variable>.PicHeightInMb, <variable>.PicHeightInMb
	ldrh	lr, [r6, #48]	@ <variable>.PicWidthInMb, <variable>.PicWidthInMb
	mul	r1, lr, ip	@ tmp171, <variable>.PicWidthInMb, <variable>.PicHeightInMb
	add	r0, r1, r1, lsr #31	@, tmp174, tmp171, tmp171,
	mov	r3, r0, asr #1	@ tmp175, tmp174,
	strh	r3, [r4, #16]	@ movhi	@ tmp175, <variable>.SliceMbRange
	ldrh	r2, [r6, #48]	@ <variable>.PicWidthInMb, <variable>.PicWidthInMb
	ldrh	lr, [r6, #50]	@ <variable>.PicHeightInMb, <variable>.PicHeightInMb
	mul	ip, r2, lr	@ tmp178, <variable>.PicWidthInMb, <variable>.PicHeightInMb
	add	r1, ip, ip, lsr #31	@, tmp181, tmp178, tmp178,
	mov	r0, r1, asr #1	@ tmp182, tmp181,
	strh	r0, [r4, #18]	@ movhi	@ tmp182, <variable>.SliceMbRange
	b	.L41	@
	.fnend
	.size	PostPro_SetDecReport, .-PostPro_SetDecReport
	.align	2
	.global	PostPro_GetDivx3MbGroup
	.type	PostPro_GetDivx3MbGroup, %function
PostPro_GetDivx3MbGroup:
	.fnstart
.LFB1537:
	@ args = 0, pretend = 0, frame = 24
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	.pad #28
	sub	sp, sp, #28	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	ldr	r2, [r1, #8]	@ D.33459, <variable>.DecSliceNum
	sub	r3, r2, #1	@ tmp156, D.33459,
	cmp	r3, #3	@ tmp156,
	bhi	.L62	@,
	ldr	r7, [r0, #28]	@ <variable>.ImageHeight, <variable>.ImageHeight
	mov	r6, #0	@ tmp158,
	ldr	r5, [r0, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	mov	ip, r6	@ i, tmp158
	str	r6, [r0, #856]	@ tmp158, <variable>.FullRepair
	mvn	r8, #0	@ old_slice_end_mbn,
	ldr	r6, [r1, #8]	@ prephitmp.615, <variable>.DecSliceNum
	add	r9, r0, #872	@, pRepairParam,
	mul	r5, r5, r7	@ total_mbn, <variable>.ImageWidth, <variable>.ImageHeight
	str	r1, [fp, #-68]	@ pDecReport, %sfp
	add	r2, r1, r6, asl #2	@, tmp163, pDecReport, prephitmp.615,
	str	r9, [fp, #-64]	@, %sfp
	mov	r7, r0	@ pLocalRepairParam, pRepairParam
	mov	r9, ip	@ dectopfldmbs, i
	add	sl, r5, r8	@, total_mbn,
	mov	r4, r8	@ old_slice_start_mbn, old_slice_start_mbn
	str	sl, [fp, #-56]	@, %sfp
	mov	sl, r8	@ old_slice_start_mbn, old_slice_end_mbn
	mov	r3, r5, asr #1	@, total_mbn,
	str	r3, [fp, #-52]	@, %sfp
	uxth	r3, r5	@, total_mbn
	str	r3, [fp, #-48]	@, %sfp
	ldr	r3, [fp, #-52]	@, %sfp
	add	r3, r3, r8	@,,
	str	r3, [fp, #-60]	@, %sfp
	ldr	r3, [fp, #-48]	@, %sfp
	strh	r3, [r2, #14]	@ movhi	@, <variable>.SliceMbRange
	strh	r3, [r2, #12]	@ movhi	@, <variable>.SliceMbRange
	ldr	r3, [fp, #-68]	@ ivtmp.630, %sfp
	str	r0, [fp, #-68]	@ pRepairParam, %sfp
.L54:
	ldrh	r2, [r3, #12]	@ D.33470, <variable>.SliceMbRange
	ldrh	r0, [r3, #14]	@ curr_slice_end_mbn, <variable>.SliceMbRange
	cmp	r2, r5	@ D.33470, total_mbn
	cmple	r0, r5	@, curr_slice_end_mbn, total_mbn
	bgt	.L50	@,
	cmp	r2, r0	@ D.33470, curr_slice_end_mbn
	bgt	.L50	@,
	cmp	r2, r8	@ D.33470, old_slice_end_mbn
	movlt	r8, r4	@ old_slice_end_mbn, old_slice_start_mbn
	add	r8, r8, #1	@ tmp177, old_slice_end_mbn,
	cmp	r2, r8	@ D.33470, tmp177
	ble	.L52	@,
	ldr	sl, [r7, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r6, r4, r4, lsr #31	@, tmp186, old_slice_start_mbn, old_slice_start_mbn,
	uxth	r4, r9	@ D.33487, dectopfldmbs
	sub	r8, r2, #1	@ tmp195, D.33470,
	rsb	r6, r4, r6	@ tmp188, D.33487, tmp186
	rsb	r4, r4, r8	@ tmp197, D.33487, tmp195
	add	sl, r7, sl, asl #2	@, tmp180, pLocalRepairParam, <variable>.ValidGroupNum,
	strh	r6, [sl, #40]	@ movhi	@ tmp188, <variable>.StartMbn
	ldr	r6, [r7, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r8, r7, r6, asl #2	@, tmp193, pLocalRepairParam, <variable>.ValidGroupNum,
	strh	r4, [r8, #42]	@ movhi	@ tmp197, <variable>.EndMbn
	ldr	r6, [r7, #32]	@ <variable>.IsFrame, <variable>.IsFrame
	ldr	r8, [r7, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	cmp	r6, #0	@ <variable>.IsFrame,
	add	r4, r8, #1	@ tmp199, <variable>.ValidGroupNum,
	str	r4, [r7, #840]	@ tmp199, <variable>.ValidGroupNum
	bne	.L61	@,
	ldr	r4, [fp, #-60]	@, %sfp
	cmp	r2, r4	@ D.33470,
	bge	.L60	@,
.L61:
	ldr	r6, [r1, #8]	@ prephitmp.615, <variable>.DecSliceNum
.L52:
	sub	r8, r6, #1	@ temp.636, prephitmp.615,
	cmp	r8, ip	@ temp.636, i
	beq	.L63	@,
.L53:
	mov	r8, r0	@ old_slice_end_mbn, curr_slice_end_mbn
	mov	r4, r2	@ old_slice_start_mbn, D.33470
.L50:
	add	ip, ip, #1	@ i, i,
	add	r3, r3, #4	@ ivtmp.630, ivtmp.630,
	cmp	ip, r6	@ i, prephitmp.615
	bls	.L54	@,
	mov	r3, #0	@ D.33464,
.L47:
	mov	r0, r3	@, D.33464
	sub	sp, fp, #40
	ldmfd	sp, {r4, r5, r6, r7, r8, r9, sl, fp, sp, pc}
.L63:
	add	r4, r1, ip, asl #2	@, tmp203, pDecReport, i,
	ldr	sl, [fp, #-56]	@, %sfp
	ldrh	r8, [r4, #14]	@ D.33504, <variable>.SliceMbRange
	cmp	r8, sl	@ D.33504,
	bge	.L53	@,
	ldr	r0, [fp, #-68]	@ pRepairParam, %sfp
	ldr	r3, [fp, #-48]	@, %sfp
	ldr	ip, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	sub	r1, r3, #1	@ tmp216,,
	mov	r3, #0	@ D.33464,
	add	r2, r0, ip, asl #2	@, tmp208, pRepairParam, <variable>.ValidGroupNum,
	strh	r8, [r2, #40]	@ movhi	@ D.33504, <variable>.StartMbn
	ldr	ip, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r2, r0, ip, asl #2	@, tmp214, pRepairParam, <variable>.ValidGroupNum,
	strh	r1, [r2, #42]	@ movhi	@ tmp216, <variable>.EndMbn
	ldr	ip, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r1, ip, #1	@ tmp218, <variable>.ValidGroupNum,
	str	r1, [r0, #840]	@ tmp218, <variable>.ValidGroupNum
	b	.L47	@
.L60:
	ldr	r6, [r1, #8]	@ prephitmp.615, <variable>.DecSliceNum
	ldr	r7, [fp, #-64]	@ pLocalRepairParam, %sfp
	ldr	r9, [fp, #-52]	@ dectopfldmbs, %sfp
	b	.L52	@
.L62:
	mov	r0, #0	@,
	movw	r1, #:lower16:.LC1	@,
	movt	r1, #:upper16:.LC1	@,
	bl	dprint_vfmw	@
	mov	r3, #1	@ D.33464,
	b	.L47	@
	.fnend
	.size	PostPro_GetDivx3MbGroup, .-PostPro_GetDivx3MbGroup
	.align	2
	.global	PostPro_GetAvsMbGroup
	.type	PostPro_GetAvsMbGroup, %function
PostPro_GetAvsMbGroup:
	.fnstart
.LFB1536:
	@ args = 0, pretend = 0, frame = 24
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	.pad #28
	sub	sp, sp, #28	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	ldr	r2, [r1, #8]	@ D.33387, <variable>.DecSliceNum
	sub	r3, r2, #1	@ tmp156, D.33387,
	cmp	r3, #199	@ tmp156,
	bhi	.L81	@,
	ldr	r7, [r0, #28]	@ <variable>.ImageHeight, <variable>.ImageHeight
	mov	r6, #0	@ tmp158,
	ldr	r5, [r0, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	mov	ip, r6	@ i, tmp158
	str	r6, [r0, #856]	@ tmp158, <variable>.FullRepair
	mvn	r8, #0	@ old_slice_end_mbn,
	ldr	r6, [r1, #8]	@ prephitmp.660, <variable>.DecSliceNum
	add	r9, r0, #872	@, pRepairParam,
	mul	r5, r5, r7	@ total_mbn, <variable>.ImageWidth, <variable>.ImageHeight
	str	r1, [fp, #-68]	@ pDecReport, %sfp
	add	r2, r1, r6, asl #2	@, tmp163, pDecReport, prephitmp.660,
	str	r9, [fp, #-64]	@, %sfp
	mov	r7, r0	@ pLocalRepairParam, pRepairParam
	mov	r9, ip	@ dectopfldmbs, i
	add	sl, r5, r8	@, total_mbn,
	mov	r4, r8	@ old_slice_start_mbn, old_slice_start_mbn
	str	sl, [fp, #-56]	@, %sfp
	mov	sl, r8	@ old_slice_start_mbn, old_slice_end_mbn
	mov	r3, r5, asr #1	@, total_mbn,
	str	r3, [fp, #-52]	@, %sfp
	uxth	r3, r5	@, total_mbn
	str	r3, [fp, #-48]	@, %sfp
	ldr	r3, [fp, #-52]	@, %sfp
	add	r3, r3, r8	@,,
	str	r3, [fp, #-60]	@, %sfp
	ldr	r3, [fp, #-48]	@, %sfp
	strh	r3, [r2, #14]	@ movhi	@, <variable>.SliceMbRange
	strh	r3, [r2, #12]	@ movhi	@, <variable>.SliceMbRange
	ldr	r3, [fp, #-68]	@ ivtmp.675, %sfp
	str	r0, [fp, #-68]	@ pRepairParam, %sfp
.L73:
	ldrh	r2, [r3, #12]	@ D.33398, <variable>.SliceMbRange
	ldrh	r0, [r3, #14]	@ curr_slice_end_mbn, <variable>.SliceMbRange
	cmp	r2, r5	@ D.33398, total_mbn
	cmple	r0, r5	@, curr_slice_end_mbn, total_mbn
	bgt	.L69	@,
	cmp	r2, r0	@ D.33398, curr_slice_end_mbn
	bgt	.L69	@,
	cmp	r2, r8	@ D.33398, old_slice_end_mbn
	movlt	r8, r4	@ old_slice_end_mbn, old_slice_start_mbn
	add	r8, r8, #1	@ tmp177, old_slice_end_mbn,
	cmp	r2, r8	@ D.33398, tmp177
	ble	.L71	@,
	ldr	sl, [r7, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r6, r4, r4, lsr #31	@, tmp186, old_slice_start_mbn, old_slice_start_mbn,
	uxth	r4, r9	@ D.33415, dectopfldmbs
	sub	r8, r2, #1	@ tmp195, D.33398,
	rsb	r6, r4, r6	@ tmp188, D.33415, tmp186
	rsb	r4, r4, r8	@ tmp197, D.33415, tmp195
	add	sl, r7, sl, asl #2	@, tmp180, pLocalRepairParam, <variable>.ValidGroupNum,
	strh	r6, [sl, #40]	@ movhi	@ tmp188, <variable>.StartMbn
	ldr	r6, [r7, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r8, r7, r6, asl #2	@, tmp193, pLocalRepairParam, <variable>.ValidGroupNum,
	strh	r4, [r8, #42]	@ movhi	@ tmp197, <variable>.EndMbn
	ldr	r6, [r7, #32]	@ <variable>.IsFrame, <variable>.IsFrame
	ldr	r8, [r7, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	cmp	r6, #0	@ <variable>.IsFrame,
	add	r4, r8, #1	@ tmp199, <variable>.ValidGroupNum,
	str	r4, [r7, #840]	@ tmp199, <variable>.ValidGroupNum
	bne	.L80	@,
	ldr	r4, [fp, #-60]	@, %sfp
	cmp	r2, r4	@ D.33398,
	bge	.L79	@,
.L80:
	ldr	r6, [r1, #8]	@ prephitmp.660, <variable>.DecSliceNum
.L71:
	sub	r8, r6, #1	@ temp.681, prephitmp.660,
	cmp	r8, ip	@ temp.681, i
	beq	.L82	@,
.L72:
	mov	r8, r0	@ old_slice_end_mbn, curr_slice_end_mbn
	mov	r4, r2	@ old_slice_start_mbn, D.33398
.L69:
	add	ip, ip, #1	@ i, i,
	add	r3, r3, #4	@ ivtmp.675, ivtmp.675,
	cmp	ip, r6	@ i, prephitmp.660
	bls	.L73	@,
	mov	r3, #0	@ D.33392,
.L66:
	mov	r0, r3	@, D.33392
	sub	sp, fp, #40
	ldmfd	sp, {r4, r5, r6, r7, r8, r9, sl, fp, sp, pc}
.L82:
	add	r4, r1, ip, asl #2	@, tmp203, pDecReport, i,
	ldr	sl, [fp, #-56]	@, %sfp
	ldrh	r8, [r4, #14]	@ D.33432, <variable>.SliceMbRange
	cmp	r8, sl	@ D.33432,
	bge	.L72	@,
	ldr	r0, [fp, #-68]	@ pRepairParam, %sfp
	ldr	r3, [fp, #-48]	@, %sfp
	ldr	ip, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	sub	r1, r3, #1	@ tmp216,,
	mov	r3, #0	@ D.33392,
	add	r2, r0, ip, asl #2	@, tmp208, pRepairParam, <variable>.ValidGroupNum,
	strh	r8, [r2, #40]	@ movhi	@ D.33432, <variable>.StartMbn
	ldr	ip, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r2, r0, ip, asl #2	@, tmp214, pRepairParam, <variable>.ValidGroupNum,
	strh	r1, [r2, #42]	@ movhi	@ tmp216, <variable>.EndMbn
	ldr	ip, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r1, ip, #1	@ tmp218, <variable>.ValidGroupNum,
	str	r1, [r0, #840]	@ tmp218, <variable>.ValidGroupNum
	b	.L66	@
.L79:
	ldr	r6, [r1, #8]	@ prephitmp.660, <variable>.DecSliceNum
	ldr	r7, [fp, #-64]	@ pLocalRepairParam, %sfp
	ldr	r9, [fp, #-52]	@ dectopfldmbs, %sfp
	b	.L71	@
.L81:
	mov	r0, #0	@,
	movw	r1, #:lower16:.LC1	@,
	movt	r1, #:upper16:.LC1	@,
	bl	dprint_vfmw	@
	mov	r3, #1	@ D.33392,
	b	.L66	@
	.fnend
	.size	PostPro_GetAvsMbGroup, .-PostPro_GetAvsMbGroup
	.align	2
	.global	PostPro_GetVp8MbGroup
	.type	PostPro_GetVp8MbGroup, %function
PostPro_GetVp8MbGroup:
	.fnstart
.LFB1535:
	@ args = 0, pretend = 0, frame = 8
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	.pad #12
	sub	sp, sp, #12	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	mov	r9, r1	@ pDecReport, pDecReport
	ldr	r1, [r1, #8]	@ <variable>.DecSliceNum, <variable>.DecSliceNum
	sub	r3, r1, #1	@ tmp152, <variable>.DecSliceNum,
	cmp	r3, #199	@ tmp152,
	bhi	.L97	@,
	ldr	r5, [r0, #28]	@ <variable>.ImageHeight, <variable>.ImageHeight
	mov	r6, #0	@ tmp155,
	ldr	r4, [r0, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	mvn	r7, #0	@ old_slice_end_mbn,
	str	r6, [r0, #840]	@ tmp155, <variable>.ValidGroupNum
	mov	r1, r6	@ i, tmp155
	str	r6, [r0, #856]	@ tmp155, <variable>.FullRepair
	mov	r3, r9	@ ivtmp.720, pDecReport
	mul	r4, r4, r5	@ total_mbn, <variable>.ImageWidth, <variable>.ImageHeight
	ldr	r5, [r9, #8]	@ prephitmp.705, <variable>.DecSliceNum
	mov	r6, r7	@ old_slice_start_mbn, old_slice_end_mbn
	add	ip, r9, r5, asl #2	@, tmp161, pDecReport, prephitmp.705,
	add	r8, r4, r7	@, total_mbn, tmp6
	str	r8, [fp, #-52]	@, %sfp
	uxth	r8, r4	@, total_mbn
	str	r8, [fp, #-48]	@, %sfp
	strh	r8, [ip, #14]	@ movhi	@, <variable>.SliceMbRange
	strh	r8, [ip, #12]	@ movhi	@, <variable>.SliceMbRange
	b	.L94	@
.L88:
	add	r1, r1, #1	@ i, i,
	cmp	r1, r5	@ i, prephitmp.705
	bhi	.L98	@,
.L94:
	ldrh	r2, [r3, #12]	@ D.33328, <variable>.SliceMbRange
	ldrh	ip, [r3, #14]	@ curr_slice_end_mbn, <variable>.SliceMbRange
	add	r3, r3, #4	@ ivtmp.720, ivtmp.720,
	cmp	r2, r4	@ D.33328, total_mbn
	cmple	ip, r4	@, curr_slice_end_mbn, total_mbn
	bgt	.L88	@,
	cmp	r2, ip	@ D.33328, curr_slice_end_mbn
	bgt	.L88	@,
	cmp	r2, r7	@ D.33328, old_slice_end_mbn
	add	sl, r6, r6, lsr #31	@, tmp218, old_slice_start_mbn, old_slice_start_mbn,
	sub	r8, r2, #1	@ tmp217, D.33328,
	movlt	r7, r6	@ old_slice_end_mbn, old_slice_start_mbn
	add	r7, r7, #1	@ tmp175, old_slice_end_mbn,
	cmp	r7, r2	@ tmp175, D.33328
	mov	r6, r2	@ old_slice_start_mbn, D.33328
	mov	r7, ip	@ old_slice_end_mbn, curr_slice_end_mbn
	beq	.L90	@,
	cmp	sl, r8	@ tmp218, tmp217
	bge	.L90	@,
	ldr	r2, [r0, #840]	@ D.33346, <variable>.ValidGroupNum
	cmp	r2, #199	@ D.33346,
	add	r2, r0, r2, asl #2	@, tmp181, pRepairParam, D.33346,
	bgt	.L99	@,
	strh	sl, [r2, #40]	@ movhi	@ tmp218, <variable>.StartMbn
	ldr	ip, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r2, r0, ip, asl #2	@, tmp192, pRepairParam, <variable>.ValidGroupNum,
	strh	r8, [r2, #42]	@ movhi	@ tmp217, <variable>.EndMbn
	ldr	r5, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	ip, r5, #1	@ tmp196, <variable>.ValidGroupNum,
	str	ip, [r0, #840]	@ tmp196, <variable>.ValidGroupNum
	ldr	r5, [r9, #8]	@ prephitmp.705, <variable>.DecSliceNum
.L90:
	sub	r2, r5, #1	@ temp.725, prephitmp.705,
	cmp	r2, r1	@ temp.725, i
	bne	.L88	@,
	add	r2, r9, r1, asl #2	@, tmp199, pDecReport, i,
	ldr	ip, [fp, #-52]	@, %sfp
	ldrh	r2, [r2, #14]	@ D.33360, <variable>.SliceMbRange
	cmp	r2, ip	@ D.33360,
	bge	.L88	@,
	ldr	r3, [r0, #840]	@ temp.726, <variable>.ValidGroupNum
	cmp	r3, #199	@ temp.726,
	bgt	.L100	@,
	add	ip, r0, r3, asl #2	@, tmp205, pRepairParam, temp.726,
	ldr	r3, [fp, #-48]	@, %sfp
	strh	r2, [ip, #40]	@ movhi	@ D.33360, <variable>.StartMbn
	sub	r1, r3, #1	@ tmp213,,
	ldr	ip, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	mov	r3, #0	@ D.33322,
	add	r2, r0, ip, asl #2	@, tmp211, pRepairParam, <variable>.ValidGroupNum,
	strh	r1, [r2, #42]	@ movhi	@ tmp213, <variable>.EndMbn
	ldr	ip, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r1, ip, #1	@ tmp215, <variable>.ValidGroupNum,
	str	r1, [r0, #840]	@ tmp215, <variable>.ValidGroupNum
	b	.L85	@
.L98:
	mov	r3, #0	@ D.33322,
.L85:
	mov	r0, r3	@, D.33322
	sub	sp, fp, #40
	ldmfd	sp, {r4, r5, r6, r7, r8, r9, sl, fp, sp, pc}
.L97:
	mov	r0, #0	@,
	movw	r1, #:lower16:.LC2	@,
	movt	r1, #:upper16:.LC2	@,
	bl	dprint_vfmw	@
	mov	r3, #1	@ D.33322,
	b	.L85	@
.L99:
	mov	r0, #22	@,
	movw	r1, #:lower16:.LC3	@,
	mov	r2, #1472	@,
	movt	r1, #:upper16:.LC3	@,
	bl	dprint_vfmw	@
	mov	r3, #1	@ D.33322,
	b	.L85	@
.L100:
	mov	r0, #22	@,
	movw	r1, #:lower16:.LC3	@,
	movw	r2, #1490	@,
	movt	r1, #:upper16:.LC3	@,
	bl	dprint_vfmw	@
	mov	r3, #1	@ D.33322,
	b	.L85	@
	.fnend
	.size	PostPro_GetVp8MbGroup, .-PostPro_GetVp8MbGroup
	.align	2
	.global	PostPro_GetVp6MbGroup
	.type	PostPro_GetVp6MbGroup, %function
PostPro_GetVp6MbGroup:
	.fnstart
.LFB1534:
	@ args = 0, pretend = 0, frame = 8
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	.pad #12
	sub	sp, sp, #12	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	mov	r9, r1	@ pDecReport, pDecReport
	ldr	r1, [r1, #8]	@ <variable>.DecSliceNum, <variable>.DecSliceNum
	sub	r3, r1, #1	@ tmp152, <variable>.DecSliceNum,
	cmp	r3, #199	@ tmp152,
	bhi	.L115	@,
	ldr	r5, [r0, #28]	@ <variable>.ImageHeight, <variable>.ImageHeight
	mov	r6, #0	@ tmp155,
	ldr	r4, [r0, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	mvn	r7, #0	@ old_slice_end_mbn,
	str	r6, [r0, #840]	@ tmp155, <variable>.ValidGroupNum
	mov	r1, r6	@ i, tmp155
	str	r6, [r0, #856]	@ tmp155, <variable>.FullRepair
	mov	r3, r9	@ ivtmp.767, pDecReport
	mul	r4, r4, r5	@ total_mbn, <variable>.ImageWidth, <variable>.ImageHeight
	ldr	r5, [r9, #8]	@ prephitmp.752, <variable>.DecSliceNum
	mov	r6, r7	@ old_slice_start_mbn, old_slice_end_mbn
	add	ip, r9, r5, asl #2	@, tmp161, pDecReport, prephitmp.752,
	add	r8, r4, r7	@, total_mbn, tmp6
	str	r8, [fp, #-52]	@, %sfp
	uxth	r8, r4	@, total_mbn
	str	r8, [fp, #-48]	@, %sfp
	strh	r8, [ip, #14]	@ movhi	@, <variable>.SliceMbRange
	strh	r8, [ip, #12]	@ movhi	@, <variable>.SliceMbRange
	b	.L112	@
.L106:
	add	r1, r1, #1	@ i, i,
	cmp	r1, r5	@ i, prephitmp.752
	bhi	.L116	@,
.L112:
	ldrh	r2, [r3, #12]	@ D.33260, <variable>.SliceMbRange
	ldrh	ip, [r3, #14]	@ curr_slice_end_mbn, <variable>.SliceMbRange
	add	r3, r3, #4	@ ivtmp.767, ivtmp.767,
	cmp	r2, r4	@ D.33260, total_mbn
	cmple	ip, r4	@, curr_slice_end_mbn, total_mbn
	bgt	.L106	@,
	cmp	r2, ip	@ D.33260, curr_slice_end_mbn
	bgt	.L106	@,
	cmp	r2, r7	@ D.33260, old_slice_end_mbn
	add	sl, r6, r6, lsr #31	@, tmp218, old_slice_start_mbn, old_slice_start_mbn,
	sub	r8, r2, #1	@ tmp217, D.33260,
	movlt	r7, r6	@ old_slice_end_mbn, old_slice_start_mbn
	add	r7, r7, #1	@ tmp175, old_slice_end_mbn,
	cmp	r7, r2	@ tmp175, D.33260
	mov	r6, r2	@ old_slice_start_mbn, D.33260
	mov	r7, ip	@ old_slice_end_mbn, curr_slice_end_mbn
	beq	.L108	@,
	cmp	sl, r8	@ tmp218, tmp217
	bge	.L108	@,
	ldr	r2, [r0, #840]	@ D.33278, <variable>.ValidGroupNum
	cmp	r2, #199	@ D.33278,
	add	r2, r0, r2, asl #2	@, tmp181, pRepairParam, D.33278,
	bgt	.L117	@,
	strh	sl, [r2, #40]	@ movhi	@ tmp218, <variable>.StartMbn
	ldr	ip, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r2, r0, ip, asl #2	@, tmp192, pRepairParam, <variable>.ValidGroupNum,
	strh	r8, [r2, #42]	@ movhi	@ tmp217, <variable>.EndMbn
	ldr	r5, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	ip, r5, #1	@ tmp196, <variable>.ValidGroupNum,
	str	ip, [r0, #840]	@ tmp196, <variable>.ValidGroupNum
	ldr	r5, [r9, #8]	@ prephitmp.752, <variable>.DecSliceNum
.L108:
	sub	r2, r5, #1	@ temp.772, prephitmp.752,
	cmp	r2, r1	@ temp.772, i
	bne	.L106	@,
	add	r2, r9, r1, asl #2	@, tmp199, pDecReport, i,
	ldr	ip, [fp, #-52]	@, %sfp
	ldrh	r2, [r2, #14]	@ D.33292, <variable>.SliceMbRange
	cmp	r2, ip	@ D.33292,
	bge	.L106	@,
	ldr	r3, [r0, #840]	@ temp.773, <variable>.ValidGroupNum
	cmp	r3, #199	@ temp.773,
	bgt	.L118	@,
	add	ip, r0, r3, asl #2	@, tmp205, pRepairParam, temp.773,
	ldr	r3, [fp, #-48]	@, %sfp
	strh	r2, [ip, #40]	@ movhi	@ D.33292, <variable>.StartMbn
	sub	r1, r3, #1	@ tmp213,,
	ldr	ip, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	mov	r3, #0	@ D.33254,
	add	r2, r0, ip, asl #2	@, tmp211, pRepairParam, <variable>.ValidGroupNum,
	strh	r1, [r2, #42]	@ movhi	@ tmp213, <variable>.EndMbn
	ldr	ip, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r1, ip, #1	@ tmp215, <variable>.ValidGroupNum,
	str	r1, [r0, #840]	@ tmp215, <variable>.ValidGroupNum
	b	.L103	@
.L116:
	mov	r3, #0	@ D.33254,
.L103:
	mov	r0, r3	@, D.33254
	sub	sp, fp, #40
	ldmfd	sp, {r4, r5, r6, r7, r8, r9, sl, fp, sp, pc}
.L115:
	mov	r0, #0	@,
	movw	r1, #:lower16:.LC2	@,
	movt	r1, #:upper16:.LC2	@,
	bl	dprint_vfmw	@
	mov	r3, #1	@ D.33254,
	b	.L103	@
.L117:
	mov	r0, #22	@,
	movw	r1, #:lower16:.LC3	@,
	movw	r2, #1393	@,
	movt	r1, #:upper16:.LC3	@,
	bl	dprint_vfmw	@
	mov	r3, #1	@ D.33254,
	b	.L103	@
.L118:
	mov	r0, #22	@,
	movw	r1, #:lower16:.LC3	@,
	movw	r2, #1411	@,
	movt	r1, #:upper16:.LC3	@,
	bl	dprint_vfmw	@
	mov	r3, #1	@ D.33254,
	b	.L103	@
	.fnend
	.size	PostPro_GetVp6MbGroup, .-PostPro_GetVp6MbGroup
	.align	2
	.global	PostPro_GetVc1MbGroup
	.type	PostPro_GetVc1MbGroup, %function
PostPro_GetVc1MbGroup:
	.fnstart
.LFB1533:
	@ args = 0, pretend = 0, frame = 8
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	.pad #12
	sub	sp, sp, #12	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	mov	r9, r1	@ pDecReport, pDecReport
	ldr	r1, [r1, #8]	@ <variable>.DecSliceNum, <variable>.DecSliceNum
	sub	r3, r1, #1	@ tmp152, <variable>.DecSliceNum,
	cmp	r3, #199	@ tmp152,
	bhi	.L133	@,
	ldr	r5, [r0, #28]	@ <variable>.ImageHeight, <variable>.ImageHeight
	mov	r6, #0	@ tmp155,
	ldr	r4, [r0, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	mvn	r7, #0	@ old_slice_end_mbn,
	str	r6, [r0, #840]	@ tmp155, <variable>.ValidGroupNum
	mov	r1, r6	@ i, tmp155
	str	r6, [r0, #856]	@ tmp155, <variable>.FullRepair
	mov	r3, r9	@ ivtmp.814, pDecReport
	mul	r4, r4, r5	@ total_mbn, <variable>.ImageWidth, <variable>.ImageHeight
	ldr	r5, [r9, #8]	@ prephitmp.799, <variable>.DecSliceNum
	mov	r6, r7	@ old_slice_start_mbn, old_slice_end_mbn
	add	ip, r9, r5, asl #2	@, tmp161, pDecReport, prephitmp.799,
	add	r8, r4, r7	@, total_mbn, tmp6
	str	r8, [fp, #-52]	@, %sfp
	uxth	r8, r4	@, total_mbn
	str	r8, [fp, #-48]	@, %sfp
	strh	r8, [ip, #14]	@ movhi	@, <variable>.SliceMbRange
	strh	r8, [ip, #12]	@ movhi	@, <variable>.SliceMbRange
	b	.L130	@
.L124:
	add	r1, r1, #1	@ i, i,
	cmp	r1, r5	@ i, prephitmp.799
	bhi	.L134	@,
.L130:
	ldrh	r2, [r3, #12]	@ D.33192, <variable>.SliceMbRange
	ldrh	ip, [r3, #14]	@ curr_slice_end_mbn, <variable>.SliceMbRange
	add	r3, r3, #4	@ ivtmp.814, ivtmp.814,
	cmp	r2, r4	@ D.33192, total_mbn
	cmple	ip, r4	@, curr_slice_end_mbn, total_mbn
	bgt	.L124	@,
	cmp	r2, ip	@ D.33192, curr_slice_end_mbn
	bgt	.L124	@,
	cmp	r2, r7	@ D.33192, old_slice_end_mbn
	add	sl, r6, r6, lsr #31	@, tmp218, old_slice_start_mbn, old_slice_start_mbn,
	sub	r8, r2, #1	@ tmp217, D.33192,
	movlt	r7, r6	@ old_slice_end_mbn, old_slice_start_mbn
	add	r7, r7, #1	@ tmp175, old_slice_end_mbn,
	cmp	r7, r2	@ tmp175, D.33192
	mov	r6, r2	@ old_slice_start_mbn, D.33192
	mov	r7, ip	@ old_slice_end_mbn, curr_slice_end_mbn
	beq	.L126	@,
	cmp	sl, r8	@ tmp218, tmp217
	bge	.L126	@,
	ldr	r2, [r0, #840]	@ D.33210, <variable>.ValidGroupNum
	cmp	r2, #199	@ D.33210,
	add	r2, r0, r2, asl #2	@, tmp181, pRepairParam, D.33210,
	bgt	.L135	@,
	strh	sl, [r2, #40]	@ movhi	@ tmp218, <variable>.StartMbn
	ldr	ip, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r2, r0, ip, asl #2	@, tmp192, pRepairParam, <variable>.ValidGroupNum,
	strh	r8, [r2, #42]	@ movhi	@ tmp217, <variable>.EndMbn
	ldr	r5, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	ip, r5, #1	@ tmp196, <variable>.ValidGroupNum,
	str	ip, [r0, #840]	@ tmp196, <variable>.ValidGroupNum
	ldr	r5, [r9, #8]	@ prephitmp.799, <variable>.DecSliceNum
.L126:
	sub	r2, r5, #1	@ temp.819, prephitmp.799,
	cmp	r2, r1	@ temp.819, i
	bne	.L124	@,
	add	r2, r9, r1, asl #2	@, tmp199, pDecReport, i,
	ldr	ip, [fp, #-52]	@, %sfp
	ldrh	r2, [r2, #14]	@ D.33224, <variable>.SliceMbRange
	cmp	r2, ip	@ D.33224,
	bge	.L124	@,
	ldr	r3, [r0, #840]	@ temp.820, <variable>.ValidGroupNum
	cmp	r3, #199	@ temp.820,
	bgt	.L136	@,
	add	ip, r0, r3, asl #2	@, tmp205, pRepairParam, temp.820,
	ldr	r3, [fp, #-48]	@, %sfp
	strh	r2, [ip, #40]	@ movhi	@ D.33224, <variable>.StartMbn
	sub	r1, r3, #1	@ tmp213,,
	ldr	ip, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	mov	r3, #0	@ D.33186,
	add	r2, r0, ip, asl #2	@, tmp211, pRepairParam, <variable>.ValidGroupNum,
	strh	r1, [r2, #42]	@ movhi	@ tmp213, <variable>.EndMbn
	ldr	ip, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r1, ip, #1	@ tmp215, <variable>.ValidGroupNum,
	str	r1, [r0, #840]	@ tmp215, <variable>.ValidGroupNum
	b	.L121	@
.L134:
	mov	r3, #0	@ D.33186,
.L121:
	mov	r0, r3	@, D.33186
	sub	sp, fp, #40
	ldmfd	sp, {r4, r5, r6, r7, r8, r9, sl, fp, sp, pc}
.L133:
	mov	r0, #0	@,
	movw	r1, #:lower16:.LC2	@,
	movt	r1, #:upper16:.LC2	@,
	bl	dprint_vfmw	@
	mov	r3, #1	@ D.33186,
	b	.L121	@
.L135:
	mov	r0, #22	@,
	movw	r1, #:lower16:.LC3	@,
	mov	r2, #1312	@,
	movt	r1, #:upper16:.LC3	@,
	bl	dprint_vfmw	@
	mov	r3, #1	@ D.33186,
	b	.L121	@
.L136:
	mov	r0, #22	@,
	movw	r1, #:lower16:.LC3	@,
	movw	r2, #1331	@,
	movt	r1, #:upper16:.LC3	@,
	bl	dprint_vfmw	@
	mov	r3, #1	@ D.33186,
	b	.L121	@
	.fnend
	.size	PostPro_GetVc1MbGroup, .-PostPro_GetVc1MbGroup
	.align	2
	.global	PostPro_GetMp24MbGroup
	.type	PostPro_GetMp24MbGroup, %function
PostPro_GetMp24MbGroup:
	.fnstart
.LFB1532:
	@ args = 0, pretend = 0, frame = 8
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	.pad #12
	sub	sp, sp, #12	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	ldr	r2, [r1, #8]	@ D.33096, <variable>.DecSliceNum
	sub	r3, r2, #1	@ tmp155, D.33096,
	cmp	r3, #199	@ tmp155,
	bhi	.L153	@,
	ldr	r6, [r0, #28]	@ <variable>.ImageHeight, <variable>.ImageHeight
	mov	r4, #0	@ tmp157,
	ldr	r5, [r0, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	str	r4, [r0, #856]	@ tmp157, <variable>.FullRepair
	str	r4, [r0, #840]	@ tmp157, <variable>.ValidGroupNum
	mul	r5, r5, r6	@ total_mbn, <variable>.ImageWidth, <variable>.ImageHeight
	ldr	r6, [r1, #8]	@ prephitmp.854, <variable>.DecSliceNum
	cmp	r6, r4	@ prephitmp.854,
	add	r2, r1, r6, asl #2	@, tmp163, pDecReport, prephitmp.854,
	uxth	r9, r5	@ D.33104, total_mbn
	strh	r9, [r2, #14]	@ movhi	@ D.33104, <variable>.SliceMbRange
	strh	r9, [r2, #12]	@ movhi	@ D.33104, <variable>.SliceMbRange
	bne	.L154	@,
.L140:
	mvn	sl, #0	@ old_slice_end_mbn,
	mov	ip, #0	@ i,
	add	r3, r5, sl	@, total_mbn,
	mov	r7, sl	@ old_slice_start_mbn, old_slice_end_mbn
	str	r3, [fp, #-48]	@, %sfp
	mov	r3, r1	@ ivtmp.871, pDecReport
	b	.L150	@
.L148:
	mov	sl, r4	@ old_slice_end_mbn, curr_slice_end_mbn
	mov	r7, r2	@ old_slice_start_mbn, D.33115
.L143:
	add	ip, ip, #1	@ i, i,
	add	r3, r3, #4	@ ivtmp.871, ivtmp.871,
	cmp	ip, r6	@ i, prephitmp.854
	bhi	.L155	@,
.L150:
	ldrh	r2, [r3, #12]	@ D.33115, <variable>.SliceMbRange
	ldrh	r4, [r3, #14]	@ curr_slice_end_mbn, <variable>.SliceMbRange
	cmp	r2, r5	@ D.33115, total_mbn
	cmple	r4, r5	@, curr_slice_end_mbn, total_mbn
	bgt	.L143	@,
	cmp	r2, r4	@ D.33115, curr_slice_end_mbn
	movle	r8, #0	@, tmp191
	movgt	r8, #1	@, tmp191
	cmp	r2, r7	@ D.33115, old_slice_start_mbn
	orrlt	r8, r8, #1	@,, tmp194, tmp191
	cmp	r8, #0	@ tmp194,
	bne	.L143	@,
	cmp	r2, sl	@ D.33115, old_slice_end_mbn
	movlt	sl, r7	@ old_slice_end_mbn, old_slice_start_mbn
	add	r8, sl, #1	@ tmp195, old_slice_end_mbn,
	cmp	r8, r2	@ tmp195, D.33115
	beq	.L145	@,
	add	r7, r7, r7, lsr #31	@, tmp247, old_slice_start_mbn, old_slice_start_mbn,
	sub	r8, r2, #1	@ tmp246, D.33115,
	cmp	r7, r8	@ tmp247, tmp246
	bge	.L145	@,
	ldr	r6, [r0, #840]	@ D.33136, <variable>.ValidGroupNum
	cmp	r6, #199	@ D.33136,
	bgt	.L156	@,
	add	r6, r0, r6, asl #2	@, tmp201, pRepairParam, D.33136,
	sub	sl, sl, #100	@ tmp248, old_slice_end_mbn,
	strh	r7, [r6, #40]	@ movhi	@ tmp247, <variable>.StartMbn
	ldr	r7, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r6, r0, r7, asl #2	@, tmp212, pRepairParam, <variable>.ValidGroupNum,
	strh	r8, [r6, #42]	@ movhi	@ tmp246, <variable>.EndMbn
	ldr	r6, [r0, #840]	@ prephitmp.856, <variable>.ValidGroupNum
	add	r8, r6, #10	@ tmp216, prephitmp.856,
	mov	r7, r8, asl #2	@ tmp217, tmp216,
	ldrsh	r8, [r7, r0]	@ <variable>.StartMbn, <variable>.StartMbn
	cmp	sl, r8	@ tmp248, <variable>.StartMbn
	strgth	sl, [r7, r0]	@ movhi	@ tmp248, <variable>.StartMbn
	ldrgt	r6, [r0, #840]	@ prephitmp.856, <variable>.ValidGroupNum
	add	r6, r6, #1	@ tmp225, prephitmp.856,
	str	r6, [r0, #840]	@ tmp225, <variable>.ValidGroupNum
	ldr	r6, [r1, #8]	@ prephitmp.854, <variable>.DecSliceNum
.L145:
	sub	r7, r6, #1	@ temp.876, prephitmp.854,
	cmp	r7, ip	@ temp.876, i
	bne	.L148	@,
	add	r8, r1, ip, asl #2	@, tmp228, pDecReport, i,
	ldrh	r7, [r8, #14]	@ temp.877, <variable>.SliceMbRange
	ldr	r8, [fp, #-48]	@, %sfp
	cmp	r7, r8	@ temp.877,
	bge	.L148	@,
	ldr	r3, [r0, #840]	@ temp.879, <variable>.ValidGroupNum
	cmp	r3, #199	@ temp.879,
	bgt	.L157	@,
	add	r2, r0, r3, asl #2	@, tmp234, pRepairParam, temp.879,
	sub	r9, r9, #1	@ tmp242, D.33104,
	mov	r3, #0	@ D.33101,
	strh	r7, [r2, #40]	@ movhi	@ temp.877, <variable>.StartMbn
	ldr	r1, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	ip, r0, r1, asl #2	@, tmp240, pRepairParam, <variable>.ValidGroupNum,
	strh	r9, [ip, #42]	@ movhi	@ tmp242, <variable>.EndMbn
	ldr	r2, [r0, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r1, r2, #1	@ tmp244, <variable>.ValidGroupNum,
	str	r1, [r0, #840]	@ tmp244, <variable>.ValidGroupNum
	b	.L139	@
.L155:
	mov	r3, #0	@ D.33101,
.L139:
	mov	r0, r3	@, D.33101
	sub	sp, fp, #40
	ldmfd	sp, {r4, r5, r6, r7, r8, r9, sl, fp, sp, pc}
.L154:
	add	sl, r2, #6	@ tmp173, tmp172,
	sub	r7, r5, #10	@ tmp175, total_mbn,
	ldrh	ip, [sl, #4]	@ tmp174, <variable>.SliceMbRange
	cmp	ip, r7	@ tmp174, tmp175
	subge	r7, r9, #1	@ tmp180, D.33104,
	strgeh	r7, [sl, #4]	@ movhi	@ tmp180, <variable>.SliceMbRange
	b	.L140	@
.L153:
	mov	r0, #0	@,
	movw	r1, #:lower16:.LC1	@,
	movt	r1, #:upper16:.LC1	@,
	bl	dprint_vfmw	@
	mov	r3, #1	@ D.33101,
	b	.L139	@
.L156:
	mov	r0, #22	@,
	movw	r1, #:lower16:.LC3	@,
	movw	r2, #1222	@,
	movt	r1, #:upper16:.LC3	@,
	bl	dprint_vfmw	@
	mov	r3, #1	@ D.33101,
	b	.L139	@
.L157:
	mov	r0, #22	@,
	movw	r1, #:lower16:.LC3	@,
	movw	r2, #1251	@,
	movt	r1, #:upper16:.LC3	@,
	bl	dprint_vfmw	@
	mov	r3, #1	@ D.33101,
	b	.L139	@
	.fnend
	.size	PostPro_GetMp24MbGroup, .-PostPro_GetMp24MbGroup
	.global	__aeabi_uidivmod
	.global	__aeabi_uidiv
	.align	2
	.global	PostPro_GetH264MbGroup
	.type	PostPro_GetH264MbGroup, %function
PostPro_GetH264MbGroup:
	.fnstart
.LFB1531:
	@ args = 0, pretend = 0, frame = 832
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	.pad #836
	sub	sp, sp, #836	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	mov	r4, r0	@ pRepairParam, pRepairParam
	ldr	r0, [r1, #8]	@, <variable>.DecSliceNum
	mov	r5, r1	@ pDecReport, pDecReport
	sub	r3, r0, #1	@ tmp194,,
	cmp	r3, #199	@ tmp194,
	str	r0, [fp, #-856]	@, %sfp
	bhi	.L203	@,
	ldr	sl, [r4, #24]	@ D.32963, <variable>.ImageWidth
	cmp	r2, #0	@ IsMbaff,
	ldr	r6, [r4, #28]	@ <variable>.ImageHeight, <variable>.ImageHeight
	mul	r6, r6, sl	@ total_mbn, <variable>.ImageHeight, D.32963
	uxtheq	r9, r6	@ prephitmp.914, total_mbn
	bne	.L204	@,
.L162:
	mov	r1, #0	@ tmp392,
	str	r1, [r4, #840]	@ tmp392, <variable>.ValidGroupNum
	str	r1, [r4, #856]	@ tmp392, <variable>.FullRepair
	mvn	r8, #0	@ old_slice_end_mbn,
	ldr	ip, [r5, #8]	@ prephitmp.909, <variable>.DecSliceNum
	add	r7, r6, r8	@, total_mbn,
	mov	r3, r5	@ ivtmp.934, pDecReport
	str	r7, [fp, #-848]	@, %sfp
	mov	r7, r8	@ old_slice_start_mbn, old_slice_end_mbn
	add	r0, r5, ip, asl #2	@, tmp396, pDecReport, prephitmp.909,
	strh	r9, [r0, #14]	@ movhi	@ prephitmp.914, <variable>.SliceMbRange
	strh	r9, [r0, #12]	@ movhi	@ prephitmp.914, <variable>.SliceMbRange
	b	.L182	@
.L180:
	mov	r8, r0	@ old_slice_end_mbn, curr_slice_end_mbn
	mov	r7, r2	@ old_slice_start_mbn, temp.1010
.L175:
	add	r1, r1, #1	@ i.959, i.959,
	add	r3, r3, #4	@ ivtmp.934, ivtmp.934,
	cmp	ip, r1	@ prephitmp.909, i.959
	bcc	.L205	@,
.L182:
	ldrh	r2, [r3, #12]	@ temp.1010, <variable>.SliceMbRange
	ldrh	r0, [r3, #14]	@ curr_slice_end_mbn, <variable>.SliceMbRange
	cmp	r2, r6	@ temp.1010, total_mbn
	cmple	r0, r6	@, curr_slice_end_mbn, total_mbn
	bgt	.L175	@,
	cmp	r2, r0	@ temp.1010, curr_slice_end_mbn
	bgt	.L175	@,
	cmp	r2, r8	@ temp.1010, old_slice_end_mbn
	movlt	r8, r7	@ old_slice_end_mbn, old_slice_start_mbn
	add	sl, r8, #1	@ tmp410, old_slice_end_mbn,
	cmp	r2, sl	@ temp.1010, tmp410
	ble	.L177	@,
	ldr	sl, [r4, #840]	@ D.33049, <variable>.ValidGroupNum
	cmp	sl, #199	@ D.33049,
	bgt	.L206	@,
	add	sl, r4, sl, asl #2	@, tmp413, pRepairParam, D.33049,
	add	r7, r7, r7, lsr #31	@, tmp419, old_slice_start_mbn, old_slice_start_mbn,
	sub	ip, r2, #1	@ tmp426, temp.1010,
	sub	r8, r8, #100	@ tmp471, old_slice_end_mbn,
	strh	r7, [sl, #40]	@ movhi	@ tmp419, <variable>.StartMbn
	ldr	sl, [r4, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r7, r4, sl, asl #2	@, tmp424, pRepairParam, <variable>.ValidGroupNum,
	strh	ip, [r7, #42]	@ movhi	@ tmp426, <variable>.EndMbn
	ldr	ip, [r4, #840]	@ prephitmp.911, <variable>.ValidGroupNum
	add	sl, ip, #10	@ tmp428, prephitmp.911,
	mov	r7, sl, asl #2	@ tmp429, tmp428,
	ldrsh	sl, [r7, r4]	@ <variable>.StartMbn, <variable>.StartMbn
	cmp	r8, sl	@ tmp471, <variable>.StartMbn
	strgth	r8, [r7, r4]	@ movhi	@ tmp471, <variable>.StartMbn
	ldrgt	ip, [r4, #840]	@ prephitmp.911, <variable>.ValidGroupNum
	add	r8, ip, #1	@ tmp437, prephitmp.911,
	str	r8, [r4, #840]	@ tmp437, <variable>.ValidGroupNum
	ldr	ip, [r5, #8]	@ prephitmp.909, <variable>.DecSliceNum
.L177:
	sub	r8, ip, #1	@ temp.1013, prephitmp.909,
	cmp	r8, r1	@ temp.1013, i.959
	bne	.L180	@,
	add	r7, r5, r1, asl #2	@, tmp440, pDecReport, i.959,
	ldr	r8, [fp, #-848]	@, %sfp
	ldrh	r7, [r7, #14]	@ D.33071, <variable>.SliceMbRange
	cmp	r7, r8	@ D.33071,
	bge	.L180	@,
	ldr	r3, [r4, #840]	@ temp.1014, <variable>.ValidGroupNum
	cmp	r3, #199	@ temp.1014,
	bgt	.L207	@,
	add	r1, r4, r3, asl #2	@, tmp446, pRepairParam, temp.1014,
	sub	r9, r9, #1	@ tmp454, prephitmp.914,
	mov	r0, #0	@ D.32962,
	strh	r7, [r1, #40]	@ movhi	@ D.33071, <variable>.StartMbn
	ldr	ip, [r4, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r2, r4, ip, asl #2	@, tmp452, pRepairParam, <variable>.ValidGroupNum,
	strh	r9, [r2, #42]	@ movhi	@ tmp454, <variable>.EndMbn
	ldr	r3, [r4, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r1, r3, #1	@ tmp456, <variable>.ValidGroupNum,
	str	r1, [r4, #840]	@ tmp456, <variable>.ValidGroupNum
	b	.L160	@
.L205:
	mov	r0, #0	@ D.32962,
.L160:
	sub	sp, fp, #40
	ldmfd	sp, {r4, r5, r6, r7, r8, r9, sl, fp, sp, pc}
.L204:
	ldrh	r8, [r5, #12]	@, <variable>.SliceMbRange
	sub	r2, fp, #844	@ ivtmp.953,,
	ldr	lr, [fp, #-856]	@, %sfp
	add	r3, r2, #4	@ ivtmp.953, ivtmp.953,
	mov	sl, sl, asl #1	@ DoubleImageWidth, D.32963,
	strh	r8, [r2, #0]	@ movhi	@, SliceMbRange_Tmp
	add	r0, r2, lr, asl #2	@, D.34132, ivtmp.953,,
	ldrh	ip, [r5, #14]	@, <variable>.SliceMbRange
	rsb	r9, r2, r0	@ tmp475, ivtmp.953, D.34132
	cmp	r3, r0	@ ivtmp.953, D.34132
	sub	r1, r9, #4	@ tmp476, tmp475,
	strh	ip, [r2, #2]	@ movhi	@, SliceMbRange_Tmp
	ubfx	r1, r1, #2, #1	@ tmp477, tmp476,,
	add	r2, r5, #4	@ ivtmp.952, pDecReport,
	beq	.L193	@,
	cmp	r1, #0	@ tmp477,
	beq	.L163	@,
	ldrh	r1, [r2, #12]	@, <variable>.SliceMbRange
	strh	r1, [r3, #0]	@ movhi	@, SliceMbRange_Tmp
	ldrh	ip, [r2, #14]	@, <variable>.SliceMbRange
	add	r2, r2, #4	@ ivtmp.952, ivtmp.952,
	strh	ip, [r3, #2]	@ movhi	@, SliceMbRange_Tmp
	add	r3, r3, #4	@ ivtmp.953, ivtmp.953,
	cmp	r3, r0	@ ivtmp.953, D.34132
	beq	.L193	@,
.L163:
	ldrh	lr, [r2, #12]	@, <variable>.SliceMbRange
	add	r1, r2, #4	@ tmp479, ivtmp.952,
	strh	lr, [r3, #0]	@ movhi	@, SliceMbRange_Tmp
	ldrh	r9, [r2, #14]	@, <variable>.SliceMbRange
	add	r2, r3, #4	@ tmp478, ivtmp.953,
	strh	r9, [r3, #2]	@ movhi	@, SliceMbRange_Tmp
	ldrh	r8, [r1, #12]	@, <variable>.SliceMbRange
	strh	r8, [r3, #4]	@ movhi	@, SliceMbRange_Tmp
	add	r3, r2, #4	@ ivtmp.953, tmp478,
	ldrh	ip, [r1, #14]	@, <variable>.SliceMbRange
	cmp	r3, r0	@ ivtmp.953, D.34132
	strh	ip, [r2, #2]	@ movhi	@, SliceMbRange_Tmp
	add	r2, r1, #4	@ ivtmp.952, tmp479,
	bne	.L163	@,
.L193:
	sub	r9, fp, #44	@,,
	movw	r8, #:lower16:-800	@ tmp205,
	movw	r3, #:lower16:-798	@ tmp209,
	movt	r8, #:upper16:-800	@ tmp205,
	movt	r3, #:upper16:-798	@ tmp209,
	cmp	sl, #0	@ DoubleImageWidth,
	ldrh	lr, [r9, r8]	@ SliceMbRange_Tmp, SliceMbRange_Tmp
	mov	r2, r9	@,
	ldrh	ip, [r9, r3]	@ SliceMbRange_Tmp, SliceMbRange_Tmp
	movw	r0, #:lower16:65534	@ prephitmp.916,
	movt	r0, #:upper16:65534	@ prephitmp.916,
	moveq	r7, sl	@ j, DoubleImageWidth
	and	r0, lr, r0	@ prephitmp.916, SliceMbRange_Tmp, prephitmp.916
	strh	r0, [r9, r8]	@ movhi	@ prephitmp.916, SliceMbRange_Tmp
	orr	r9, ip, #1	@ D.32974, SliceMbRange_Tmp,
	strh	r9, [r2, r3]	@ movhi	@ D.32974, SliceMbRange_Tmp
	beq	.L165	@,
	mov	r3, #0	@,
	uxth	r7, sl	@, DoubleImageWidth
	sub	r1, sl, #2	@, DoubleImageWidth,
	str	r7, [fp, #-864]	@, %sfp
	str	r6, [fp, #-868]	@ total_mbn, %sfp
	sub	r8, fp, #840	@ ivtmp.940,,
	str	r3, [fp, #-848]	@, %sfp
	mov	r7, r3	@ j,
	str	r1, [fp, #-860]	@, %sfp
	mov	r6, r0	@ prephitmp.916, prephitmp.916
	b	.L184	@
.L209:
	mov	r0, r6	@, prephitmp.916
	mov	r1, sl	@, DoubleImageWidth
	str	r3, [fp, #-872]	@,
	bl	__aeabi_uidiv	@
	mov	r1, sl	@, DoubleImageWidth
	mov	r6, r0	@ tmp229,
	mov	r0, r9	@, D.32974
	bl	__aeabi_uidiv	@
	ldr	r2, [fp, #-852]	@, %sfp
	ldr	r9, [fp, #-872]	@,
	mov	r1, r2, lsr #1	@ mbsurplus0,,
	mov	r3, r9, lsr #1	@ mbsurplus1, tmp225,
	cmp	r0, r6	@ tmp232, tmp229
	beq	.L168	@,
	ldr	r2, [fp, #-864]	@, %sfp
	add	r9, r5, r7, asl #2	@, tmp240, pDecReport, j,
	mov	lr, r9	@ tmp244, tmp240
	mul	r6, r6, r2	@ tmp234, tmp229,
	add	r2, r7, #1	@ j.961, j,
	cmp	r2, #199	@ j.961,
	uxth	r6, r6	@ D.32990, tmp234
	add	r1, r6, r1	@ tmp236, D.32990, mbsurplus0
	uxth	r1, r1	@ D.32992, tmp236
	strh	r1, [r9, #12]	@ movhi	@ D.32992, <variable>.SliceMbRange
	ldr	ip, [r4, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	sub	r9, ip, #1	@ tmp248, <variable>.ImageWidth,
	add	ip, r6, r9	@ tmp250, D.32990, tmp248
	strh	ip, [lr, #14]	@ movhi	@ tmp250, <variable>.SliceMbRange
	bhi	.L199	@,
	ldr	lr, [fp, #-864]	@, %sfp
	add	ip, r2, #1	@ j.964, j.961,
	ldr	r6, [r4, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	add	r9, r5, r2, asl #2	@, tmp263, pDecReport, j.961,
	cmp	ip, #200	@ j.964,
	uxth	r3, r3	@ D.33001, mbsurplus1
	mul	r0, r0, lr	@ tmp260, tmp232,
	add	lr, r5, r7, asl #2	@, tmp254, pDecReport, j,
	add	r1, r1, r6	@ tmp258, D.32992, <variable>.ImageWidth
	strh	r1, [lr, #16]	@ movhi	@ tmp258, <variable>.SliceMbRange
	uxth	r0, r0	@ D.33000, tmp260
	add	r7, r3, r0	@ tmp265, D.33001, D.33000
	strh	r7, [r9, #14]	@ movhi	@ tmp265, <variable>.SliceMbRange
	beq	.L199	@,
	ldr	r6, [r4, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	add	r7, ip, #1	@ j, j.964,
	cmp	r7, #200	@ j,
	add	ip, r5, ip, asl #2	@, tmp276, pDecReport, j.964,
	add	r1, r0, r6	@ tmp268, D.33000, <variable>.ImageWidth
	uxth	r9, r1	@ D.33005, tmp268
	strh	r9, [lr, #20]	@ movhi	@ D.33005, <variable>.SliceMbRange
	add	r3, r9, r3	@ tmp278, D.33005, D.33001
	strh	r3, [ip, #14]	@ movhi	@ tmp278, <variable>.SliceMbRange
	beq	.L199	@,
.L170:
	ldr	r6, [fp, #-848]	@, %sfp
	add	r8, r8, #4	@ ivtmp.940, ivtmp.940,
	ldr	lr, [fp, #-856]	@, %sfp
	add	r3, r6, #1	@,,
	str	r3, [fp, #-848]	@, %sfp
	cmp	lr, r3	@,
	bls	.L208	@,
.L172:
	ldrh	r6, [r8, #-4]	@ tmp463, SliceMbRange_Tmp
	ldrh	r9, [r8, #-2]	@ tmp466, SliceMbRange_Tmp
	bic	r6, r6, #1	@ tmp464, tmp463,
	strh	r6, [r8, #-4]	@ movhi	@ tmp464, SliceMbRange_Tmp
	orr	r9, r9, #1	@ D.32974, tmp466,
	strh	r9, [r8, #-2]	@ movhi	@ D.32974, SliceMbRange_Tmp
.L184:
	mov	r0, r6	@, prephitmp.916
	mov	r1, sl	@, DoubleImageWidth
	bl	__aeabi_uidivmod	@
	cmp	r1, #1	@,
	str	r1, [fp, #-852]	@, %sfp
	bls	.L166	@,
	mov	r0, r9	@, D.32974
	mov	r1, sl	@, DoubleImageWidth
	bl	__aeabi_uidivmod	@
	ldr	ip, [fp, #-860]	@, %sfp
	cmp	ip, r1	@, tmp225
	mov	r3, r1	@ tmp225,
	bhi	.L209	@,
	mov	r0, r6	@, prephitmp.916
	mov	r1, sl	@, DoubleImageWidth
	bl	__aeabi_uidiv	@
	add	r1, r5, r7, asl #2	@, tmp323, pDecReport, j,
	add	r3, r7, #1	@ j.990, j,
	ldr	r7, [fp, #-852]	@, %sfp
	mov	r2, r1	@ tmp327, tmp323
	cmp	r3, #199	@ j.990,
	mul	r0, sl, r0	@ tmp316, DoubleImageWidth,
	uxth	r6, r0	@ temp.983, tmp316
	add	ip, r6, r7, lsr #1	@, tmp319, temp.983,,
	uxth	ip, ip	@ temp.985, tmp319
	strh	ip, [r1, #12]	@ movhi	@ temp.985, <variable>.SliceMbRange
	ldr	r1, [r4, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	sub	lr, r1, #1	@ tmp331, <variable>.ImageWidth,
	add	r7, r6, lr	@ tmp333, temp.983, tmp331
	strh	r7, [r2, #14]	@ movhi	@ tmp333, <variable>.SliceMbRange
	bhi	.L199	@,
	add	r7, r3, #1	@ j, j.990,
	ldr	r6, [r4, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	add	r3, r5, r3, asl #2	@, tmp344, pDecReport, j.990,
	cmp	r7, #200	@ j,
	add	lr, ip, r6	@ tmp341, temp.985, <variable>.ImageWidth
	strh	lr, [r2, #16]	@ movhi	@ tmp341, <variable>.SliceMbRange
	strh	r9, [r3, #14]	@ movhi	@ D.32974, <variable>.SliceMbRange
	bne	.L170	@,
.L199:
	ldr	r6, [fp, #-868]	@ total_mbn, %sfp
	mov	r8, #0	@ movhi	@,
	mov	r0, #1	@ tmp458,
	strh	r8, [r5, #12]	@ movhi	@, <variable>.SliceMbRange
	str	r0, [r5, #8]	@ tmp458, <variable>.DecSliceNum
	uxth	r9, r6	@ prephitmp.914, total_mbn
	sub	lr, r9, #1	@ tmp461, prephitmp.914,
	strh	lr, [r5, #14]	@ movhi	@ tmp461, <variable>.SliceMbRange
.L183:
	mov	r0, r5	@, pDecReport
	bl	PostPro_BubbleSort	@
	b	.L162	@
.L166:
	mov	r0, r9	@, D.32974
	mov	r1, sl	@, DoubleImageWidth
	bl	__aeabi_uidivmod	@
	mov	r2, r1	@ tmp350,
	ldr	r1, [fp, #-860]	@, %sfp
	cmp	r1, r2	@, tmp350
	bls	.L171	@,
	add	r3, r5, r7, asl #2	@, tmp355, pDecReport, j,
	mov	r0, r9	@, D.32974
	mov	r1, sl	@, DoubleImageWidth
	strh	r6, [r3, #12]	@ movhi	@ prephitmp.916, <variable>.SliceMbRange
	str	r2, [fp, #-872]	@,
	bl	__aeabi_uidiv	@
	ldr	r2, [fp, #-872]	@,
	add	r3, r7, #1	@ j.1004, j,
	add	r1, r5, r7, asl #2	@, tmp367, pDecReport, j,
	cmp	r3, #199	@ j.1004,
	ubfx	r2, r2, #1, #16	@ temp.1002, tmp350,,
	mul	ip, sl, r0	@ tmp363, DoubleImageWidth,
	uxth	r0, ip	@ temp.1001, tmp363
	add	r9, r2, r0	@ tmp369, temp.1002, temp.1001
	strh	r9, [r1, #14]	@ movhi	@ tmp369, <variable>.SliceMbRange
	bhi	.L199	@,
	ldr	ip, [r4, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	add	r7, r3, #1	@ j, j.1004,
	add	r6, r5, r3, asl #2	@, tmp380, pDecReport, j.1004,
	cmp	r7, #200	@ j,
	add	r9, r0, ip	@ tmp372, temp.1001, <variable>.ImageWidth
	uxth	r0, r9	@ temp.1007, tmp372
	strh	r0, [r1, #16]	@ movhi	@ temp.1007, <variable>.SliceMbRange
	add	lr, r0, r2	@ tmp382, temp.1007, temp.1002
	strh	lr, [r6, #14]	@ movhi	@ tmp382, <variable>.SliceMbRange
	beq	.L199	@,
	ldr	r6, [fp, #-848]	@, %sfp
	add	r8, r8, #4	@ ivtmp.940, ivtmp.940,
	ldr	lr, [fp, #-856]	@, %sfp
	add	r3, r6, #1	@,,
	str	r3, [fp, #-848]	@, %sfp
	cmp	lr, r3	@,
	bhi	.L172	@,
.L208:
	ldr	r6, [fp, #-868]	@ total_mbn, %sfp
.L165:
	uxth	r9, r6	@ prephitmp.914, total_mbn
	str	r7, [r5, #8]	@ j, <variable>.DecSliceNum
	b	.L183	@
.L171:
	add	r2, r5, r7, asl #2	@, tmp386, pDecReport, j,
	add	r7, r7, #1	@ j, j,
	cmp	r7, #199	@ j,
	strh	r6, [r2, #12]	@ movhi	@ prephitmp.916, <variable>.SliceMbRange
	strh	r9, [r2, #14]	@ movhi	@ D.32974, <variable>.SliceMbRange
	bls	.L170	@,
	b	.L199	@
.L168:
	mul	r9, sl, r0	@ tmp281, DoubleImageWidth, tmp232
	add	r2, r7, #1	@ j.973, j,
	add	ip, r5, r7, asl #2	@, tmp287, pDecReport, j,
	cmp	r2, #199	@ j.973,
	uxth	r0, r9	@ temp.969, tmp281
	add	r3, r0, r3	@ tmp290, temp.969, mbsurplus1
	add	r7, r0, r1	@ tmp283, temp.969, mbsurplus0
	uxth	r3, r3	@ D.33011, tmp290
	uxth	r1, r7	@ temp.971, tmp283
	strh	r3, [ip, #14]	@ movhi	@ D.33011, <variable>.SliceMbRange
	strh	r1, [ip, #12]	@ movhi	@ temp.971, <variable>.SliceMbRange
	bhi	.L199	@,
	mov	r0, ip	@ tmp298, tmp293
	ldr	ip, [r4, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	add	r7, r2, #1	@ j, j.973,
	add	lr, r5, r2, asl #2	@, tmp305, pDecReport, j.973,
	add	r9, r1, ip	@ tmp302, temp.971, <variable>.ImageWidth
	cmp	r7, #200	@ j,
	strh	r9, [r0, #16]	@ movhi	@ tmp302, <variable>.SliceMbRange
	ldr	r1, [r4, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	add	r6, r3, r1	@ tmp309, D.33011, <variable>.ImageWidth
	strh	r6, [lr, #14]	@ movhi	@ tmp309, <variable>.SliceMbRange
	bne	.L170	@,
	b	.L199	@
.L203:
	mov	r2, r0	@,
	movw	r1, #:lower16:.LC1	@,
	mov	r0, #0	@,
	movt	r1, #:upper16:.LC1	@,
	bl	dprint_vfmw	@
	mov	r0, #1	@ D.32962,
	b	.L160	@
.L206:
	mov	r0, #22	@,
	movw	r1, #:lower16:.LC3	@,
	movw	r2, #1121	@,
	movt	r1, #:upper16:.LC3	@,
	bl	dprint_vfmw	@
	mov	r0, #1	@ D.32962,
	b	.L160	@
.L207:
	mov	r0, #22	@,
	movw	r1, #:lower16:.LC3	@,
	movw	r2, #1148	@,
	movt	r1, #:upper16:.LC3	@,
	bl	dprint_vfmw	@
	mov	r0, #1	@ D.32962,
	b	.L160	@
	.fnend
	.size	PostPro_GetH264MbGroup, .-PostPro_GetH264MbGroup
	.align	2
	.global	PostPro_GetHevcMbGroup
	.type	PostPro_GetHevcMbGroup, %function
PostPro_GetHevcMbGroup:
	.fnstart
.LFB1530:
	@ args = 0, pretend = 0, frame = 8
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, r6, r7, r8, r9, sl, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	.pad #12
	sub	sp, sp, #12	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	mov	r9, r0	@ pRepairParam, pRepairParam
	ldr	r0, [r1, #8]	@ D.32836, <variable>.DecSliceNum
	mov	r3, r2	@ pHevcDecParam, pHevcDecParam
	sub	r2, r0, #1	@ tmp234, D.32836,
	cmp	r2, #199	@ tmp234,
	bhi	.L271	@,
	ldr	r0, [r9, #868]	@ <variable>.tiles_enabled_flag, <variable>.tiles_enabled_flag
	mov	r8, #0	@ tmp238,
	ldr	ip, [r9, #28]	@ <variable>.ImageHeight, <variable>.ImageHeight
	ldr	r4, [r9, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	cmp	r0, r8	@ <variable>.tiles_enabled_flag,
	str	r8, [r9, #840]	@ tmp238, <variable>.ValidGroupNum
	str	r8, [r9, #856]	@ tmp238, <variable>.FullRepair
	mul	r4, r4, ip	@ total_mbn, <variable>.ImageWidth, <variable>.ImageHeight
	beq	.L213	@,
	ldr	r0, [r1, #8]	@ prephitmp.1045, <variable>.DecSliceNum
	cmp	r0, r8	@ prephitmp.1045,
	beq	.L214	@,
	mov	r6, r1	@ ivtmp.1108, pDecReport
	mov	r7, #1	@ tmp381,
.L218:
	ldrh	ip, [r6, #12]	@ prephitmp.1054, <variable>.SliceMbRange
	ldrh	r5, [r6, #14]	@ temp.1132, <variable>.SliceMbRange
	cmp	ip, r5	@ prephitmp.1054, temp.1132
	mov	r2, ip	@ j, prephitmp.1054
	bhi	.L215	@,
	add	r0, ip, #1664	@ tmp242, prephitmp.1054,
	add	r0, r3, r0, asl #2	@, ivtmp.1100, pHevcDecParam, tmp242,
	b	.L217	@
.L262:
	ldrh	ip, [r6, #12]	@ prephitmp.1054, <variable>.SliceMbRange
.L217:
	cmp	r4, ip	@ total_mbn, prephitmp.1054
	add	r2, r2, #1	@ j, j,
	blt	.L216	@,
	cmp	r4, r5	@ total_mbn, temp.1132
	blt	.L216	@,
	ldr	ip, [r0, #0]	@ tmp244, <variable>.TsToRsMap
	add	r5, r3, ip	@ tmp246, pHevcDecParam, tmp244
	add	ip, r5, #153600	@ tmp247, tmp246,
	add	r5, ip, #512	@ tmp247, tmp247,
	strb	r7, [r5, #0]	@ tmp381, <variable>.IsDeced
	ldrh	r5, [r6, #14]	@ temp.1132, <variable>.SliceMbRange
.L216:
	cmp	r5, r2	@ temp.1132, j
	add	r0, r0, #4	@ ivtmp.1100, ivtmp.1100,
	bcs	.L262	@,
	ldr	r0, [r1, #8]	@ prephitmp.1045, <variable>.DecSliceNum
.L215:
	add	r8, r8, #1	@ i.1118, i.1118,
	add	r6, r6, #4	@ ivtmp.1108, ivtmp.1108,
	cmp	r0, r8	@ prephitmp.1045, i.1118
	bhi	.L218	@,
.L214:
	movw	r2, #6424	@ tmp251,
	ldr	r1, [r3, r2]	@ <variable>.NumSlicePara, <variable>.NumSlicePara
	cmp	r1, #0	@ <variable>.NumSlicePara,
	beq	.L219	@,
	add	r8, r3, #223232	@ ivtmp.1090, pHevcDecParam,
	mov	sl, #0	@ i.1121,
	add	r8, r8, #516	@ ivtmp.1090, ivtmp.1090,
	mov	r1, sl	@ tmp377, i.1121
	str	r4, [fp, #-48]	@ total_mbn, %sfp
.L226:
	ldr	r6, [r8, #0]	@ j.1119, <variable>.SliceGroup
	ldr	r0, [r8, #4]	@ D.32864, <variable>.SliceGroup
	cmp	r6, r0	@ j.1119, D.32864
	bhi	.L220	@,
	add	r7, r6, #1664	@ tmp365, j.1119,
	ldr	r2, [r3, r7, asl #2]	@ prephitmp.1051, <variable>.TsToRsMap
	add	r2, r2, r3	@ tmp368, prephitmp.1051, pHevcDecParam
	add	r4, r2, #153600	@ tmp257, tmp368,
	add	ip, r4, #512	@ tmp257, tmp257,
	ldrb	r4, [ip, #0]	@ zero_extendqisi2	@ tmp258, <variable>.IsDeced
	cmp	r4, #0	@ tmp258,
	beq	.L221	@,
	rsb	r4, r6, r0	@ tmp393, j.1119, D.32864
	add	ip, r3, r7, asl #2	@, ivtmp.1087, pHevcDecParam, tmp365,
	tst	r4, #1	@ tmp393,
	mov	r4, r6	@ j.1120, j.1119
	beq	.L223	@,
	add	r4, r6, #1	@ j.1120, j.1119,
	cmp	r4, r0	@ j.1120, D.32864
	bls	.L261	@,
	b	.L220	@
.L223:
	add	r4, r4, #1	@ tmp396, j.1120,
	cmp	r4, r0	@ tmp396, D.32864
	add	r4, r4, #1	@ j.1120, tmp396,
	bhi	.L220	@,
	ldr	r5, [ip, #4]!	@ tmp259, <variable>.TsToRsMap
	add	r5, r3, r5	@ tmp261, pHevcDecParam, tmp259
	add	r5, r5, #153600	@ tmp262, tmp261,
	add	r5, r5, #512	@ tmp262, tmp262,
	ldrb	r5, [r5, #0]	@ zero_extendqisi2	@ D.32859, <variable>.IsDeced
	cmp	r5, #0	@ D.32859,
	beq	.L221	@,
.L261:
	ldr	r5, [ip, #4]!	@ tmp421, <variable>.TsToRsMap
	add	r5, r3, r5	@ tmp423, pHevcDecParam, tmp421
	add	r5, r5, #153600	@ tmp424, tmp423,
	add	r5, r5, #512	@ tmp424, tmp424,
	ldrb	r5, [r5, #0]	@ zero_extendqisi2	@ D.32859, <variable>.IsDeced
	cmp	r5, #0	@ D.32859,
	bne	.L223	@,
.L221:
	rsb	r4, r6, r0	@ tmp389, k, D.32864
	add	ip, r7, #1	@ tmp263, tmp365,
	tst	r4, #1	@ tmp389,
	add	ip, r3, ip, asl #2	@, ivtmp.1076, pHevcDecParam, tmp263,
	beq	.L224	@,
	add	r2, r2, #153600	@ tmp413, tmp368,
	add	r6, r6, #1	@ k, k,
	add	r4, r2, #512	@ tmp413, tmp413,
	cmp	r0, r6	@ D.32864, k
	add	ip, ip, #4	@ ivtmp.1076, ivtmp.1076,
	strb	r1, [r4, #0]	@ tmp377, <variable>.IsDeced
	bcc	.L220	@,
	ldr	r4, [ip, #-4]	@ prephitmp.1051, <variable>.TsToRsMap
	add	r2, r4, r3	@ tmp368, prephitmp.1051, pHevcDecParam
	b	.L224	@
.L272:
	ldr	r4, [ip, #-4]	@ prephitmp.1051, <variable>.TsToRsMap
	ldr	r2, [ip], #4	@ prephitmp.1051, <variable>.TsToRsMap
	add	r4, r4, r3	@ tmp401, prephitmp.1051, pHevcDecParam
	add	r4, r4, #153600	@ tmp403, tmp401,
	add	r2, r2, r3	@ tmp368, prephitmp.1051, pHevcDecParam
	add	r4, r4, #512	@ tmp403, tmp403,
	strb	r1, [r4, #0]	@ tmp377, <variable>.IsDeced
.L224:
	add	r6, r6, #1	@ tmp391, k,
	add	r4, r2, #153600	@ tmp268, tmp368,
	add	r2, r4, #512	@ tmp268, tmp268,
	cmp	r0, r6	@ D.32864, tmp391
	add	ip, ip, #4	@ tmp392, ivtmp.1076,
	add	r6, r6, #1	@ k, tmp391,
	strb	r1, [r2, #0]	@ tmp377, <variable>.IsDeced
	bcs	.L272	@,
.L220:
	movw	r0, #6424	@,
	add	sl, sl, #1	@ i.1121, i.1121,
	ldr	ip, [r3, r0]	@ <variable>.NumSlicePara, <variable>.NumSlicePara
	add	r8, r8, #8	@ ivtmp.1090, ivtmp.1090,
	cmp	ip, sl	@ <variable>.NumSlicePara, i.1121
	bhi	.L226	@,
	ldr	r4, [fp, #-48]	@ total_mbn, %sfp
.L219:
	mov	r2, #0	@ i.1116,
.L231:
	cmp	r2, r4	@ i.1116, total_mbn
	bcs	.L233	@,
	add	r0, r2, r3	@ tmp276, i.1116, pHevcDecParam
	add	ip, r0, #153600	@ tmp277, tmp276,
	add	r1, ip, #512	@ tmp277, tmp277,
	ldrb	r1, [r1, #0]	@ zero_extendqisi2	@ tmp278, <variable>.IsDeced
	cmp	r1, #1	@ tmp278,
	addeq	r2, r2, #1	@ i.1116, i.1116,
	ldreq	r1, [r9, #840]	@ prephitmp.1126, <variable>.ValidGroupNum
	beq	.L228	@,
	mvn	r1, r2	@ tmp385, i.1116
	add	r0, r1, r4	@ tmp384, tmp385, total_mbn
	add	ip, r2, #153600	@ tmp279, i.1116,
	tst	r0, #1	@ tmp384,
	add	r1, ip, #512	@ tmp279, tmp279,
	mov	ip, r2	@ i, i.1116
	add	r0, r3, r1	@ ivtmp.1069, pHevcDecParam, tmp279
	beq	.L230	@,
	add	r1, r2, #1	@ i.1122, i.1116,
	cmp	r1, r4	@ i.1122, total_mbn
	bcs	.L229	@,
	ldrb	r5, [r0, #1]!	@ zero_extendqisi2	@ D.32874, <variable>.IsDeced
	cmp	r5, #0	@ D.32874,
	bne	.L229	@,
.L267:
	mov	ip, r1	@ i, i.1122
.L230:
	add	r1, ip, #1	@ i.1122, i,
	cmp	r1, r4	@ i.1122, total_mbn
	bcs	.L229	@,
	ldrb	r5, [r0, #1]!	@ zero_extendqisi2	@ D.32874, <variable>.IsDeced
	cmp	r5, #0	@ D.32874,
	bne	.L229	@,
	ldrb	r5, [r0, #1]!	@ zero_extendqisi2	@ D.32874, <variable>.IsDeced
	mov	ip, r1	@ i, i.1122
	add	r1, r1, #1	@ i.1122, i,
	cmp	r5, #0	@ D.32874,
	beq	.L267	@,
.L229:
	ldr	r0, [r9, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r0, r9, r0, asl #2	@, tmp283, pRepairParam, <variable>.ValidGroupNum,
	strh	r2, [r0, #40]	@ movhi	@ i.1116, <variable>.StartMbn
	mov	r2, r1	@ i.1116, i.1122
	ldr	r1, [r9, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r0, r9, r1, asl #2	@, tmp289, pRepairParam, <variable>.ValidGroupNum,
	strh	ip, [r0, #42]	@ movhi	@ i, <variable>.EndMbn
	ldr	ip, [r9, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r1, ip, #1	@ prephitmp.1126, <variable>.ValidGroupNum,
	str	r1, [r9, #840]	@ prephitmp.1126, <variable>.ValidGroupNum
.L228:
	cmp	r1, #199	@ prephitmp.1126,
	ble	.L231	@,
	mov	r0, #1	@,
	movw	r1, #:lower16:.LC4	@,
	movt	r1, #:upper16:.LC4	@,
	sub	r4, r4, #1	@ tmp296, total_mbn,
	bl	dprint_vfmw	@
	mov	r0, #0	@ D.32841,
	mov	r2, #0	@ movhi	@,
	mov	r3, #1	@ tmp297,
	strh	r4, [r9, #42]	@ movhi	@ tmp296, <variable>.EndMbn
	strh	r2, [r9, #40]	@ movhi	@, <variable>.StartMbn
	str	r3, [r9, #840]	@ tmp297, <variable>.ValidGroupNum
.L212:
	sub	sp, fp, #40
	ldmfd	sp, {r4, r5, r6, r7, r8, r9, sl, fp, sp, pc}
.L233:
	mov	r0, #0	@ D.32841,
	b	.L212	@
.L213:
	ldr	r3, [r1, #8]	@ prephitmp.1045, <variable>.DecSliceNum
	mvn	sl, #0	@ old_slice_end_mbn,
	uxth	r7, r4	@ D.32886, total_mbn
	add	r8, r4, sl	@, total_mbn,
	mov	r2, r1	@ ivtmp.1114, pDecReport
	str	r8, [fp, #-48]	@, %sfp
	add	r5, r1, r3, asl #2	@, tmp300, pDecReport, prephitmp.1045,
	mov	r6, sl	@ old_slice_start_mbn, old_slice_end_mbn
	strh	r7, [r5, #14]	@ movhi	@ D.32886, <variable>.SliceMbRange
	strh	r7, [r5, #12]	@ movhi	@ D.32886, <variable>.SliceMbRange
	b	.L243	@
.L241:
	mov	sl, r5	@ old_slice_end_mbn, curr_slice_end_mbn
	mov	r6, ip	@ old_slice_start_mbn, D.32848
.L236:
	add	r0, r0, #1	@ i.1138, i.1138,
	add	r2, r2, #4	@ ivtmp.1114, ivtmp.1114,
	cmp	r0, r3	@ i.1138, prephitmp.1045
	bhi	.L233	@,
.L243:
	ldrh	ip, [r2, #12]	@ D.32848, <variable>.SliceMbRange
	ldrh	r5, [r2, #14]	@ curr_slice_end_mbn, <variable>.SliceMbRange
	cmp	ip, r4	@ D.32848, total_mbn
	cmple	r5, r4	@, curr_slice_end_mbn, total_mbn
	bgt	.L236	@,
	cmp	ip, r5	@ D.32848, curr_slice_end_mbn
	bgt	.L236	@,
	cmp	ip, sl	@ D.32848, old_slice_end_mbn
	movlt	sl, r6	@ old_slice_end_mbn, old_slice_start_mbn
	add	r8, sl, #1	@ tmp314, old_slice_end_mbn,
	cmp	ip, r8	@ D.32848, tmp314
	ble	.L238	@,
	ldr	r3, [r9, #840]	@ D.32875, <variable>.ValidGroupNum
	cmp	r3, #199	@ D.32875,
	bgt	.L273	@,
	add	r3, r9, r3, asl #2	@, tmp319, pRepairParam, D.32875,
	add	r6, r6, r6, lsr #31	@, tmp325, old_slice_start_mbn, old_slice_start_mbn,
	sub	r8, ip, #1	@ tmp332, D.32848,
	sub	sl, sl, #100	@ tmp369, old_slice_end_mbn,
	strh	r6, [r3, #40]	@ movhi	@ tmp325, <variable>.StartMbn
	ldr	r6, [r9, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r3, r9, r6, asl #2	@, tmp330, pRepairParam, <variable>.ValidGroupNum,
	strh	r8, [r3, #42]	@ movhi	@ tmp332, <variable>.EndMbn
	ldr	r3, [r9, #840]	@ prephitmp.1047, <variable>.ValidGroupNum
	add	r8, r3, #10	@ tmp334, prephitmp.1047,
	mov	r8, r8, asl #2	@ tmp335, tmp334,
	ldrsh	r6, [r8, r9]	@ <variable>.StartMbn, <variable>.StartMbn
	cmp	sl, r6	@ tmp369, <variable>.StartMbn
	strgth	sl, [r8, r9]	@ movhi	@ tmp369, <variable>.StartMbn
	ldrgt	r3, [r9, #840]	@ prephitmp.1047, <variable>.ValidGroupNum
	add	r6, r3, #1	@ tmp343, prephitmp.1047,
	str	r6, [r9, #840]	@ tmp343, <variable>.ValidGroupNum
	ldr	r3, [r1, #8]	@ prephitmp.1045, <variable>.DecSliceNum
.L238:
	sub	r6, r3, #1	@ temp.1130, prephitmp.1045,
	cmp	r6, r0	@ temp.1130, i.1138
	bne	.L241	@,
	add	r8, r1, r0, asl #2	@, tmp346, pDecReport, i.1138,
	ldrh	r6, [r8, #14]	@ D.32853, <variable>.SliceMbRange
	ldr	r8, [fp, #-48]	@, %sfp
	cmp	r6, r8	@ D.32853,
	bge	.L241	@,
	ldr	r3, [r9, #840]	@ temp.1131, <variable>.ValidGroupNum
	cmp	r3, #199	@ temp.1131,
	bgt	.L274	@,
	add	r1, r9, r3, asl #2	@, tmp353, pRepairParam, temp.1131,
	sub	r7, r7, #1	@ tmp361, D.32886,
	mov	r0, #0	@ D.32841,
	strh	r6, [r1, #40]	@ movhi	@ D.32853, <variable>.StartMbn
	ldr	r3, [r9, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	ip, r9, r3, asl #2	@, tmp359, pRepairParam, <variable>.ValidGroupNum,
	strh	r7, [ip, #42]	@ movhi	@ tmp361, <variable>.EndMbn
	ldr	r2, [r9, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	add	r1, r2, #1	@ tmp363, <variable>.ValidGroupNum,
	str	r1, [r9, #840]	@ tmp363, <variable>.ValidGroupNum
	b	.L212	@
.L271:
	mov	r2, r0	@, D.32836
	movw	r1, #:lower16:.LC1	@,
	mov	r0, #0	@,
	movt	r1, #:upper16:.LC1	@,
	bl	dprint_vfmw	@
	mov	r0, #1	@ D.32841,
	b	.L212	@
.L273:
	mov	r0, #1	@,
	movw	r1, #:lower16:.LC5	@,
	ldr	r2, .L275	@,
	movt	r1, #:upper16:.LC5	@,
	bl	dprint_vfmw	@
	mov	r0, #1	@ D.32841,
	b	.L212	@
.L274:
	mov	r0, #1	@,
	movw	r1, #:lower16:.LC6	@,
	ldr	r2, .L275	@,
	movt	r1, #:upper16:.LC6	@,
	bl	dprint_vfmw	@
	mov	r0, #1	@ D.32841,
	b	.L212	@
.L276:
	.align	2
.L275:
	.word	.LANCHOR0+24
	.fnend
	.size	PostPro_GetHevcMbGroup, .-PostPro_GetHevcMbGroup
	.global	__aeabi_idiv
	.align	2
	.global	PostPro_GetRepairParam
	.type	PostPro_GetRepairParam, %function
PostPro_GetRepairParam:
	.fnstart
.LFB1529:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r3, r4, r5, r6, r7, r8, r9, sl, fp, ip, lr, pc}	@,
	.pad #4
	.save {r3, r4, r5, r6, r7, r8, r9, sl, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	add	r8, r1, #872	@ D.32448, pRepairParam,
	mov	r9, r3	@ pDecReport, pDecReport
	mov	r7, r1	@ pRepairParam, pRepairParam
	mov	r3, #0	@ tmp201,
	mov	r4, r2	@ pDecParam, pDecParam
	str	r3, [r1, #840]	@ tmp201, <variable>.ValidGroupNum
	str	r0, [r1, #0]	@ VidStd, <variable>.VidStd
	str	r3, [r8, #840]	@ tmp201, <variable>.ValidGroupNum
	cmp	r0, #16	@ VidStd,
	ldrls	pc, [pc, r0, asl #2]	@ VidStd
	b	.L278	@
.L291:
	.word	.L279
	.word	.L280
	.word	.L281
	.word	.L282
	.word	.L278
	.word	.L283
	.word	.L284
	.word	.L278
	.word	.L285
	.word	.L286
	.word	.L287
	.word	.L287
	.word	.L287
	.word	.L288
	.word	.L278
	.word	.L289
	.word	.L290
.L290:
	ldr	lr, [r2, #1280]	@ <variable>.CurrPicImgIdc, <variable>.CurrPicImgIdc
	mov	sl, #1	@ tmp264,
	add	ip, lr, #328	@ tmp244, <variable>.CurrPicImgIdc,
	movw	lr, #6428	@ tmp251,
	add	r3, ip, #2	@ tmp244, tmp244,
	ldr	r0, [r2, r3, asl #2]	@ tmp247, <variable>.ImgPhyAddr
	str	r0, [r1, #4]	@ tmp247, <variable>.ImageAddr
	movw	r1, #6648	@ tmp248,
	ldr	r2, [r2, r1]	@ <variable>.CurrPicImg2DAddr, <variable>.CurrPicImg2DAddr
	str	r2, [r7, #8]	@ <variable>.CurrPicImg2DAddr, <variable>.Image2DAddr
	ldr	ip, [r4, lr]	@ <variable>.pFirstSlice, <variable>.pFirstSlice
	ldr	r3, [ip, #356]	@ <variable>.Idx2Apc, <variable>.Idx2Apc
	add	r0, r3, #328	@ tmp252, <variable>.Idx2Apc,
	add	r1, r0, #2	@ tmp252, tmp252,
	ldr	r2, [r4, r1, asl #2]	@ tmp255, <variable>.ImgPhyAddr
	str	r2, [r7, #16]	@ tmp255, <variable>.RefImageAddr
	ldr	lr, [r4, #1284]	@ <variable>.CurrPicPmvIdc, <variable>.CurrPicPmvIdc
	add	ip, r4, lr, asl #2	@, tmp261, pDecParam, <variable>.CurrPicPmvIdc,
	ldr	r3, [ip, #1580]	@ tmp263, <variable>.PmvPhyAddr
	str	r3, [r7, #20]	@ tmp263, <variable>.CurrPmvAddr
	ldr	r3, [r4, #68]	@ D.32520, <variable>.CtbLog2SizeY
	mov	ip, sl, asl r3	@ D.32525, tmp264,
	str	r3, [r7, #864]	@ D.32520, <variable>.CtbSize
	ldr	r0, [r4, #188]	@ <variable>.pic_width_in_luma_samples, <variable>.pic_width_in_luma_samples
	sub	r1, r0, #1	@ tmp265, <variable>.pic_width_in_luma_samples,
	add	r2, r1, ip	@ tmp267, tmp265, D.32525
	mov	lr, r2, lsr r3	@ tmp268, tmp267,
	str	lr, [r7, #24]	@ tmp268, <variable>.ImageWidth
	ldr	r0, [r4, #184]	@ <variable>.pic_height_in_luma_samples, <variable>.pic_height_in_luma_samples
	sub	r1, r0, #1	@ tmp269, <variable>.pic_height_in_luma_samples,
	add	r2, r1, ip	@ tmp271, tmp269, D.32525
	mov	lr, r2, lsr r3	@ tmp272, tmp271,
	str	lr, [r7, #28]	@ tmp272, <variable>.ImageHeight
	ldrb	r0, [r4, #217]	@ zero_extendqisi2	@ <variable>.tiles_enabled_flag, <variable>.tiles_enabled_flag
	str	sl, [r7, #32]	@ tmp264, <variable>.IsFrame
	str	r0, [r7, #868]	@ <variable>.tiles_enabled_flag, <variable>.tiles_enabled_flag
	ldr	r1, [r4, #8]	@ <variable>.chroma_format_idc, <variable>.chroma_format_idc
	rsbs	ip, r1, #1	@ tmp276, <variable>.chroma_format_idc
	movcc	ip, #0	@ tmp276
	str	ip, [r7, #36]	@ tmp276, <variable>.ImageCSP
	ldr	r2, [r4, #1316]	@ <variable>.NewPicFlag, <variable>.NewPicFlag
	cmp	r2, #0	@ <variable>.NewPicFlag,
	streq	r2, [r9, #8]	@ <variable>.NewPicFlag, <variable>.DecSliceNum
	bne	.L412	@,
.L312:
	ldr	r2, [r7, #4]	@ temp.1230, <variable>.ImageAddr
	ldr	sl, [r7, #16]	@ <variable>.RefImageAddr, <variable>.RefImageAddr
	cmp	r2, sl	@ temp.1230, <variable>.RefImageAddr
	beq	.L413	@,
.L313:
	mov	r2, #0	@ tmp280,
	str	r2, [r7, #852]	@ tmp280, <variable>.Pic_type
.L310:
	ldr	lr, [r7, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	ldr	r0, [r7, #28]	@ <variable>.ImageHeight, <variable>.ImageHeight
	ldr	r1, [r7, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	cmp	lr, #0	@ <variable>.ValidGroupNum,
	movle	r5, #0	@ err_mbs,
	mul	sl, r1, r0	@ total_mbs, <variable>.ImageWidth, <variable>.ImageHeight
	ble	.L345	@,
	mov	r5, #0	@ err_mbs,
	mov	r4, r7	@ ivtmp.1198, pRepairParam
	mov	r6, r5	@ i.1238, err_mbs
.L346:
	ldrsh	r2, [r4, #42]	@, <variable>.EndMbn
	mov	r0, #22	@,
	ldrsh	r3, [r4, #40]	@, <variable>.StartMbn
	movw	r1, #:lower16:.LC7	@,
	movt	r1, #:upper16:.LC7	@,
	add	r6, r6, #1	@ i.1238, i.1238,
	bl	dprint_vfmw	@
	ldrsh	r0, [r4, #42]	@ <variable>.EndMbn, <variable>.EndMbn
	ldr	r1, [r7, #840]	@ <variable>.ValidGroupNum, <variable>.ValidGroupNum
	ldrsh	r2, [r4, #40]	@ <variable>.StartMbn, <variable>.StartMbn
	add	r3, r0, #1	@ tmp477, <variable>.EndMbn,
	cmp	r1, r6	@ <variable>.ValidGroupNum, i.1238
	add	r4, r4, #4	@ ivtmp.1198, ivtmp.1198,
	rsb	ip, r2, r3	@ tmp479, <variable>.StartMbn, tmp477
	add	r5, r5, ip	@ err_mbs, err_mbs, tmp479
	bgt	.L346	@,
.L345:
	ldr	lr, [r8, #840]	@ D.32781, <variable>.ValidGroupNum
	cmp	lr, #0	@ D.32781,
	ble	.L347	@,
	ldrsh	ip, [r8, #42]	@ <variable>.EndMbn, <variable>.EndMbn
	mov	r2, #1	@ i.1245,
	ldrsh	r1, [r8, #40]	@ <variable>.StartMbn, <variable>.StartMbn
	cmp	r2, lr	@ i.1245, D.32781
	add	r0, ip, r2	@ tmp482, <variable>.EndMbn,
	sub	r3, lr, #1	@ tmp497, D.32781,
	rsb	ip, r1, r0	@ tmp484, <variable>.StartMbn, tmp482
	and	r3, r3, r2	@ tmp499, tmp497,
	add	r5, r5, ip	@ err_mbs, err_mbs, tmp484
	add	r8, r8, #4	@ ivtmp.1192, D.32448,
	beq	.L347	@,
	cmp	r3, #0	@ tmp499,
	beq	.L348	@,
	ldrsh	r0, [r8, #42]	@ <variable>.EndMbn, <variable>.EndMbn
	mov	r2, #2	@ i.1245,
	ldrsh	ip, [r8, #40]	@ <variable>.StartMbn, <variable>.StartMbn
	cmp	r2, lr	@ i.1245, D.32781
	add	r1, r0, #1	@ tmp549, <variable>.EndMbn,
	add	r8, r8, #4	@ ivtmp.1192, ivtmp.1192,
	rsb	r3, ip, r1	@ tmp551, <variable>.StartMbn, tmp549
	add	r5, r5, r3	@ err_mbs, err_mbs, tmp551
	beq	.L347	@,
.L348:
	add	r3, r8, #4	@ tmp501, ivtmp.1192,
	ldrsh	r0, [r8, #42]	@ <variable>.EndMbn, <variable>.EndMbn
	ldrsh	r4, [r8, #40]	@ <variable>.StartMbn, <variable>.StartMbn
	add	r2, r2, #2	@ i.1245, i.1245,
	ldrsh	r8, [r3, #42]	@ <variable>.EndMbn, <variable>.EndMbn
	add	r1, r0, #1	@ tmp538, <variable>.EndMbn,
	ldrsh	r0, [r3, #40]	@ <variable>.StartMbn, <variable>.StartMbn
	rsb	ip, r4, r1	@ tmp540, <variable>.StartMbn, tmp538
	cmp	r2, lr	@ i.1245, D.32781
	add	r1, r8, #1	@ tmp545, <variable>.EndMbn,
	rsb	r1, r0, r1	@ tmp547, <variable>.StartMbn, tmp545
	add	r8, r5, ip	@ err_mbs, err_mbs, tmp540
	add	r5, r8, r1	@ err_mbs, err_mbs, tmp547
	add	r8, r3, #4	@ ivtmp.1192, tmp501,
	bne	.L348	@,
.L347:
	cmp	sl, #0	@ total_mbs,
	moveq	r4, sl	@ err_ratio, total_mbs
	beq	.L350	@,
	mov	r4, #100	@ tmp486,
	mov	r1, sl	@, total_mbs
	mul	r0, r4, r5	@, tmp486, err_mbs
	bl	__aeabi_idiv	@
	cmp	r0, #100	@,
	movge	r0, #100	@ err_ratio.1258,
	bic	r4, r0, r0, asr #31	@ err_ratio, err_ratio.1258
.L350:
	mov	lr, #0	@ tmp490,
	mov	r2, sl	@, total_mbs
	mov	r3, r5	@, err_mbs
	str	lr, [r9, #8]	@ tmp490, <variable>.DecSliceNum
	mov	r0, #22	@,
	movw	r1, #:lower16:.LC8	@,
	movt	r1, #:upper16:.LC8	@,
	bl	dprint_vfmw	@
	mov	r0, r4	@, err_ratio
	ldmfd	sp, {r3, r4, r5, r6, r7, r8, r9, sl, fp, sp, pc}	@
.L278:
	movw	r1, #:lower16:.LC0	@,
	ldr	r2, .L420	@,
	movt	r1, #:upper16:.LC0	@,
	mov	r3, #716	@,
	mov	r0, #0	@,
	bl	dprint_vfmw	@
	b	.L310	@
.L279:
	ldr	sl, [r2, #292]	@ <variable>.CurrPicImgIdc, <variable>.CurrPicImgIdc
	add	r2, r2, sl, asl #2	@, tmp207, pDecParam, <variable>.CurrPicImgIdc,
	ldr	r0, [r2, #308]	@ tmp209, <variable>.ImgPhyAddr
	str	r0, [r1, #4]	@ tmp209, <variable>.ImageAddr
	ldr	r1, [r4, #296]	@ <variable>.CurrPicImg2DAddr, <variable>.CurrPicImg2DAddr
	str	r1, [r7, #8]	@ <variable>.CurrPicImg2DAddr, <variable>.Image2DAddr
	ldr	r3, [r4, #1124]	@ <variable>.pFirstSlice, <variable>.pFirstSlice
	ldr	r1, [r3, #1640]	@ ref_img_idc, <variable>.img_idc
	add	lr, r4, r1, asl #2	@, tmp215, pDecParam, ref_img_idc,
	ldr	ip, [lr, #308]	@ tmp217, <variable>.ImgPhyAddr
	str	ip, [r7, #16]	@ tmp217, <variable>.RefImageAddr
	ldr	sl, [r4, #300]	@ <variable>.CurrPicPmvIdc, <variable>.CurrPicPmvIdc
	add	r2, sl, #206	@ tmp218, <variable>.CurrPicPmvIdc,
	ldr	r0, [r4, r2, asl #2]	@ tmp220, <variable>.PmvPhyAddr
	str	r0, [r7, #20]	@ tmp220, <variable>.CurrPmvAddr
	ldr	r3, [r4, #28]	@ <variable>.pic_width_in_mb, <variable>.pic_width_in_mb
	str	r3, [r7, #24]	@ <variable>.pic_width_in_mb, <variable>.ImageWidth
	ldr	lr, [r4, #20]	@ <variable>.pic_height_in_mb, <variable>.pic_height_in_mb
	str	lr, [r7, #28]	@ <variable>.pic_height_in_mb, <variable>.ImageHeight
	ldrb	ip, [r4, #0]	@ zero_extendqisi2	@ <variable>.pic_structure, <variable>.pic_structure
	rsbs	sl, ip, #1	@ tmp224, <variable>.pic_structure
	movcc	sl, #0	@ tmp224
	str	sl, [r7, #32]	@ tmp224, <variable>.IsFrame
	ldrb	r2, [r4, #1]	@ zero_extendqisi2	@ <variable>.chroma_format_idc, <variable>.chroma_format_idc
	rsbs	r0, r2, #1	@ tmp226, <variable>.chroma_format_idc
	movcc	r0, #0	@ tmp226
	str	r0, [r7, #36]	@ tmp226, <variable>.ImageCSP
	ldr	ip, [r4, #1116]	@ D.32476, <variable>.ApcSize
	cmp	ip, #0	@ D.32476,
	beq	.L292	@,
	ldr	r3, [r4, #1320]	@ <variable>.RefPicFsId, <variable>.RefPicFsId
	cmp	r3, r1	@ <variable>.RefPicFsId, ref_img_idc
	moveq	r3, #0	@ i,
	beq	.L294	@,
	tst	ip, #1	@ D.32476,
	mov	r2, r4	@ ivtmp.1209, pDecParam
	mov	r3, #0	@ i,
	bne	.L295	@,
	ldr	sl, [r4, #1324]	@ D.32470, <variable>.RefPicFsId
	mov	r3, #1	@ i,
	add	r2, r4, #4	@ ivtmp.1209, pDecParam,
	cmp	sl, r1	@ D.32470, ref_img_idc
	bne	.L295	@,
.L294:
	add	r1, r3, #312	@ tmp228, i,
	add	r3, r1, #2	@ tmp228, tmp228,
	ldr	ip, [r4, r3, asl #2]	@ tmp230, <variable>.RefPicType
	str	ip, [r7, #844]	@ tmp230, <variable>.rpr_ref_pic_type
.L292:
	ldr	r2, [r4, #32]	@ <variable>.mb_adaptive_frame_field_flag, <variable>.mb_adaptive_frame_field_flag
	cmp	r2, #0	@ <variable>.mb_adaptive_frame_field_flag,
	bne	.L414	@,
.L298:
	ldrsb	sl, [r4, #2]	@ <variable>.NewPicFlag, <variable>.NewPicFlag
	cmp	sl, #0	@ <variable>.NewPicFlag,
	streq	sl, [r9, #8]	@ <variable>.NewPicFlag, <variable>.DecSliceNum
	bne	.L415	@,
.L300:
	ldr	r2, [r7, #4]	@ D.32487, <variable>.ImageAddr
	ldr	lr, [r7, #16]	@ <variable>.RefImageAddr, <variable>.RefImageAddr
	cmp	r2, lr	@ D.32487, <variable>.RefImageAddr
	bne	.L327	@,
	ldr	ip, [r4, #820]	@ D.32496, <variable>.ImgSlotNum
	cmp	ip, #0	@ D.32496,
	beq	.L327	@,
	ldr	r3, [r4, #308]	@ D.32492, <variable>.ImgPhyAddr
	cmp	r2, r3	@ D.32487, D.32492
	bne	.L328	@,
	tst	ip, #1	@ D.32496,
	mov	r1, r4	@ ivtmp.1204, pDecParam
	mov	r0, #0	@ i.1226,
	bne	.L304	@,
	ldr	r3, [r4, #312]	@ D.32492, <variable>.ImgPhyAddr
	mov	r0, #1	@ i.1226,
	add	r1, r4, #4	@ ivtmp.1204, pDecParam,
	cmp	r3, r2	@ D.32492, D.32487
	beq	.L304	@,
	b	.L328	@
.L389:
	ldr	r3, [lr, #312]	@ D.32492, <variable>.ImgPhyAddr
	cmp	r3, r2	@ D.32492, D.32487
	bne	.L328	@,
.L304:
	add	r3, r0, #1	@ tmp505, i.1226,
	add	lr, r1, #4	@ tmp506, ivtmp.1204,
	cmp	ip, r3	@ D.32496, tmp505
	add	r0, r3, #1	@ i.1226, tmp505,
	bls	.L327	@,
	ldr	r3, [r1, #312]	@ D.32492, <variable>.ImgPhyAddr
	add	r1, lr, #4	@ ivtmp.1204, tmp506,
	cmp	r3, r2	@ D.32492, D.32487
	beq	.L389	@,
.L328:
	str	r3, [r7, #16]	@ D.32588, <variable>.RefImageAddr
	b	.L327	@
.L296:
	ldr	lr, [r2, #1324]	@ D.32470, <variable>.RefPicFsId
	add	r2, r0, #4	@ ivtmp.1209, tmp510,
	cmp	lr, r1	@ D.32470, ref_img_idc
	beq	.L294	@,
	ldr	lr, [r0, #1324]	@ D.32470, <variable>.RefPicFsId
	add	r3, r3, #1	@ i, i,
	cmp	lr, r1	@ D.32470, ref_img_idc
	beq	.L294	@,
.L295:
	add	r3, r3, #1	@ i, i,
	add	r0, r2, #4	@ tmp510, ivtmp.1209,
	cmp	ip, r3	@ D.32476, i
	bhi	.L296	@,
	b	.L292	@
.L280:
	movw	r5, #:lower16:78036	@ tmp417,
	movt	r5, #:upper16:78036	@ tmp417,
	movw	lr, #12384	@ tmp419,
	movw	r3, #12388	@ tmp421,
	ldr	r2, [r2, r5]	@ <variable>.ystaddr_1d, <variable>.ystaddr_1d
	mov	r5, #0	@ tmp434,
	mov	r0, r1	@, pRepairParam
	mov	r1, r9	@, pDecReport
	str	r2, [r7, #4]	@ <variable>.ystaddr_1d, <variable>.ImageAddr
	movw	r2, #12396	@ tmp423,
	ldr	sl, [r4, lr]	@ <variable>.CurFrmImgLuma2dPhyAddr, <variable>.CurFrmImgLuma2dPhyAddr
	str	sl, [r7, #8]	@ <variable>.CurFrmImgLuma2dPhyAddr, <variable>.Image2DAddr
	ldr	ip, [r4, r3]	@ <variable>.FwdRefAddr, <variable>.FwdRefAddr
	str	ip, [r7, #16]	@ <variable>.FwdRefAddr, <variable>.RefImageAddr
	ldr	lr, [r4, r2]	@ <variable>.CurrColmbAddr, <variable>.CurrColmbAddr
	str	lr, [r7, #20]	@ <variable>.CurrColmbAddr, <variable>.CurrPmvAddr
	ldrh	sl, [r4, #78]	@ <variable>.mbwidth, <variable>.mbwidth
	add	r3, sl, #1	@ tmp426, <variable>.mbwidth,
	str	r3, [r7, #24]	@ tmp426, <variable>.ImageWidth
	ldrh	ip, [r4, #80]	@ <variable>.mbheight, <variable>.mbheight
	add	r2, ip, #1	@ tmp428, <variable>.mbheight,
	str	r2, [r7, #28]	@ tmp428, <variable>.ImageHeight
	ldrb	lr, [r4, #5]	@ zero_extendqisi2	@ D.32723, <variable>.fcm
	str	r5, [r7, #36]	@ tmp434, <variable>.ImageCSP
	cmp	lr, r5	@ D.32723,
	cmpne	lr, #2	@, D.32723,
	movne	sl, #0	@, tmp433
	moveq	sl, #1	@, tmp433
	str	sl, [r7, #32]	@ tmp433, <variable>.IsFrame
	bl	PostPro_GetVc1MbGroup	@
	ldr	r3, [r7, #32]	@ <variable>.IsFrame, <variable>.IsFrame
	ldrb	r1, [r4, #68]	@ zero_extendqisi2	@ <variable>.ref_pic_type, <variable>.ref_pic_type
	cmp	r3, #1	@ <variable>.IsFrame,
	streq	r5, [r7, #852]	@ tmp434, <variable>.Pic_type
	and	r0, r1, #3	@ tmp436, <variable>.ref_pic_type,
	str	r0, [r7, #844]	@ tmp436, <variable>.rpr_ref_pic_type
	beq	.L342	@,
	ldrb	r0, [r4, #5]	@ zero_extendqisi2	@ <variable>.fcm, <variable>.fcm
	cmp	r0, #3	@ <variable>.fcm,
	beq	.L416	@,
.L342:
	movw	r3, #:lower16:78068	@ tmp443,
	movt	r3, #:upper16:78068	@ tmp443,
	mov	sl, #4	@ tmp442,
	str	sl, [r7, #864]	@ tmp442, <variable>.CtbSize
	ldr	ip, [r4, r3]	@ <variable>.Compress_en, <variable>.Compress_en
	str	ip, [r7, #848]	@ <variable>.Compress_en, <variable>.Compress_en
	b	.L310	@
.L281:
	ldr	r0, [r2, #212]	@ <variable>.CurPicPhyAddr, <variable>.CurPicPhyAddr
	mov	sl, #0	@ tmp345,
	str	r0, [r1, #4]	@ <variable>.CurPicPhyAddr, <variable>.ImageAddr
	mov	r0, r1	@, pRepairParam
	mov	r1, #14592	@ tmp338,
	ldr	r3, [r2, r1]	@ <variable>.DispFramePhyAddr, <variable>.DispFramePhyAddr
	mov	r1, r9	@, pDecReport
	str	r3, [r7, #8]	@ <variable>.DispFramePhyAddr, <variable>.Image2DAddr
	mov	r3, #1	@ tmp344,
	ldr	lr, [r2, #220]	@ <variable>.FwdRefPicPhyAddr, <variable>.FwdRefPicPhyAddr
	str	lr, [r7, #16]	@ <variable>.FwdRefPicPhyAddr, <variable>.RefImageAddr
	ldr	ip, [r2, #228]	@ <variable>.CurPmvPhyAddr, <variable>.CurPmvPhyAddr
	str	ip, [r7, #20]	@ <variable>.CurPmvPhyAddr, <variable>.CurrPmvAddr
	ldrh	r2, [r2, #164]	@ <variable>.PicWidthInMb, <variable>.PicWidthInMb
	str	r2, [r7, #24]	@ <variable>.PicWidthInMb, <variable>.ImageWidth
	ldrh	lr, [r4, #166]	@ <variable>.PicHeightInMb, <variable>.PicHeightInMb
	str	r3, [r7, #32]	@ tmp344, <variable>.IsFrame
	movw	r3, #14660	@ tmp347,
	str	sl, [r7, #852]	@ tmp345, <variable>.Pic_type
	str	lr, [r7, #28]	@ <variable>.PicHeightInMb, <variable>.ImageHeight
	str	sl, [r7, #36]	@ tmp345, <variable>.ImageCSP
.L406:
	ldr	r3, [r4, r3]	@ <variable>.Compress_en,
	mov	ip, #4	@ tmp395,
	str	ip, [r7, #864]	@ tmp395, <variable>.CtbSize
	str	r3, [r7, #848]	@ <variable>.Compress_en, <variable>.Compress_en
	bl	PostPro_GetMp24MbGroup	@
	b	.L310	@
.L282:
	ldr	r0, [r2, #200]	@ <variable>.CurPicPhyAddr, <variable>.CurPicPhyAddr
	mov	r2, #0	@ tmp330,
	str	r0, [r1, #4]	@ <variable>.CurPicPhyAddr, <variable>.ImageAddr
	ldr	r1, [r4, #224]	@ <variable>.DispFramePhyAddr, <variable>.DispFramePhyAddr
	str	r1, [r7, #8]	@ <variable>.DispFramePhyAddr, <variable>.Image2DAddr
	ldr	lr, [r4, #196]	@ <variable>.FwdRefPhyAddr, <variable>.FwdRefPhyAddr
	str	lr, [r7, #16]	@ <variable>.FwdRefPhyAddr, <variable>.RefImageAddr
	ldr	sl, [r4, #240]	@ <variable>.PmvColmbPhyAddr, <variable>.PmvColmbPhyAddr
	str	sl, [r7, #20]	@ <variable>.PmvColmbPhyAddr, <variable>.CurrPmvAddr
	ldrh	ip, [r4, #152]	@ <variable>.PicWidthInMb, <variable>.PicWidthInMb
	str	ip, [r7, #24]	@ <variable>.PicWidthInMb, <variable>.ImageWidth
	ldrh	r3, [r4, #148]	@ <variable>.PicHeightInMb, <variable>.PicHeightInMb
	str	r3, [r7, #28]	@ <variable>.PicHeightInMb, <variable>.ImageHeight
	ldrb	r0, [r4, #3]	@ zero_extendqisi2	@ <variable>.PictureStructure, <variable>.PictureStructure
	str	r2, [r7, #36]	@ tmp330, <variable>.ImageCSP
	cmp	r0, #3	@ <variable>.PictureStructure,
	movne	r1, #0	@, tmp329
	moveq	r1, #1	@, tmp329
	str	r1, [r7, #32]	@ tmp329, <variable>.IsFrame
	ldrb	r3, [r4, #3]	@ zero_extendqisi2	@ temp.1239, <variable>.PictureStructure
	cmp	r3, #1	@ temp.1239,
	beq	.L404	@,
	cmp	r3, #2	@ temp.1239,
	beq	.L404	@,
	cmp	r3, #3	@ temp.1239,
	streq	r2, [r7, #852]	@ tmp330, <variable>.Pic_type
.L337:
	movw	ip, #45316	@ tmp334,
	mov	r2, #4	@ tmp336,
	ldr	r3, [r4, ip]	@ <variable>.Compress_en, <variable>.Compress_en
	mov	r0, r7	@, pRepairParam
	str	r2, [r7, #864]	@ tmp336, <variable>.CtbSize
	mov	r1, r9	@, pDecReport
	str	r3, [r7, #848]	@ <variable>.Compress_en, <variable>.Compress_en
	bl	PostPro_GetMp24MbGroup	@
	b	.L310	@
.L283:
	ldr	ip, [r2, #128]	@ <variable>.CurPicPhyAddr, <variable>.CurPicPhyAddr
	mov	r3, #0	@ tmp413,
	mov	r0, r1	@, pRepairParam
	mov	r1, r9	@, pDecReport
	str	ip, [r7, #4]	@ <variable>.CurPicPhyAddr, <variable>.ImageAddr
	mov	ip, #1	@ tmp412,
	ldr	r2, [r2, #124]	@ <variable>.FwdRefPhyAddr, <variable>.FwdRefPhyAddr
	str	r2, [r7, #16]	@ <variable>.FwdRefPhyAddr, <variable>.RefImageAddr
	ldr	lr, [r4, #144]	@ <variable>.CurrPmvPhyAddr, <variable>.CurrPmvPhyAddr
	str	lr, [r7, #20]	@ <variable>.CurrPmvPhyAddr, <variable>.CurrPmvAddr
	mov	lr, #4	@ tmp416,
	ldr	sl, [r4, #8]	@ <variable>.PicWidthInMb, <variable>.PicWidthInMb
	str	sl, [r7, #24]	@ <variable>.PicWidthInMb, <variable>.ImageWidth
	ldr	r2, [r4, #12]	@ <variable>.PicHeightInMb, <variable>.PicHeightInMb
	str	ip, [r7, #32]	@ tmp412, <variable>.IsFrame
	str	r3, [r7, #852]	@ tmp413, <variable>.Pic_type
	str	r2, [r7, #28]	@ <variable>.PicHeightInMb, <variable>.ImageHeight
	str	r3, [r7, #36]	@ tmp413, <variable>.ImageCSP
	ldr	sl, [r4, #152]	@ <variable>.Compress_en, <variable>.Compress_en
	str	lr, [r7, #864]	@ tmp416, <variable>.CtbSize
	str	sl, [r7, #848]	@ <variable>.Compress_en, <variable>.Compress_en
	bl	PostPro_GetDivx3MbGroup	@
	b	.L310	@
.L284:
	movw	ip, #14440	@ tmp350,
	add	r3, ip, #12	@ tmp351, tmp351,
	ldr	lr, [r2, ip]	@ D.32641, <variable>.CurPicAddr
	mov	r2, #0	@ tmp361,
	str	lr, [r1, #4]	@ D.32641, <variable>.ImageAddr
	ldr	r5, [r4, r3]	@ <variable>.rcn_address, <variable>.rcn_address
	str	r5, [r1, #8]	@ <variable>.rcn_address, <variable>.Image2DAddr
	movw	r1, #14432	@ tmp353,
	ldr	r5, [r4, r1]	@ <variable>.FwdRefPic0Addr, <variable>.FwdRefPic0Addr
	add	r6, r1, #12	@ tmp355, tmp355,
	str	r5, [r7, #16]	@ <variable>.FwdRefPic0Addr, <variable>.RefImageAddr
	ldr	r1, [r4, r6]	@ <variable>.CurPmvAddr, <variable>.CurPmvAddr
	str	r1, [r7, #20]	@ <variable>.CurPmvAddr, <variable>.CurrPmvAddr
	ldrh	ip, [r4, #48]	@ <variable>.PicWidthInMb, <variable>.PicWidthInMb
	str	ip, [r7, #24]	@ <variable>.PicWidthInMb, <variable>.ImageWidth
	ldrh	r3, [r4, #50]	@ <variable>.PicHeightInMb, <variable>.PicHeightInMb
	str	r3, [r7, #28]	@ <variable>.PicHeightInMb, <variable>.ImageHeight
	mov	r6, r3, lsr #1	@ tmp372, <variable>.PicHeightInMb,
	ldrb	r0, [r4, #8]	@ zero_extendqisi2	@ <variable>.PicStruct, <variable>.PicStruct
	str	r2, [r7, #36]	@ tmp361, <variable>.ImageCSP
	cmp	r0, #3	@ <variable>.PicStruct,
	movne	r0, #0	@, tmp360
	moveq	r0, #1	@, tmp360
	str	r0, [r7, #32]	@ tmp360, <variable>.IsFrame
	ldr	sl, [r9, #4]	@ <variable>.ImgStride, <variable>.ImgStride
	str	r5, [r8, #16]	@ <variable>.FwdRefPic0Addr, <variable>.RefImageAddr
	add	lr, sl, lr	@ tmp363, <variable>.ImgStride, D.32641
	str	lr, [r8, #4]	@ tmp363, <variable>.ImageAddr
	ldr	lr, [r9, #4]	@ <variable>.ImgStride, <variable>.ImgStride
	str	r3, [r8, #28]	@ <variable>.PicHeightInMb, <variable>.ImageHeight
	mov	r3, #9	@ tmp367,
	str	ip, [r8, #24]	@ <variable>.PicWidthInMb, <variable>.ImageWidth
	mul	ip, r3, lr	@ tmp365, tmp367, <variable>.ImgStride
	str	r0, [r8, #32]	@ tmp360, <variable>.IsFrame
	str	r2, [r8, #36]	@ tmp361, <variable>.ImageCSP
	mla	sl, r6, ip, r1	@ tmp375, tmp372, tmp365, <variable>.CurPmvAddr
	str	sl, [r8, #20]	@ tmp375, <variable>.CurrPmvAddr
	ldrb	r3, [r4, #8]	@ zero_extendqisi2	@ temp.1244, <variable>.PicStruct
	cmp	r3, #3	@ temp.1244,
	streq	r2, [r7, #852]	@ tmp361, <variable>.Pic_type
	beq	.L340	@,
	cmp	r3, #1	@ temp.1244,
	streq	r3, [r7, #852]	@ temp.1244, <variable>.Pic_type
.L340:
	movw	sl, #14864	@ tmp382,
	mov	r2, #4	@ tmp384,
	ldr	lr, [r4, sl]	@ <variable>.Compress_en, <variable>.Compress_en
	mov	r0, r7	@, pRepairParam
	str	r2, [r7, #864]	@ tmp384, <variable>.CtbSize
	mov	r1, r9	@, pDecReport
	str	lr, [r7, #848]	@ <variable>.Compress_en, <variable>.Compress_en
	bl	PostPro_GetAvsMbGroup	@
	b	.L310	@
.L285:
	ldr	r1, [r2, #56]	@ <variable>.CurPicPhyAddr, <variable>.CurPicPhyAddr
	mov	r3, #0	@ tmp391,
	mov	ip, #1	@ tmp390,
	mov	r0, r7	@, pRepairParam
	str	r1, [r7, #4]	@ <variable>.CurPicPhyAddr, <variable>.ImageAddr
	mov	r1, r9	@, pDecReport
	ldr	lr, [r2, #52]	@ <variable>.FwdRefPhyAddr, <variable>.FwdRefPhyAddr
	str	lr, [r7, #16]	@ <variable>.FwdRefPhyAddr, <variable>.RefImageAddr
	ldr	sl, [r2, #72]	@ <variable>.CurrPmvPhyAddr, <variable>.CurrPmvPhyAddr
	str	sl, [r7, #20]	@ <variable>.CurrPmvPhyAddr, <variable>.CurrPmvAddr
	ldr	r2, [r2, #4]	@ <variable>.PicWidthInMb, <variable>.PicWidthInMb
	str	r2, [r7, #24]	@ <variable>.PicWidthInMb, <variable>.ImageWidth
	ldr	lr, [r4, #8]	@ <variable>.PicHeightInMb, <variable>.PicHeightInMb
	str	r3, [r7, #852]	@ tmp391, <variable>.Pic_type
	str	r3, [r7, #36]	@ tmp391, <variable>.ImageCSP
	movw	r3, #11344	@ tmp393,
	str	ip, [r7, #32]	@ tmp390, <variable>.IsFrame
	str	lr, [r7, #28]	@ <variable>.PicHeightInMb, <variable>.ImageHeight
	b	.L406	@
.L286:
	ldr	r1, [r2, #52]	@ <variable>.CurPicPhyAddr, <variable>.CurPicPhyAddr
	mov	sl, #0	@ tmp402,
	mov	lr, #1	@ tmp401,
	mov	r0, r7	@, pRepairParam
	str	r1, [r7, #4]	@ <variable>.CurPicPhyAddr, <variable>.ImageAddr
	mov	r1, r9	@, pDecReport
	ldr	r2, [r2, #48]	@ <variable>.FwdRefPhyAddr, <variable>.FwdRefPhyAddr
	str	r2, [r7, #16]	@ <variable>.FwdRefPhyAddr, <variable>.RefImageAddr
	ldr	ip, [r4, #68]	@ <variable>.CurrPmvPhyAddr, <variable>.CurrPmvPhyAddr
	str	ip, [r7, #20]	@ <variable>.CurrPmvPhyAddr, <variable>.CurrPmvAddr
	ldr	r3, [r4, #4]	@ <variable>.PicWidthInMb, <variable>.PicWidthInMb
	str	r3, [r7, #24]	@ <variable>.PicWidthInMb, <variable>.ImageWidth
	movw	r3, #11340	@ tmp404,
	ldr	r2, [r4, #8]	@ <variable>.PicHeightInMb, <variable>.PicHeightInMb
	str	lr, [r7, #32]	@ tmp401, <variable>.IsFrame
	str	sl, [r7, #852]	@ tmp402, <variable>.Pic_type
	str	r2, [r7, #28]	@ <variable>.PicHeightInMb, <variable>.ImageHeight
	str	sl, [r7, #36]	@ tmp402, <variable>.ImageCSP
	b	.L406	@
.L287:
	ldr	ip, [r2, #172]	@ <variable>.image_curr_recon_addr, <variable>.image_curr_recon_addr
	mov	r5, #0	@ tmp452,
	mov	r0, r1	@, pRepairParam
	mov	r1, r9	@, pDecReport
	str	ip, [r7, #4]	@ <variable>.image_curr_recon_addr, <variable>.ImageAddr
	mov	ip, #1	@ tmp451,
	ldr	lr, [r2, #172]	@ <variable>.image_curr_recon_addr, <variable>.image_curr_recon_addr
	str	lr, [r7, #8]	@ <variable>.image_curr_recon_addr, <variable>.Image2DAddr
	ldr	r2, [r2, #180]	@ <variable>.image_last_ref_addr, <variable>.image_last_ref_addr
	str	r2, [r7, #16]	@ <variable>.image_last_ref_addr, <variable>.RefImageAddr
	ldr	sl, [r4, #184]	@ <variable>.CurPmvAddr, <variable>.CurPmvAddr
	str	sl, [r7, #20]	@ <variable>.CurPmvAddr, <variable>.CurrPmvAddr
	ldrh	r3, [r4, #52]	@ <variable>.PicWidthInMb, <variable>.PicWidthInMb
	str	r3, [r7, #24]	@ <variable>.PicWidthInMb, <variable>.ImageWidth
	ldrh	lr, [r4, #54]	@ <variable>.PicHeightInMb, <variable>.PicHeightInMb
	str	ip, [r7, #32]	@ tmp451, <variable>.IsFrame
	str	r5, [r7, #36]	@ tmp452, <variable>.ImageCSP
	str	lr, [r7, #28]	@ <variable>.PicHeightInMb, <variable>.ImageHeight
	bl	PostPro_GetVp6MbGroup	@
	str	r5, [r7, #852]	@ tmp452, <variable>.Pic_type
	str	r5, [r7, #844]	@ tmp452, <variable>.rpr_ref_pic_type
	mov	r2, #4	@ tmp456,
	ldr	r0, [r4, #192]	@ <variable>.Compress_en, <variable>.Compress_en
	str	r2, [r7, #864]	@ tmp456, <variable>.CtbSize
	str	r0, [r7, #848]	@ <variable>.Compress_en, <variable>.Compress_en
	b	.L310	@
.L288:
	ldr	r3, [r2, #3116]	@ <variable>.image_curr_rcn_addr, <variable>.image_curr_rcn_addr
	mov	lr, #0	@ tmp464,
	mov	r0, r1	@, pRepairParam
	mov	r1, r9	@, pDecReport
	str	r3, [r7, #4]	@ <variable>.image_curr_rcn_addr, <variable>.ImageAddr
	ldr	ip, [r2, #3116]	@ <variable>.image_curr_rcn_addr, <variable>.image_curr_rcn_addr
	str	ip, [r7, #8]	@ <variable>.image_curr_rcn_addr, <variable>.Image2DAddr
	mov	ip, #1	@ tmp463,
	ldr	r2, [r2, #3128]	@ <variable>.image_last_ref_addr, <variable>.image_last_ref_addr
	str	r2, [r7, #16]	@ <variable>.image_last_ref_addr, <variable>.RefImageAddr
	ldr	sl, [r4, #3132]	@ <variable>.CurrPmvAddr, <variable>.CurrPmvAddr
	str	sl, [r7, #20]	@ <variable>.CurrPmvAddr, <variable>.CurrPmvAddr
	mov	sl, #4	@ tmp467,
	ldr	r3, [r4, #2784]	@ <variable>.pic_width_in_mb, <variable>.pic_width_in_mb
	str	r3, [r7, #24]	@ <variable>.pic_width_in_mb, <variable>.ImageWidth
	ldr	r2, [r4, #2788]	@ <variable>.pic_height_in_mb, <variable>.pic_height_in_mb
	str	ip, [r7, #32]	@ tmp463, <variable>.IsFrame
	str	lr, [r7, #852]	@ tmp464, <variable>.Pic_type
	str	r2, [r7, #28]	@ <variable>.pic_height_in_mb, <variable>.ImageHeight
	str	lr, [r7, #36]	@ tmp464, <variable>.ImageCSP
	ldr	r3, [r4, #3140]	@ <variable>.Compress_en, <variable>.Compress_en
	str	sl, [r7, #864]	@ tmp467, <variable>.CtbSize
	str	r3, [r7, #848]	@ <variable>.Compress_en, <variable>.Compress_en
	bl	PostPro_GetVp8MbGroup	@
	b	.L310	@
.L289:
	ldr	ip, [r2, #292]	@ <variable>.CurrPicImgIdc, <variable>.CurrPicImgIdc
	add	r3, r2, ip, asl #2	@, tmp285, pDecParam, <variable>.CurrPicImgIdc,
	ldr	r0, [r3, #308]	@ tmp287, <variable>.ImgPhyAddr
	str	r0, [r1, #4]	@ tmp287, <variable>.ImageAddr
	ldr	r1, [r2, #296]	@ <variable>.CurrPicImg2DAddr, <variable>.CurrPicImg2DAddr
	str	r1, [r7, #8]	@ <variable>.CurrPicImg2DAddr, <variable>.Image2DAddr
	ldr	r2, [r2, #1124]	@ <variable>.pFirstSlice, <variable>.pFirstSlice
	ldr	r1, [r2, #1640]	@ mvc_ref_img_idc, <variable>.img_idc
	add	sl, r4, r1, asl #2	@, tmp293, pDecParam, mvc_ref_img_idc,
	ldr	lr, [sl, #308]	@ tmp295, <variable>.ImgPhyAddr
	str	lr, [r7, #16]	@ tmp295, <variable>.RefImageAddr
	ldr	ip, [r4, #300]	@ <variable>.CurrPicPmvIdc, <variable>.CurrPicPmvIdc
	add	r3, ip, #206	@ tmp296, <variable>.CurrPicPmvIdc,
	ldr	r0, [r4, r3, asl #2]	@ tmp298, <variable>.PmvPhyAddr
	str	r0, [r7, #20]	@ tmp298, <variable>.CurrPmvAddr
	ldr	r2, [r4, #28]	@ <variable>.pic_width_in_mb, <variable>.pic_width_in_mb
	str	r2, [r7, #24]	@ <variable>.pic_width_in_mb, <variable>.ImageWidth
	ldr	sl, [r4, #20]	@ <variable>.pic_height_in_mb, <variable>.pic_height_in_mb
	str	sl, [r7, #28]	@ <variable>.pic_height_in_mb, <variable>.ImageHeight
	ldrb	lr, [r4, #0]	@ zero_extendqisi2	@ <variable>.pic_structure, <variable>.pic_structure
	rsbs	ip, lr, #1	@ tmp302, <variable>.pic_structure
	movcc	ip, #0	@ tmp302
	str	ip, [r7, #32]	@ tmp302, <variable>.IsFrame
	ldrb	r3, [r4, #1]	@ zero_extendqisi2	@ <variable>.chroma_format_idc, <variable>.chroma_format_idc
	rsbs	r0, r3, #1	@ tmp304, <variable>.chroma_format_idc
	movcc	r0, #0	@ tmp304
	str	r0, [r7, #36]	@ tmp304, <variable>.ImageCSP
	ldr	ip, [r4, #1116]	@ D.32575, <variable>.ApcSize
	cmp	ip, #0	@ D.32575,
	beq	.L318	@,
	ldr	r3, [r4, #1320]	@ <variable>.RefPicFsId, <variable>.RefPicFsId
	cmp	r3, r1	@ <variable>.RefPicFsId, mvc_ref_img_idc
	moveq	r3, #0	@ i.1233,
	beq	.L320	@,
	tst	ip, #1	@ D.32575,
	mov	r2, r4	@ ivtmp.1219, pDecParam
	mov	r3, #0	@ i.1233,
	bne	.L321	@,
	ldr	r0, [r4, #1324]	@ D.32570, <variable>.RefPicFsId
	mov	r3, #1	@ i.1233,
	add	r2, r4, #4	@ ivtmp.1219, pDecParam,
	cmp	r0, r1	@ D.32570, mvc_ref_img_idc
	bne	.L321	@,
.L320:
	add	r1, r3, #312	@ tmp306, i.1233,
	add	r2, r1, #2	@ tmp306, tmp306,
	ldr	sl, [r4, r2, asl #2]	@ tmp308, <variable>.RefPicType
	str	sl, [r7, #844]	@ tmp308, <variable>.rpr_ref_pic_type
.L318:
	ldr	r2, [r4, #32]	@ <variable>.mb_adaptive_frame_field_flag, <variable>.mb_adaptive_frame_field_flag
	cmp	r2, #0	@ <variable>.mb_adaptive_frame_field_flag,
	bne	.L417	@,
.L324:
	ldrsb	r3, [r4, #2]	@ <variable>.NewPicFlag, <variable>.NewPicFlag
	cmp	r3, #0	@ <variable>.NewPicFlag,
	streq	r3, [r9, #8]	@ <variable>.NewPicFlag, <variable>.DecSliceNum
	bne	.L418	@,
.L326:
	ldr	r2, [r7, #4]	@ temp.1235, <variable>.ImageAddr
	ldr	ip, [r7, #16]	@ <variable>.RefImageAddr, <variable>.RefImageAddr
	cmp	r2, ip	@ temp.1235, <variable>.RefImageAddr
	beq	.L419	@,
.L327:
	ldrb	r3, [r4, #0]	@ zero_extendqisi2	@ temp.1237, <variable>.pic_structure
	cmp	r3, #0	@ temp.1237,
	beq	.L403	@,
	cmp	r3, #1	@ temp.1237,
	beq	.L403	@,
	cmp	r3, #2	@ temp.1237,
	beq	.L403	@,
	cmp	r3, #3	@ temp.1237,
	bne	.L333	@,
	mov	r3, #0	@ tmp319,
.L403:
	str	r3, [r7, #852]	@ tmp319, <variable>.Pic_type
.L333:
	ldr	lr, [r4, #1384]	@ <variable>.Compress_en, <variable>.Compress_en
	mov	r2, #4	@ tmp321,
	str	r2, [r7, #864]	@ tmp321, <variable>.CtbSize
	str	lr, [r7, #848]	@ <variable>.Compress_en, <variable>.Compress_en
	b	.L310	@
.L322:
	ldr	lr, [r2, #1324]	@ D.32570, <variable>.RefPicFsId
	add	r2, r0, #4	@ ivtmp.1219, tmp521,
	cmp	lr, r1	@ D.32570, mvc_ref_img_idc
	beq	.L320	@,
	ldr	sl, [r0, #1324]	@ D.32570, <variable>.RefPicFsId
	add	r3, r3, #1	@ i.1233, i.1233,
	cmp	sl, r1	@ D.32570, mvc_ref_img_idc
	beq	.L320	@,
.L321:
	add	r3, r3, #1	@ i.1233, i.1233,
	add	r0, r2, #4	@ tmp521, ivtmp.1219,
	cmp	ip, r3	@ D.32575, i.1233
	bhi	.L322	@,
	b	.L318	@
.L414:
	ldrb	r0, [r4, #0]	@ zero_extendqisi2	@ <variable>.pic_structure, <variable>.pic_structure
	rsbs	r2, r0, #1	@ prephitmp.1261, <variable>.pic_structure
	movcc	r2, #0	@ prephitmp.1261
	b	.L298	@
.L417:
	ldrb	r0, [r4, #0]	@ zero_extendqisi2	@ <variable>.pic_structure, <variable>.pic_structure
	rsbs	r2, r0, #1	@ prephitmp.1168, <variable>.pic_structure
	movcc	r2, #0	@ prephitmp.1168
	b	.L324	@
.L404:
	str	r3, [r7, #852]	@ temp.1239, <variable>.Pic_type
	b	.L337	@
.L416:
	ldrb	r3, [r4, #8]	@ zero_extendqisi2	@ D.32737, <variable>.curparity
	cmp	r3, #0	@ D.32737,
	beq	.L405	@,
	cmp	r3, #1	@ D.32737,
	bne	.L342	@,
.L405:
	add	r1, r3, #1	@ tmp441, tmp441,
	str	r1, [r7, #852]	@ tmp441, <variable>.Pic_type
	b	.L342	@
.L419:
	ldr	ip, [r4, #820]	@ D.32592, <variable>.ImgSlotNum
	cmp	ip, #0	@ D.32592,
	beq	.L327	@,
	ldr	r3, [r4, #308]	@ D.32588, <variable>.ImgPhyAddr
	cmp	r2, r3	@ temp.1235, D.32588
	bne	.L328	@,
	tst	ip, #1	@ D.32592,
	mov	r1, r4	@ ivtmp.1214, pDecParam
	mov	r0, #0	@ i.1228,
	bne	.L330	@,
	ldr	r3, [r4, #312]	@ D.32588, <variable>.ImgPhyAddr
	mov	r0, #1	@ i.1228,
	add	r1, r4, #4	@ ivtmp.1214, pDecParam,
	cmp	r2, r3	@ temp.1235, D.32588
	beq	.L330	@,
	b	.L328	@
.L392:
	ldr	r3, [lr, #312]	@ D.32588, <variable>.ImgPhyAddr
	cmp	r2, r3	@ temp.1235, D.32588
	bne	.L328	@,
.L330:
	add	sl, r0, #1	@ tmp516, i.1228,
	add	lr, r1, #4	@ tmp515, ivtmp.1214,
	cmp	ip, sl	@ D.32592, tmp516
	add	r0, sl, #1	@ i.1228, tmp516,
	bls	.L327	@,
	ldr	r3, [r1, #312]	@ D.32588, <variable>.ImgPhyAddr
	add	r1, lr, #4	@ ivtmp.1214, tmp515,
	cmp	r2, r3	@ temp.1235, D.32588
	beq	.L392	@,
	str	r3, [r7, #16]	@ D.32588, <variable>.RefImageAddr
	b	.L327	@
.L418:
	mov	r0, r7	@, pRepairParam
	mov	r1, r9	@, pDecReport
	bl	PostPro_GetH264MbGroup	@
	b	.L326	@
.L415:
	mov	r0, r7	@, pRepairParam
	mov	r1, r9	@, pDecReport
	bl	PostPro_GetH264MbGroup	@
	b	.L300	@
.L413:
	ldr	r0, [r4, #1576]	@ D.32549, <variable>.ImgSlotNum
	cmp	r0, #0	@ D.32549,
	beq	.L313	@,
	ldr	r3, [r4, #1320]	@ D.32545, <variable>.ImgPhyAddr
	cmp	r2, r3	@ temp.1230, D.32545
	bne	.L314	@,
	tst	r0, #1	@ D.32549,
	mov	r1, #0	@ i.1232,
	bne	.L316	@,
	ldr	r3, [r4, #1324]	@ D.32545, <variable>.ImgPhyAddr
	mov	r1, #1	@ i.1232,
	add	r4, r4, #4	@ ivtmp.1224, ivtmp.1224,
	cmp	r3, r2	@ D.32545, temp.1230
	beq	.L316	@,
	b	.L314	@
.L390:
	ldr	r3, [ip, #1324]	@ D.32545, <variable>.ImgPhyAddr
	cmp	r3, r2	@ D.32545, temp.1230
	bne	.L314	@,
.L316:
	add	r1, r1, #1	@ tmp526, i.1232,
	add	ip, r4, #4	@ tmp525, ivtmp.1224,
	cmp	r0, r1	@ D.32549, tmp526
	add	r1, r1, #1	@ i.1232, tmp526,
	bls	.L313	@,
	ldr	r3, [r4, #1324]	@ D.32545, <variable>.ImgPhyAddr
	add	r4, ip, #4	@ ivtmp.1224, tmp525,
	cmp	r3, r2	@ D.32545, temp.1230
	beq	.L390	@,
.L314:
	str	r3, [r7, #16]	@ D.32545, <variable>.RefImageAddr
	b	.L313	@
.L412:
	mov	r0, r7	@, pRepairParam
	mov	r1, r9	@, pDecReport
	mov	r2, r4	@, pDecParam
	bl	PostPro_GetHevcMbGroup	@
	b	.L312	@
.L421:
	.align	2
.L420:
	.word	.LANCHOR0+48
	.fnend
	.size	PostPro_GetRepairParam, .-PostPro_GetRepairParam
	.align	2
	.global	PostPro_SetFullRepair
	.type	PostPro_SetFullRepair, %function
PostPro_SetFullRepair:
	.fnstart
.LFB1539:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	mov	r4, #816	@ tmp141,
	mul	r4, r4, r2	@ tmp140, tmp141, VdhId
	movw	ip, #:lower16:g_DecReport	@ tmp142,
	movt	ip, #:upper16:g_DecReport	@ tmp142,
	movw	r3, #:lower16:g_RepairParam	@ tmp148,
	movt	r3, #:upper16:g_RepairParam	@ tmp148,
	mov	r5, r1	@ pDecParam, pDecParam
	add	lr, ip, r4	@ pDecReport, tmp142, tmp140
	mov	r1, #1744	@ tmp146,
	mla	r1, r1, r2, r3	@, tmp146, VdhId, tmp148
	mov	r2, r5	@, pDecParam
	mov	r3, lr	@, pDecReport
	mov	r5, #1	@ tmp143,
	str	r5, [ip, r4]	@ tmp143, <variable>.RetType
	mov	ip, #0	@ tmp144,
	str	ip, [lr, #8]	@ tmp144, <variable>.DecSliceNum
	bl	PostPro_GetRepairParam	@
	ldmfd	sp, {r4, r5, fp, sp, pc}	@
	.fnend
	.size	PostPro_SetFullRepair, .-PostPro_SetFullRepair
	.align	2
	.global	PostPro_CopyYuv_Vp6
	.type	PostPro_CopyYuv_Vp6, %function
PostPro_CopyYuv_Vp6:
	.fnstart
.LFB1528:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r3, r4, r5, r6, r7, r8, fp, ip, lr, pc}	@,
	.pad #4
	.save {r3, r4, r5, r6, r7, r8, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	movw	r5, #:lower16:g_RepairParam	@ tmp144,
	movt	r5, #:upper16:g_RepairParam	@ tmp144,
	mov	r4, #1744	@ tmp143,
	ldr	lr, [r0, #172]	@ <variable>.image_curr_recon_addr, <variable>.image_curr_recon_addr
	mov	r6, #0	@ tmp150,
	mla	r4, r4, r1, r5	@ pRepairParam, tmp143, VdhId, tmp144
	mov	r5, r0	@ pVp6DecParam, pVp6DecParam
	mov	r7, #1	@ tmp149,
	mov	r8, r1	@ VdhId, VdhId
	mov	r0, #22	@,
	movw	r1, #:lower16:.LC9	@,
	movt	r1, #:upper16:.LC9	@,
	str	lr, [r4, #4]	@ <variable>.image_curr_recon_addr, <variable>.ImageAddr
	ldr	ip, [r5, #172]	@ <variable>.image_curr_recon_addr, <variable>.image_curr_recon_addr
	str	ip, [r4, #8]	@ <variable>.image_curr_recon_addr, <variable>.Image2DAddr
	ldr	r3, [r5, #180]	@ <variable>.image_last_ref_addr, <variable>.image_last_ref_addr
	str	r3, [r4, #16]	@ <variable>.image_last_ref_addr, <variable>.RefImageAddr
	ldr	r2, [r5, #184]	@ <variable>.CurPmvAddr, <variable>.CurPmvAddr
	str	r2, [r4, #20]	@ <variable>.CurPmvAddr, <variable>.CurrPmvAddr
	ldrh	r2, [r5, #52]	@ D.32364, <variable>.PicWidthInMb
	str	r2, [r4, #24]	@ D.32364, <variable>.ImageWidth
	ldrh	lr, [r5, #54]	@ D.32366, <variable>.PicHeightInMb
	str	r7, [r4, #32]	@ tmp149, <variable>.IsFrame
	str	r6, [r4, #36]	@ tmp150, <variable>.ImageCSP
	mov	r3, lr	@, D.32366
	str	lr, [r4, #28]	@ D.32366, <variable>.ImageHeight
	bl	dprint_vfmw	@
	ldr	ip, [r4, #28]	@ <variable>.ImageHeight, <variable>.ImageHeight
	ldr	r1, [r4, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	movw	r3, #:lower16:g_vdm_hal_fun_ptr	@ tmp167,
	movt	r3, #:upper16:g_vdm_hal_fun_ptr	@ tmp167,
	str	r6, [r4, #844]	@ tmp150, <variable>.rpr_ref_pic_type
	str	r7, [r4, #840]	@ tmp149, <variable>.ValidGroupNum
	mul	r2, r1, ip	@ tmp159, <variable>.ImageWidth, <variable>.ImageHeight
	ldr	ip, [r3, #104]	@ D.32378, g_vdm_hal_fun_ptr.pfun_VDMHAL_PrepareRepair
	strh	r6, [r4, #40]	@ movhi	@ tmp150, <variable>.StartMbn
	cmp	ip, r6	@ D.32378,
	sub	r1, r2, #1	@ tmp161, tmp159,
	strh	r1, [r4, #42]	@ movhi	@ tmp161, <variable>.EndMbn
	ldr	r3, [r5, #192]	@ <variable>.Compress_en, <variable>.Compress_en
	moveq	r0, r7	@ D.32381, tmp149
	str	r7, [r4, #856]	@ tmp149, <variable>.FullRepair
	str	r6, [r4, #852]	@ tmp150, <variable>.Pic_type
	str	r3, [r4, #848]	@ <variable>.Compress_en, <variable>.Compress_en
	str	r6, [r4, #844]	@ tmp150, <variable>.rpr_ref_pic_type
	ldmeqfd	sp, {r3, r4, r5, r6, r7, r8, fp, sp, pc}	@
	mov	r1, r5	@, pVp6DecParam
	mov	r2, r6	@, tmp150
	mov	r3, r8	@, VdhId
	mov	r0, #10	@,
	blx	ip	@ D.32378
	subs	r0, r0, #0	@ D.32381,,
	movne	r0, #1	@ D.32381
	ldmfd	sp, {r3, r4, r5, r6, r7, r8, fp, sp, pc}	@
	.fnend
	.size	PostPro_CopyYuv_Vp6, .-PostPro_CopyYuv_Vp6
	.align	2
	.global	PostPro_CopyYuv_Vc1
	.type	PostPro_CopyYuv_Vc1, %function
PostPro_CopyYuv_Vc1:
	.fnstart
.LFB1527:
	@ args = 0, pretend = 0, frame = 0
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, r6, r7, r8, sl, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, r6, r7, r8, sl, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	mov	r5, r0	@ pVc1DecParam, pVc1DecParam
	ldrh	r0, [r0, #74]	@ D.32302, <variable>.DispPicWidth
	mov	r8, r1	@ VdhId, VdhId
	movw	r6, #:lower16:g_RepairParam	@ tmp146,
	movw	r2, #2047	@ tmp149,
	sub	r1, r0, #1	@ tmp147, D.32302,
	movt	r6, #:upper16:g_RepairParam	@ tmp146,
	mov	r4, #1744	@ tmp145,
	uxth	r3, r1	@ tmp148, tmp147
	cmp	r3, r2	@ tmp148, tmp149
	mla	r4, r4, r8, r6	@ pRepairParam, tmp145, VdhId, tmp146
	bls	.L429	@,
	sub	lr, r0, #2048	@ tmp150, D.32302,
	sub	ip, lr, #1	@ tmp150, tmp150,
	uxth	r7, ip	@ tmp152, tmp150
	cmp	r7, r2	@ tmp152, tmp149
	movls	sl, #32	@ level,
	bhi	.L436	@,
.L431:
	movw	r7, #:lower16:78036	@ tmp162,
	movt	r7, #:upper16:78036	@ tmp162,
	movw	r6, #12384	@ tmp164,
	movw	r3, #12388	@ tmp166,
	ldr	r0, [r5, r7]	@ <variable>.ystaddr_1d, <variable>.ystaddr_1d
	movw	r2, #:lower16:78072	@ tmp170,
	movt	r2, #:upper16:78072	@ tmp170,
	mov	r7, #1	@ tmp176,
	movw	lr, #:lower16:16382	@ D.32333,
	movt	lr, #:upper16:16382	@ D.32333,
	str	r0, [r4, #4]	@ <variable>.ystaddr_1d, <variable>.ImageAddr
	movw	r1, #:lower16:.LC9	@,
	ldr	ip, [r5, r6]	@ <variable>.CurFrmImgLuma2dPhyAddr, <variable>.CurFrmImgLuma2dPhyAddr
	movt	r1, #:upper16:.LC9	@,
	mov	r6, #0	@ tmp177,
	mov	r0, #22	@,
	str	ip, [r4, #8]	@ <variable>.CurFrmImgLuma2dPhyAddr, <variable>.Image2DAddr
	ldr	ip, [r5, r3]	@ <variable>.FwdRefAddr, <variable>.FwdRefAddr
	movw	r3, #12396	@ tmp168,
	str	ip, [r4, #16]	@ <variable>.FwdRefAddr, <variable>.RefImageAddr
	ldr	ip, [r5, r3]	@ <variable>.CurrColmbAddr, <variable>.CurrColmbAddr
	str	ip, [r4, #20]	@ <variable>.CurrColmbAddr, <variable>.CurrPmvAddr
	ldr	r2, [r5, r2]	@ D.32326, <variable>.ChanMaxWidthInMb
	str	r2, [r4, #24]	@ D.32326, <variable>.ImageWidth
	ldrh	r3, [r5, #76]	@ <variable>.DispPicHeight, <variable>.DispPicHeight
	str	r7, [r4, #32]	@ tmp176, <variable>.IsFrame
	add	ip, r3, #15	@ tmp172, <variable>.DispPicHeight,
	str	r6, [r4, #36]	@ tmp177, <variable>.ImageCSP
	mov	r3, ip, asr #4	@ tmp173, tmp172,
	add	ip, r3, r7	@ tmp174, tmp173,
	and	r3, ip, lr	@ D.32333, tmp174, D.32333
	str	r3, [r4, #28]	@ D.32333, <variable>.ImageHeight
	bl	dprint_vfmw	@
	ldr	ip, [r4, #28]	@ <variable>.ImageHeight, <variable>.ImageHeight
	ldr	r0, [r4, #24]	@ <variable>.ImageWidth, <variable>.ImageWidth
	movw	r2, #:lower16:g_vdm_hal_fun_ptr	@ tmp195,
	movt	r2, #:upper16:g_vdm_hal_fun_ptr	@ tmp195,
	movw	r3, #:lower16:78068	@ tmp190,
	movt	r3, #:upper16:78068	@ tmp190,
	str	r6, [r4, #844]	@ tmp177, <variable>.rpr_ref_pic_type
	mul	r1, r0, ip	@ tmp186, <variable>.ImageWidth, <variable>.ImageHeight
	ldr	ip, [r2, #104]	@ D.32345, g_vdm_hal_fun_ptr.pfun_VDMHAL_PrepareRepair
	str	r7, [r4, #840]	@ tmp176, <variable>.ValidGroupNum
	strh	r6, [r4, #40]	@ movhi	@ tmp177, <variable>.StartMbn
	cmp	ip, r6	@ D.32345,
	sub	r2, r1, #1	@ tmp188, tmp186,
	strh	r2, [r4, #42]	@ movhi	@ tmp188, <variable>.EndMbn
	ldr	r2, [r5, r3]	@ <variable>.Compress_en, <variable>.Compress_en
	moveq	r0, r7	@ D.32348, tmp176
	str	sl, [r4, #860]	@ level, <variable>.level
	str	r6, [r4, #852]	@ tmp177, <variable>.Pic_type
	str	r2, [r4, #848]	@ <variable>.Compress_en, <variable>.Compress_en
	str	r7, [r4, #856]	@ tmp176, <variable>.FullRepair
	ldmeqfd	sp, {r4, r5, r6, r7, r8, sl, fp, sp, pc}	@
	mov	r0, r7	@, tmp176
	mov	r1, r5	@, pVc1DecParam
	mov	r2, r6	@, tmp177
	mov	r3, r8	@, VdhId
	blx	ip	@ D.32345
	subs	r0, r0, #0	@ D.32348,,
	movne	r0, #1	@ D.32348
	ldmfd	sp, {r4, r5, r6, r7, r8, sl, fp, sp, pc}	@
.L436:
	sub	r6, r0, #4096	@ tmp154, D.32302,
	sub	r1, r6, #1	@ tmp154, tmp154,
	uxth	r3, r1	@ tmp156, tmp154
	cmp	r3, r2	@ tmp156, tmp149
	movls	sl, #48	@ level,
	bls	.L431	@,
	sub	ip, r0, #6144	@ tmp158, D.32302,
	sub	r7, ip, #1	@ tmp158, tmp158,
	uxth	r0, r7	@ tmp160, tmp158
	cmp	r0, r2	@ tmp160, tmp149
	movls	sl, #64	@ level,
	bls	.L431	@,
.L429:
	mov	sl, #16	@ level,
	b	.L431	@
	.fnend
	.size	PostPro_CopyYuv_Vc1, .-PostPro_CopyYuv_Vc1
	.align	2
	.global	PostPro_GetErrRatio
	.type	PostPro_GetErrRatio, %function
PostPro_GetErrRatio:
	.fnstart
.LFB1524:
	@ args = 0, pretend = 0, frame = 16
	@ frame_needed = 1, uses_anonymous_args = 0
	.movsp ip
	mov	ip, sp	@,
	stmfd	sp!, {r4, r5, r6, r7, r8, fp, ip, lr, pc}	@,
	.pad #4
	.save {r4, r5, r6, r7, r8, fp, ip, lr}
	.setfp fp, ip, #-4
	sub	fp, ip, #4	@,,
	.pad #20
	sub	sp, sp, #20	@,,
	push	{lr}
	bl	__gnu_mcount_nc
	subs	r3, r0, #0	@ pParam, pParam
	beq	.L443	@,
	sub	r8, fp, #48	@ tmp143,,
	ldr	r4, [r3, #8]	@ VdhId, <variable>.VdhId
	mov	r1, #12	@,
	ldr	r6, [r3, #0]	@ VidStd, <variable>.VidStd
	mov	r0, r8	@, tmp143
	ldr	r7, [r3, #4]	@ pDecParam, <variable>.pDecParam
	bl	__memzero	@
	movw	r2, #:lower16:g_DecReport	@ tmp146,
	movt	r2, #:upper16:g_DecReport	@ tmp146,
	mov	r5, #816	@ tmp145,
	movw	r3, #:lower16:g_vdm_hal_fun_ptr	@ tmp147,
	movt	r3, #:upper16:g_vdm_hal_fun_ptr	@ tmp147,
	mla	r5, r5, r4, r2	@ pDecReport, tmp145, VdhId, tmp146
	ldr	r3, [r3, #108]	@ D.32234, g_vdm_hal_fun_ptr.pfun_VDMHAL_MakeDecReport
	str	r6, [fp, #-48]	@ VidStd, MakeDecReport.VidStd
	cmp	r3, #0	@ D.32234,
	str	r4, [fp, #-40]	@ VdhId, MakeDecReport.VdhId
	str	r5, [fp, #-44]	@ pDecReport, MakeDecReport.pDecReport
	beq	.L440	@,
	mov	r0, r8	@, tmp143
	blx	r3	@ D.32234
.L441:
	movw	r0, #:lower16:g_RepairParam	@ tmp153,
	movt	r0, #:upper16:g_RepairParam	@ tmp153,
	mov	r1, #1744	@ tmp151,
	mov	r2, r7	@, pDecParam
	mla	r1, r1, r4, r0	@, tmp151, VdhId, tmp153
	mov	r3, r5	@, pDecReport
	mov	r0, r6	@, VidStd
	bl	PostPro_GetRepairParam	@
	movw	r1, #:lower16:.LC12	@,
	movt	r1, #:upper16:.LC12	@,
	mov	r4, r0	@ err_ratio,
	mov	r0, #22	@,
	mov	r2, r4	@, err_ratio
	bl	dprint_vfmw	@
.L439:
	mov	r0, r4	@, err_ratio
	sub	sp, fp, #32
	ldmfd	sp, {r4, r5, r6, r7, r8, fp, sp, pc}
.L440:
	mov	r0, r3	@, D.32234
	movw	r1, #:lower16:.LC11	@,
	mov	r2, #106	@,
	movt	r1, #:upper16:.LC11	@,
	bl	dprint_vfmw	@
	b	.L441	@
.L443:
	movw	r1, #:lower16:.LC10	@,
	movt	r1, #:upper16:.LC10	@,
	bl	dprint_vfmw	@
	mov	r4, #1	@ err_ratio,
	b	.L439	@
	.fnend
	.size	PostPro_GetErrRatio, .-PostPro_GetErrRatio
	.section	.rodata
	.align	2
.LANCHOR0 = . + 0
	.type	__func__.33596, %object
	.size	__func__.33596, 21
__func__.33596:
	.ascii	"PostPro_SetDecReport\000"
	.space	3
	.type	__func__.32832, %object
	.size	__func__.32832, 23
__func__.32832:
	.ascii	"PostPro_GetHevcMbGroup\000"
	.space	1
	.type	__func__.32441, %object
	.size	__func__.32441, 23
__func__.32441:
	.ascii	"PostPro_GetRepairParam\000"
	.section	.rodata.str1.4,"aMS",%progbits,1
	.align	2
.LC0:
	.ascii	"%s %d VidStd Err!\012\000"
	.space	1
.LC1:
	.ascii	"DecSliceNum(=%d) out of range!\012\000"
.LC2:
	.ascii	"DecSliceNum out of range!\012\000"
	.space	1
.LC3:
	.ascii	"line:%d! pRepairParam->ValidGroupNum > (MAX_UP_MSG_"
	.ascii	"SLICE_NUM - 1)\012\000"
	.space	1
.LC4:
	.ascii	"pRepairParam->ValidGroupNum >(MAX_UP_MSG_SLICE_NUM "
	.ascii	"- 1)\012\000"
	.space	3
.LC5:
	.ascii	"%s:0 pRepairParam->ValidGroupNum(%d) > (MAX_UP_MSG_"
	.ascii	"SLICE_NUM - 1)\012\000"
	.space	1
.LC6:
	.ascii	"%s:1 pRepairParam->ValidGroupNum(%d) > (MAX_UP_MSG_"
	.ascii	"SLICE_NUM - 1)\012\000"
	.space	1
.LC7:
	.ascii	"pRepairParam[0].MbGroup[i].EndMbn=%d,pRepairParam[0"
	.ascii	"].MbGroup[i].StartMbn=%d\012\000"
	.space	3
.LC8:
	.ascii	"total_mbs=%d,err_mbs=%d\012\000"
	.space	3
.LC9:
	.ascii	"pRepairParam->ImageWidth=%d,pRepairParam->ImageHeig"
	.ascii	"ht=%d\012\000"
	.space	2
.LC10:
	.ascii	"PostPro_GetErrRatio: pParam = NULL\012\000"
.LC11:
	.ascii	"VDMHAL_NULL_FUN_PRINT,L%d\012\000"
	.space	1
.LC12:
	.ascii	"err_ratio=%d\012\000"
	.ident	"GCC: (Hisilicon_v200(gcc4.4-290+glibc-2.11+eabi+nptl)) 4.4.1"
	.section	.note.GNU-stack,"",%progbits
